from __future__ import annotations


DEFAULT_NOTIFICATION_TEMPLATES = [
    {
        "template_key": "renewal_reminder_90",
        "event_key": "renewal_due",
        "channel": "WHATSAPP",
        "content_mode": "template",
        "language": "en",
        "provider_template_name": "renewal_reminder_90",
        "provider_template_category": "UTILITY",
        "body_template": "Your policy {{ policy }} renewal period is approaching.",
        "whatsapp_body_template": "Your policy {{ policy }} renewal period is approaching.",
        "is_active": 1,
    },
    {
        "template_key": "renewal_reminder_30",
        "event_key": "renewal_due",
        "channel": "WHATSAPP",
        "content_mode": "template",
        "language": "en",
        "provider_template_name": "renewal_reminder_30",
        "provider_template_category": "UTILITY",
        "body_template": "{{ policy }} has 30 days left until expiry.",
        "whatsapp_body_template": "{{ policy }} has 30 days left until expiry.",
        "is_active": 1,
    },
    {
        "template_key": "renewal_reminder_15",
        "event_key": "renewal_due",
        "channel": "WHATSAPP",
        "content_mode": "template",
        "language": "en",
        "provider_template_name": "renewal_reminder_15",
        "provider_template_category": "UTILITY",
        "body_template": "{{ policy }} has 15 days left until expiry.",
        "whatsapp_body_template": "{{ policy }} has 15 days left until expiry.",
        "is_active": 1,
    },
    {
        "template_key": "renewal_reminder_7",
        "event_key": "renewal_due",
        "channel": "WHATSAPP",
        "content_mode": "template",
        "language": "en",
        "provider_template_name": "renewal_reminder_7",
        "provider_template_category": "UTILITY",
        "body_template": "{{ policy }} has 7 days left until expiry.",
        "whatsapp_body_template": "{{ policy }} has 7 days left until expiry.",
        "is_active": 1,
    },
    {
        "template_key": "payment_due_7",
        "event_key": "payment_due",
        "channel": "WHATSAPP",
        "content_mode": "template",
        "language": "en",
        "provider_template_name": "payment_due_7",
        "provider_template_category": "UTILITY",
        "body_template": "{{ payment }} is due in 7 days.",
        "whatsapp_body_template": "{{ payment }} is due in 7 days.",
        "is_active": 1,
    },
    {
        "template_key": "payment_due_overdue",
        "event_key": "payment_due",
        "channel": "WHATSAPP",
        "content_mode": "template",
        "language": "en",
        "provider_template_name": "payment_due_overdue",
        "provider_template_category": "UTILITY",
        "body_template": "{{ payment }} is overdue.",
        "whatsapp_body_template": "{{ payment }} is overdue.",
        "is_active": 1,
    },
    {
        "template_key": "claim_status_approved",
        "event_key": "claim_status_update",
        "channel": "WHATSAPP",
        "content_mode": "template",
        "language": "en",
        "provider_template_name": "claim_status_approved",
        "provider_template_category": "UTILITY",
        "body_template": "{{ claim }} claim has been approved.",
        "whatsapp_body_template": "{{ claim }} claim has been approved.",
        "is_active": 1,
    },
    {
        "template_key": "policy_delivery",
        "event_key": "policy_created",
        "channel": "WHATSAPP",
        "content_mode": "template",
        "language": "en",
        "provider_template_name": "policy_delivery",
        "provider_template_category": "UTILITY",
        "body_template": "Your policy {{ policy_no }} is ready.",
        "whatsapp_body_template": "Your policy {{ policy_no }} is ready.",
        "is_active": 1,
    },
]
