from __future__ import annotations


DEFAULT_NOTIFICATION_TEMPLATES = [
    {
        "template_key": "renewal_reminder_90",
        "event_key": "renewal_due",
        "channel": "WHATSAPP",
        "content_mode": "template",
        "language": "tr",
        "provider_template_name": "renewal_reminder_90",
        "provider_template_category": "UTILITY",
        "body_template": "Policeniz {{ policy }} icin yenileme donemi yaklasiyor.",
        "whatsapp_body_template": "Policeniz {{ policy }} icin yenileme donemi yaklasiyor.",
        "is_active": 1,
    },
    {
        "template_key": "renewal_reminder_30",
        "event_key": "renewal_due",
        "channel": "WHATSAPP",
        "content_mode": "template",
        "language": "tr",
        "provider_template_name": "renewal_reminder_30",
        "provider_template_category": "UTILITY",
        "body_template": "{{ policy }} policenizin bitisine 30 gun kaldi.",
        "whatsapp_body_template": "{{ policy }} policenizin bitisine 30 gun kaldi.",
        "is_active": 1,
    },
    {
        "template_key": "payment_due_7",
        "event_key": "payment_due",
        "channel": "WHATSAPP",
        "content_mode": "template",
        "language": "tr",
        "provider_template_name": "payment_due_7",
        "provider_template_category": "UTILITY",
        "body_template": "{{ payment }} odemenizin vadesine 7 gun kaldi.",
        "whatsapp_body_template": "{{ payment }} odemenizin vadesine 7 gun kaldi.",
        "is_active": 1,
    },
    {
        "template_key": "payment_due_overdue",
        "event_key": "payment_due",
        "channel": "WHATSAPP",
        "content_mode": "template",
        "language": "tr",
        "provider_template_name": "payment_due_overdue",
        "provider_template_category": "UTILITY",
        "body_template": "{{ payment }} odemenizin vadesi gecmistir.",
        "whatsapp_body_template": "{{ payment }} odemenizin vadesi gecmistir.",
        "is_active": 1,
    },
    {
        "template_key": "claim_status_approved",
        "event_key": "claim_status_update",
        "channel": "WHATSAPP",
        "content_mode": "template",
        "language": "tr",
        "provider_template_name": "claim_status_approved",
        "provider_template_category": "UTILITY",
        "body_template": "{{ claim }} hasar dosyaniz onaylandi.",
        "whatsapp_body_template": "{{ claim }} hasar dosyaniz onaylandi.",
        "is_active": 1,
    },
    {
        "template_key": "policy_delivery",
        "event_key": "policy_created",
        "channel": "WHATSAPP",
        "content_mode": "template",
        "language": "tr",
        "provider_template_name": "policy_delivery",
        "provider_template_category": "UTILITY",
        "body_template": "{{ policy_no }} numarali policeniz hazirdir.",
        "whatsapp_body_template": "{{ policy_no }} numarali policeniz hazirdir.",
        "is_active": 1,
    },
]
