export const offerBoardCopy = {
  tr: {
    breadcrumb: "Sigorta Operasyonları → Teklifler",
    recordCount: "kayıt",
    title: "Teklif Panosu",
    subtitle: "Tekliflerinizi kanban görünümünde yönetin",
    focusFilters: "Filtrele",
    filtersTitle: "Filtreler",
    offerTableTitle: "Teklif Listesi",
    pipelineTitle: "Teklif Panosu",
    summaryTotal: "Toplam Teklif",
    summaryDraft: "Taslak",
    summarySent: "Gönderildi",
    summaryAccepted: "Kabul Edildi",
    summaryConversion: "Dönüşüm Oranı",
    viewList: "Liste",
    viewBoard: "Pano",
    newOffer: "Yeni Teklif",
    quickOfferTitle: "Hızlı Teklif Oluştur",
    customerField: "Müşteri",
    customerPlaceholder: "Müşteri ara veya yaz",
    createCustomerCta: "+ Yeni Müşteri Oluştur",
    noCustomersFound: "Müşteri bulunamadı. Yeni müşteri olarak oluşturabilirsiniz.",
    selectedCustomer: "Seçili Müşteri",
    clearSelection: "Temizle",
    branchField: "Sigorta Branşı",
    branchPlaceholder: "Branş seçin (opsiyonel)",
    notesField: "Notlar",
    createQuickOffer: "Teklifi Oluştur",
    createQuickOfferAndOpen: "Kaydet ve Aç",
    quickCreateValidationFailed: "Lütfen gerekli alanları kontrol edin.",
    refresh: "Yenile",
    exportXlsx: "Excel",
    exportPdf: "PDF",
    searchPlaceholder: "Teklif / Müşteri / Kayıt ara",
    allCompanies: "Tüm Sigorta Şirketleri",
    allBranches: "Tüm Branşlar",
    allStatuses: "Tüm Durumlar",
    validUntilFilter: "Geçerlilik Tarihi",
    advancedFilters: "Gelişmiş Filtreler",
    hideAdvancedFilters: "Gelişmiş Filtreleri Gizle",
    activeFilters: "aktif filtre",
    presetLabel: "Filtre Şablonu",
    presetDefault: "Standart",
    presetActionable: "Aksiyon Bekleyenler",
    presetConverted: "Poliçeye Dönüşenler",
    presetExpiring7: "7 Gün İçerisinde Geçerlilik",
    savePreset: "Kaydet",
    deletePreset: "Sil",
    savePresetPrompt: "Filtre şablonu adı",
    deletePresetConfirm: "Seçili özel filtre şablonu silinsin mi?",
    applyFilters: "Uygula",
    clearFilters: "Filtreleri Temizle",
    grossMinFilter: "Min Brüt Prim",
    grossMaxFilter: "Max Brüt Prim",
    actionableOnly: "Sadece Aksiyon Bekleyen",
    showingRecords: "kayıt gösteriliyor",
    showing: "Gösterilen",
    page: "Sayfa",
    previous: "Önceki",
    next: "Sonraki",
    colOffer: "Teklif",
    colDetails: "Detaylar",
    colStatus: "Durum",
    colPremiums: "Primler",
    colActions: "Aksiyon",
    offerDate: "Teklif Tarihi",
    validUntil: "Geçerlilik",
    grossPremium: "Brüt Prim",
    netPremiumShort: "Net Prim",
    commissionShort: "Komisyon",
    recordId: "Kayıt",
    openDesk: "Yönetim Ekranını Aç",
    sortModifiedDesc: "Son Güncellenen",
    sortValidUntilAsc: "Geçerlilik (Yakın)",
    sortValidUntilDesc: "Geçerlilik (Uzak)",
    sortGrossDesc: "Brüt Prim (Yüksek)",
    stage: "Aşama",
    loading: "Yükleniyor...",
    loadErrorTitle: "Teklifler Yüklenemedi",
    loadError: "Teklif panosu verileri yüklenirken bir hata oluştu. Lütfen tekrar deneyin.",
    emptyTitle: "Teklif Bulunamadı",
    empty: "Teklif kaydı bulunamadı.",
    emptyLane: "Bu asamada teklif yok.",
    customerName: "Müşteri Adı",
    premiumAmount: "Prim Tutarı",
    company: "Sigorta Şirketi",
    draftLane: "Taslak",
    sentLane: "Müşteriye Gönderildi",
    acceptedLane: "Kabul Edildi",
    convertedLane: "Poliçeye Dönüştü",
    convert: "Poliçeye Çevir",
    openPolicy: "Poliçeyi Aç",
    convertDialogTitle: "Teklif -> Poliçe",
    selectedOffer: "Seçili Teklif",
    netPremium: "Net Prim",
    taxAmount: "Vergi Tutarı",
    commissionAmount: "Komisyon Tutarı",
    policyNo: "Sigorta Şirketi Poliçe No (Opsiyonel)",
    cancel: "İptal",
    createPolicy: "Poliçe Oluştur",
    statusDraft: "Taslak",
    statusSent: "Gönderildi",
    statusAccepted: "Kabul Edildi",
    statusConverted: "Dönüştü",
    statusRejected: "Reddedildi",
    customerSearchFailed: "Müşteri araması başarısız oldu.",
    quickOfferCreateFailed: "Hızlı teklif oluşturma işlemi başarısız oldu.",
    statusUpdateFailed: "Teklif durumu güncellenemedi.",
    conversionFailed: "Teklif poliçeye dönüştürülemedi.",
  },
  en: {
    breadcrumb: "Insurance Operations → Offers",
    recordCount: "records",
    title: "Offer Board",
    subtitle: "Manage your offers in a Kanban view",
    focusFilters: "Focus Filters",
    filtersTitle: "Filters",
    offerTableTitle: "Offer List",
    pipelineTitle: "Offer Pipeline",
    summaryTotal: "Total Offers",
    summaryDraft: "Draft",
    summarySent: "Sent",
    summaryAccepted: "Accepted",
    summaryConversion: "Conversion Rate",
    viewList: "List",
    viewBoard: "Board",
    newOffer: "New Offer",
    quickOfferTitle: "Create Quick Offer",
    customerField: "Customer",
    customerPlaceholder: "Search or type customer",
    createCustomerCta: "+ Create New Customer",
    noCustomersFound: "No matching customer found. You can create a new one.",
    selectedCustomer: "Selected Customer",
    clearSelection: "Clear",
    branchField: "Insurance Branch",
    branchPlaceholder: "Select branch (optional)",
    notesField: "Notes",
    createQuickOffer: "Create Offer",
    createQuickOfferAndOpen: "Save & Open",
    quickCreateValidationFailed: "Please check required fields.",
    refresh: "Refresh",
    exportXlsx: "Excel",
    exportPdf: "PDF",
    searchPlaceholder: "Search offer / customer / record",
    allCompanies: "All Insurance Companies",
    allBranches: "All Branches",
    allStatuses: "All Statuses",
    validUntilFilter: "Valid Until",
    advancedFilters: "Advanced Filters",
    hideAdvancedFilters: "Hide Advanced Filters",
    activeFilters: "active filters",
    presetLabel: "Filter Preset",
    presetDefault: "Standard",
    presetActionable: "Action Waiting",
    presetConverted: "Converted to Policy",
    presetExpiring7: "Valid in 7 Days",
    savePreset: "Save",
    deletePreset: "Delete",
    savePresetPrompt: "Filter preset name",
    deletePresetConfirm: "Delete selected custom filter preset?",
    applyFilters: "Apply",
    clearFilters: "Clear Filters",
    grossMinFilter: "Min Gross Premium",
    grossMaxFilter: "Max Gross Premium",
    actionableOnly: "Action Waiting Only",
    showingRecords: "records shown",
    showing: "Showing",
    page: "Page",
    previous: "Previous",
    next: "Next",
    colOffer: "Offer",
    colDetails: "Details",
    colStatus: "Status",
    colPremiums: "Premiums",
    colActions: "Actions",
    offerDate: "Offer Date",
    validUntil: "Valid Until",
    grossPremium: "Gross Premium",
    netPremiumShort: "Net Premium",
    commissionShort: "Commission",
    recordId: "Record",
    openDesk: "Open Desk",
    sortModifiedDesc: "Last Modified",
    sortValidUntilAsc: "Valid Until (Soonest)",
    sortValidUntilDesc: "Valid Until (Latest)",
    sortGrossDesc: "Gross Premium (High)",
    stage: "Stage",
    loading: "Loading...",
    loadErrorTitle: "Failed to Load Offers",
    loadError: "An error occurred while loading offer board data. Please try again.",
    emptyTitle: "No Offers Found",
    empty: "No offer records found.",
    emptyLane: "No offers in this stage.",
    customerName: "Customer Name",
    premiumAmount: "Premium Amount",
    company: "Insurance Company",
    draftLane: "Draft",
    sentLane: "Sent to Customer",
    acceptedLane: "Accepted",
    convertedLane: "Converted to Policy",
    convert: "Convert to Policy",
    openPolicy: "Open Policy",
    convertDialogTitle: "Offer -> Policy",
    selectedOffer: "Selected offer",
    netPremium: "Net Premium",
    taxAmount: "Tax Amount",
    commissionAmount: "Commission Amount",
    policyNo: "Carrier Policy Number (Optional)",
    cancel: "Cancel",
    createPolicy: "Create Policy",
    statusDraft: "Draft",
    statusSent: "Sent",
    statusAccepted: "Accepted",
    statusConverted: "Converted",
    statusRejected: "Rejected",
    customerSearchFailed: "Customer search failed.",
    quickOfferCreateFailed: "Quick offer creation failed.",
    statusUpdateFailed: "Status update failed.",
    conversionFailed: "Conversion failed.",
  },
};

