export const reportCatalog = {
  policy_list: {
    label: { tr: "Poliçe Listesi", en: "Policy List" },
    readMethod: "acentem_takipte.acentem_takipte.api.reports.get_policy_list_report",
    exportMethod: "acentem_takipte.acentem_takipte.api.reports.export_policy_list_report",
  },
  payment_status: {
    label: { tr: "Tahsilat Durumu", en: "Payment Status" },
    readMethod: "acentem_takipte.acentem_takipte.api.reports.get_payment_status_report",
    exportMethod: "acentem_takipte.acentem_takipte.api.reports.export_payment_status_report",
  },
  renewal_performance: {
    label: { tr: "Yenileme Performansı", en: "Renewal Performance" },
    readMethod: "acentem_takipte.acentem_takipte.api.reports.get_renewal_performance_report",
    exportMethod: "acentem_takipte.acentem_takipte.api.reports.export_renewal_performance_report",
  },
  claim_loss_ratio: {
    label: { tr: "Hasar/Prim Oranı", en: "Claim Loss Ratio" },
    readMethod: "acentem_takipte.acentem_takipte.api.reports.get_claim_loss_ratio_report",
    exportMethod: "acentem_takipte.acentem_takipte.api.reports.export_claim_loss_ratio_report",
  },
  agent_performance: {
    label: { tr: "Acente Üretim Karnesi", en: "Agency Performance Scorecard" },
    readMethod: "acentem_takipte.acentem_takipte.api.reports.get_agent_performance_report",
    exportMethod: "acentem_takipte.acentem_takipte.api.reports.export_agent_performance_report",
  },
  customer_segmentation: {
    label: { tr: "Müşteri Segmentasyonu", en: "Customer Segmentation" },
    readMethod: "acentem_takipte.acentem_takipte.api.reports.get_customer_segmentation_report",
    exportMethod: "acentem_takipte.acentem_takipte.api.reports.export_customer_segmentation_report",
  },
  communication_operations: {
    label: { tr: "İletişim Operasyonları", en: "Communication Operations" },
    readMethod: "acentem_takipte.acentem_takipte.api.reports.get_communication_operations_report",
    exportMethod: "acentem_takipte.acentem_takipte.api.reports.export_communication_operations_report",
  },
  reconciliation_operations: {
    label: { tr: "Mutabakat Operasyonları", en: "Reconciliation Operations" },
    readMethod: "acentem_takipte.acentem_takipte.api.reports.get_reconciliation_operations_report",
    exportMethod: "acentem_takipte.acentem_takipte.api.reports.export_reconciliation_operations_report",
  },
  claims_operations: {
    label: { tr: "Hasar Operasyonları", en: "Claims Operations" },
    readMethod: "acentem_takipte.acentem_takipte.api.reports.get_claims_operations_report",
    exportMethod: "acentem_takipte.acentem_takipte.api.reports.export_claims_operations_report",
  },
};

export const columnLabels = {
  name: { tr: "Kayıt No", en: "Record Number" },
  customer: { tr: "Müşteri", en: "Customer" },
  customer_full_name: { tr: "Müşteri Ad Soyad", en: "Customer Full Name" },
  customer_tax_id: { tr: "TC/VKN", en: "Tax ID" },
  policy: { tr: "Poliçe", en: "Policy" },
  policy_no: { tr: "Sigorta Şirketi Poliçe No", en: "Carrier Policy Number" },
  office_branch: { tr: "Ofis Şube", en: "Office Branch" },
  branch: { tr: "Sigorta Branşı", en: "Insurance Branch" },
  insurance_company: { tr: "Sigorta Şirketi", en: "Insurance Company" },
  sales_entity: { tr: "Satış Birimi", en: "Sales Entity" },
  sales_entity_full_name: { tr: "Satış Birimi Ad Soyad", en: "Sales Entity Full Name" },
  assigned_agent: { tr: "Atanan Temsilci", en: "Assigned Agent" },
  status: { tr: "Durum", en: "Status" },
  claim_status: { tr: "Hasar Durumu", en: "Claim Status" },
  assigned_to: { tr: "Atanan Kişi", en: "Assigned To" },
  issue_date: { tr: "Tanzim Tarihi", en: "Issue Date" },
  period: { tr: "Dönem", en: "Period" },
  period_label: { tr: "Dönem Etiketi", en: "Period Label" },
  start_date: { tr: "Başlangıç Tarihi", en: "Start Date" },
  end_date: { tr: "Bitiş Tarihi", en: "End Date" },
  renewal_date: { tr: "Yenileme Tarihi", en: "Renewal Date" },
  due_date: { tr: "Vade Tarihi", en: "Due Date" },
  gross_premium: { tr: "Brüt Prim", en: "Gross Premium" },
  total_gross_premium: { tr: "Toplam Brüt Prim", en: "Total Gross Premium" },
  total_premium: { tr: "Toplam Prim", en: "Total Premium" },
  commission_amount: { tr: "Komisyon", en: "Commission" },
  total_commission: { tr: "Toplam Komisyon", en: "Total Commission" },
  paid_amount: { tr: "Ödenen", en: "Paid Amount" },
  approved_amount: { tr: "Onaylanan", en: "Approved Amount" },
  estimated_amount: { tr: "Tahmini Tutar", en: "Estimated Amount" },
  loss_ratio_percent: { tr: "Hasar/Prim Oranı", en: "Loss Ratio" },
  policy_count: { tr: "Poliçe Sayısı", en: "Policy Count" },
  active_policy_count: { tr: "Aktif Poliçe", en: "Active Policies" },
  cancelled_policy_count: { tr: "İptal Poliçe", en: "Cancelled Policies" },
  offer_count: { tr: "Teklif Sayısı", en: "Offer Count" },
  accepted_offer_count: { tr: "Kabul Edilen Teklif", en: "Accepted Offers" },
  converted_offer_count: { tr: "Poliçeye Dönüşen Teklif", en: "Converted Offers" },
  offer_conversion_rate: { tr: "Teklif Dönüşüm Oranı", en: "Offer Conversion Rate" },
  renewal_task_count: { tr: "Yenileme Görevi", en: "Renewal Tasks" },
  completed_renewal_task_count: { tr: "Tamamlanan Yenileme", en: "Completed Renewals" },
  open_renewal_task_count: { tr: "Açık Yenileme Yükü", en: "Open Renewal Load" },
  renewal_success_rate: { tr: "Yenileme Başarı Oranı", en: "Renewal Success Rate" },
  claim_count: { tr: "Hasar Sayısı", en: "Claim Count" },
  claim_history_segment: { tr: "Hasar Geçmişi", en: "Claim History" },
  loyalty_segment: { tr: "Sadakat Segmenti", en: "Loyalty Segment" },
  policy_segment: { tr: "Poliçe Segmenti", en: "Policy Segment" },
  premium_segment: { tr: "Prim Segmenti", en: "Premium Segment" },
  campaign_name: { tr: "Kampanya", en: "Campaign" },
  segment: { tr: "Segment", en: "Segment" },
  channel: { tr: "Kanal", en: "Channel" },
  scheduled_for: { tr: "Planlanan Çalışma", en: "Scheduled Run" },
  last_run_on: { tr: "Son Çalışma", en: "Last Run" },
  matched_customer_count: { tr: "Eşleşen Müşteri", en: "Matched Customers" },
  sent_count: { tr: "Üretilen Taslak", en: "Created Drafts" },
  skipped_count: { tr: "Atlanan", en: "Skipped" },
  draft_count: { tr: "Toplam Taslak", en: "Draft Count" },
  sent_outbox_count: { tr: "Başarılı Gönderim", en: "Successful Deliveries" },
  failed_outbox_count: { tr: "Hatalı Gönderim", en: "Failed Deliveries" },
  accounting_entry: { tr: "Muhasebe Kaydı", en: "Accounting Entry" },
  claim_no: { tr: "Hasar No", en: "Claim No" },
  source_doctype: { tr: "Kaynak Tipi", en: "Source Type" },
  source_name: { tr: "Kaynak Kayıt", en: "Source Record" },
  mismatch_type: { tr: "Uyumsuzluk Tipi", en: "Mismatch Type" },
  difference_try: { tr: "Fark Tutarı", en: "Difference Amount" },
  resolution_action: { tr: "Çözüm", en: "Resolution" },
  resolved_on: { tr: "Çözüm Tarihi", en: "Resolved On" },
  needs_reconciliation: { tr: "Mutabakat Gerekli", en: "Needs Reconciliation" },
  assigned_expert: { tr: "Eksper", en: "Assigned Expert" },
  rejection_reason: { tr: "Red Sebebi", en: "Rejection Reason" },
  appeal_status: { tr: "İtiraz Durumu", en: "Appeal Status" },
  next_follow_up_on: { tr: "Sonraki Takip", en: "Next Follow-up" },
  reported_date: { tr: "Bildirim Tarihi", en: "Reported Date" },
  unique_key: { tr: "Benzersiz Anahtar", en: "Unique Key" },
};

export const reportFilterConfig = {
  policy_list: ["branch", "insuranceCompany", "policyNo", "customerTaxId", "status"],
  payment_status: ["branch", "insuranceCompany", "status"],
  renewal_performance: ["branch", "salesEntity", "status"],
  claim_loss_ratio: ["branch", "insuranceCompany", "status"],
  agent_performance: ["branch", "salesEntity"],
  customer_segmentation: ["branch", "salesEntity"],
  communication_operations: ["status"],
  reconciliation_operations: ["status"],
  claims_operations: ["branch", "insuranceCompany", "status"],
};
