from __future__ import annotations

import hashlib
import json
from typing import Any, Iterable

import frappe
from frappe.utils import cint, getdate, now_datetime, today

from acentem_takipte.acentem_takipte.services.export_payload_utils import (
    coerce_columns,
    coerce_filters,
    coerce_rows,
    normalize_export_key,
)


SNAPSHOT_SOURCE_VERSION = "v1"
DEFAULT_SNAPSHOT_LIMIT = 1000
DEFAULT_SNAPSHOT_REPORT_KEYS = ("agent_performance", "customer_segmentation")


def build_snapshot_scope_hash(report_key: str, filters: dict[str, Any] | None = None) -> str:
    payload = {
        "report_key": normalize_export_key(report_key),
        "filters": coerce_filters(filters),
    }
    serialized = json.dumps(payload, sort_keys=True, default=str, ensure_ascii=False)
    return hashlib.sha256(serialized.encode("utf-8")).hexdigest()


def load_report_snapshot_payload(
    report_key: str,
    filters: dict[str, Any] | None = None,
    *,
    snapshot_date=None,
) -> dict[str, Any] | None:
    if not _has_snapshot_doctype():
        return None

    normalized_report_key = normalize_export_key(report_key)
    normalized_filters = coerce_filters(filters)
    business_date = getdate(snapshot_date or today())
    scope_hash = build_snapshot_scope_hash(normalized_report_key, normalized_filters)
    snapshot_name = frappe.db.get_value(
        "AT Report Snapshot",
        {
            "report_key": normalized_report_key,
            "snapshot_date": business_date,
            "scope_hash": scope_hash,
        },
        "name",
    )
    if not snapshot_name:
        return None

    snapshot = frappe.get_doc("AT Report Snapshot", snapshot_name)
    return _serialize_snapshot_doc(snapshot)


def store_report_snapshot_payload(
    report_key: str,
    filters: dict[str, Any] | None,
    payload: dict[str, Any] | None,
    *,
    snapshot_date=None,
) -> dict[str, Any] | None:
    if not _has_snapshot_doctype():
        return None

    normalized_report_key = normalize_export_key(report_key)
    normalized_filters = coerce_filters(filters)
    business_date = getdate(snapshot_date or today())
    scope_hash = build_snapshot_scope_hash(normalized_report_key, normalized_filters)
    normalized_payload = _coerce_snapshot_payload(payload)
    rows = normalized_payload["rows"]

    existing_name = frappe.db.get_value(
        "AT Report Snapshot",
        {
            "report_key": normalized_report_key,
            "snapshot_date": business_date,
            "scope_hash": scope_hash,
        },
        "name",
    )
    snapshot = (
        frappe.get_doc("AT Report Snapshot", existing_name)
        if existing_name
        else frappe.get_doc(
            {
                "doctype": "AT Report Snapshot",
                "report_key": normalized_report_key,
                "snapshot_date": business_date,
                "scope_hash": scope_hash,
            }
        )
    )

    snapshot.report_key = normalized_report_key
    snapshot.snapshot_date = business_date
    snapshot.scope_hash = scope_hash
    snapshot.filters_json = json.dumps(normalized_filters, ensure_ascii=False, sort_keys=True)
    snapshot.columns_json = json.dumps(normalized_payload["columns"], ensure_ascii=False)
    snapshot.rows_json = json.dumps(rows, ensure_ascii=False)
    snapshot.row_count = len(rows)
    snapshot.source_version = str(normalized_payload["source_version"] or SNAPSHOT_SOURCE_VERSION)
    snapshot.generated_on = now_datetime()
    snapshot.generated_by = _safe_session_user()
    snapshot.notes = normalized_payload.get("notes") or "Generated by report snapshot pre-aggregation."

    if existing_name:
        snapshot.save(ignore_permissions=True)
    else:
        snapshot.insert(ignore_permissions=True)

    return _serialize_snapshot_doc(snapshot)


def build_snapshot_aware_report_payload(
    report_key: str,
    *,
    filters: dict[str, Any] | None,
    limit: int,
    build_live_payload,
    force_refresh: bool = False,
) -> dict[str, Any]:
    normalized_report_key = normalize_export_key(report_key)
    normalized_filters = coerce_filters(filters)
    normalized_limit = max(cint(limit or 1), 1)

    if not force_refresh:
        snapshot = load_report_snapshot_payload(normalized_report_key, normalized_filters)
        if snapshot:
            snapshot_rows = coerce_rows(snapshot.get("rows"))
            if not snapshot_rows:
                return {
                    "report_key": normalized_report_key,
                    "columns": coerce_columns(snapshot.get("columns")),
                    "rows": [],
                    "filters": normalized_filters,
                    "total": 0,
                }
            if len(snapshot_rows) >= normalized_limit:
                return {
                    "report_key": normalized_report_key,
                    "columns": coerce_columns(snapshot.get("columns")),
                    "rows": snapshot_rows[:normalized_limit],
                    "filters": coerce_filters(snapshot.get("filters")) or normalized_filters,
                    "total": min(len(snapshot_rows), normalized_limit),
                }

    payload = build_live_payload()
    if isinstance(payload, dict):
        store_report_snapshot_payload(
            normalized_report_key,
            normalized_filters,
            payload,
        )
        return payload

    return {
        "report_key": normalized_report_key,
        "columns": [],
        "rows": [],
        "filters": normalized_filters,
        "total": 0,
    }


def refresh_report_snapshots(
    *,
    report_keys: Iterable[str] | None = None,
    filters_by_report: dict[str, dict[str, Any]] | None = None,
    limit: int = DEFAULT_SNAPSHOT_LIMIT,
) -> dict[str, Any]:
    from acentem_takipte.acentem_takipte.services.report_registry import (
        REPORT_DEFINITIONS,
        build_report_payload,
    )

    target_keys = [
        normalize_export_key(report_key)
        for report_key in (report_keys or DEFAULT_SNAPSHOT_REPORT_KEYS)
    ]
    safe_limit = max(cint(limit or DEFAULT_SNAPSHOT_LIMIT), 1)
    items: list[dict[str, Any]] = []

    for report_key in target_keys:
        if report_key not in REPORT_DEFINITIONS:
            continue
        report_filters = coerce_filters((filters_by_report or {}).get(report_key))
        payload = build_report_payload(
            report_key,
            filters=report_filters,
            limit=safe_limit,
            force_refresh=True,
        )
        items.append(
            {
                "report_key": report_key,
                "filters": report_filters,
                "row_count": len(coerce_rows(payload.get("rows"))),
            }
        )

    return {
        "refreshed": len(items),
        "limit": safe_limit,
        "items": items,
    }


def _coerce_snapshot_payload(value: Any) -> dict[str, Any]:
    if not isinstance(value, dict):
        return {
            "columns": [],
            "rows": [],
            "filters": {},
            "row_count": 0,
            "source_version": SNAPSHOT_SOURCE_VERSION,
            "notes": "",
        }

    return {
        "columns": coerce_columns(value.get("columns")),
        "rows": coerce_rows(value.get("rows")),
        "filters": coerce_filters(value.get("filters")),
        "row_count": max(cint(value.get("row_count")), 0),
        "source_version": str(value.get("source_version") or SNAPSHOT_SOURCE_VERSION),
        "notes": str(value.get("notes") or "").strip(),
    }


def _serialize_snapshot_doc(snapshot_doc) -> dict[str, Any]:
    return {
        "report_key": normalize_export_key(getattr(snapshot_doc, "report_key", "")),
        "snapshot_date": str(getattr(snapshot_doc, "snapshot_date", "") or ""),
        "scope_hash": str(getattr(snapshot_doc, "scope_hash", "") or ""),
        "columns": _parse_json_list(getattr(snapshot_doc, "columns_json", None)),
        "rows": _parse_json_list(getattr(snapshot_doc, "rows_json", None)),
        "filters": _parse_json_object(getattr(snapshot_doc, "filters_json", None)),
        "row_count": max(cint(getattr(snapshot_doc, "row_count", 0)), 0),
        "source_version": str(getattr(snapshot_doc, "source_version", "") or SNAPSHOT_SOURCE_VERSION),
        "generated_on": getattr(snapshot_doc, "generated_on", None),
        "generated_by": str(getattr(snapshot_doc, "generated_by", "") or ""),
        "notes": str(getattr(snapshot_doc, "notes", "") or ""),
    }


def _parse_json_list(value) -> list[Any]:
    try:
        parsed = frappe.parse_json(value) if isinstance(value, str) else value
    except Exception:
        parsed = []
    return parsed if isinstance(parsed, list) else []


def _parse_json_object(value) -> dict[str, Any]:
    try:
        parsed = frappe.parse_json(value) if isinstance(value, str) else value
    except Exception:
        parsed = {}
    return parsed if isinstance(parsed, dict) else {}


def _has_snapshot_doctype() -> bool:
    try:
        return bool(frappe.db.exists("DocType", "AT Report Snapshot"))
    except Exception:
        return False


def _safe_session_user() -> str | None:
    try:
        user = str(getattr(frappe.session, "user", "") or "").strip()
    except Exception:
        user = ""
    return user or None
