export const AUX_WORKBENCH_FIELD_LABELS = {
  tr: {
    "notification-drafts": {
      name: "Kayıt",
      customer: "Müşteri",
      recipient: "Alıcı",
      event_key: "Etkinlik Anahtarı",
      channel: "Kanal",
      status: "Durum",
      reference_doctype: "Referans Tipi",
      reference_name: "Referans Kayıt",
      template: "Şablon",
      subject: "Konu",
      language: "Dil",
      body: "İçerik",
      sent_at: "Gönderim Tarihi",
      outbox_record: "Giden Kayıt",
      error_message: "Hata Mesajı",
      owner: "Kayıt Sahibi",
      modified: "Güncellendi",
    },
    "notification-outbox": {
      name: "Kayıt",
      customer: "Müşteri",
      recipient: "Alıcı",
      event_key: "Etkinlik Anahtarı",
      channel: "Kanal",
      status: "Durum",
      provider: "Sağlayıcı",
      reference_doctype: "Referans Tipi",
      reference_name: "Referans Kayıt",
      draft: "Taslak",
      priority: "Öncelik",
      attempt_count: "Deneme Sayısı",
      max_attempts: "Maks. Deneme",
      next_retry_on: "Sonraki Deneme",
      last_attempt_on: "Son Deneme",
      provider_message_id: "Sağlayıcı Mesaj ID",
      error_message: "Hata Mesajı",
      response_log: "Yanıt Logu",
      owner: "Kayıt Sahibi",
      modified: "Güncellendi",
    },
    companies: {
      name: "Kayıt",
      company_name: "Şirket Adı",
      company_code: "Şirket Kodu",
      is_active: "Aktif",
      owner: "Kayıt Sahibi",
      modified: "Güncellendi",
    },
    branches: {
      name: "Kayıt",
      branch_name: "Branş Adı",
      branch_code: "Branş Kodu",
      insurance_company: "Sigorta Şirketi",
      is_active: "Aktif",
      owner: "Kayıt Sahibi",
      modified: "Güncellendi",
    },
    "sales-entities": {
      name: "Kayıt",
      full_name: "Tam Ad",
      entity_type: "Birim Türü",
      office_branch: "Ofis Şubesi",
      parent_entity: "Üst Birim",
      owner: "Kayıt Sahibi",
      modified: "Güncellendi",
    },
    templates: {
      name: "Kayıt",
      template_key: "Şablon Anahtarı",
      event_key: "Etkinlik Anahtarı",
      channel: "Kanal",
      subject: "Konu",
      language: "Dil",
      is_active: "Aktif",
      body_template: "Şablon İçeriği",
      owner: "Kayıt Sahibi",
      modified: "Güncellendi",
    },
    "accounting-entries": {
      name: "Kayıt",
      source_doctype: "Kaynak Tipi",
      source_name: "Kaynak Kayıt",
      policy: "Poliçe",
      customer: "Müşteri",
      local_amount_try: "Yerel Tutar (TRY)",
      external_amount_try: "Harici Tutar (TRY)",
      difference_try: "Fark (TRY)",
      local_amount: "Yerel Tutar",
      external_amount: "Harici Tutar",
      status: "Durum",
      entry_type: "Kayıt Türü",
      insurance_company: "Sigorta Şirketi",
      external_ref: "Harici Referans",
      needs_reconciliation: "Mutabakat Gerekli",
      last_synced_on: "Son Senkronizasyon",
      sync_attempt_count: "Senkron Deneme Sayısı",
      payload_json: "Payload",
      error_message: "Hata Mesajı",
      currency: "Döviz",
      accounting_entry: "Muhasebe Kaydı",
      owner: "Kayıt Sahibi",
      modified: "Güncellendi",
    },
    "reconciliation-items": {
      name: "Kayıt",
      accounting_entry: "Muhasebe Kaydı",
      source_doctype: "Kaynak Tipi",
      source_name: "Kaynak Kayıt",
      mismatch_type: "Uyumsuzluk Tipi",
      difference_try: "Fark (TRY)",
      local_amount_try: "Yerel Tutar (TRY)",
      external_amount_try: "Harici Tutar (TRY)",
      resolution_action: "Çözüm İşlemi",
      resolved_by: "Çözen Kullanıcı",
      resolved_on: "Çözüm Tarihi",
      unique_key: "Benzersiz Anahtar",
      notes: "Notlar",
      details_json: "Detaylar",
      status: "Durum",
      owner: "Kayıt Sahibi",
      modified: "Güncellendi",
    },
    "access-logs": {
      name: "Kayıt",
      reference_doctype: "Referans Tipi",
      reference_name: "Referans Kayıt",
      viewed_by: "Görüntüleyen",
      action: "Eylem",
      action_summary: "Eylem Özeti",
      decision_context: "Karar Bağlamı",
      ip_address: "IP Adresi",
      viewed_on: "Görüntülenme Tarihi",
      modified: "Güncellendi",
    },
    reminders: {
      name: "Kayıt",
      reminder_title: "Hatırlatıcı Başlığı",
      source_doctype: "Kaynak Tipi",
      source_name: "Kaynak Kayıt",
      customer: "Müşteri",
      policy: "Poliçe",
      claim: "Hasar",
      office_branch: "Ofis Şubesi",
      assigned_to: "Atanan Kişi",
      status: "Durum",
      priority: "Öncelik",
      remind_at: "Hatırlatma Tarihi",
      completed_on: "Tamamlanma Tarihi",
      notes: "Notlar",
      owner: "Kayıt Sahibi",
      modified: "Güncellendi",
    },
    activities: {
      name: "Kayıt",
      activity_title: "Aktivite Başlığı",
      activity_type: "Aktivite Türü",
      source_doctype: "Kaynak Tipi",
      source_name: "Kaynak Kayıt",
      customer: "Müşteri",
      policy: "Poliçe",
      claim: "Hasar",
      office_branch: "Ofis Şubesi",
      assigned_to: "Atanan Kişi",
      status: "Durum",
      activity_at: "Aktivite Tarihi",
      notes: "Notlar",
      owner: "Kayıt Sahibi",
      modified: "Güncellendi",
    },
    "ownership-assignments": {
      name: "Kayıt",
      source_doctype: "Kaynak Tipi",
      source_name: "Kaynak Kayıt",
      customer: "Müşteri",
      policy: "Poliçe",
      assigned_to: "Atanan Kişi",
      assignment_role: "Atama Rolü",
      status: "Durum",
      priority: "Öncelik",
      due_date: "Bitiş Tarihi",
      office_branch: "Ofis Şubesi",
      notes: "Notlar",
      owner: "Kayıt Sahibi",
      modified: "Güncellendi",
    },
    tasks: {
      name: "Kayıt",
      task_title: "Görev Başlığı",
      task_type: "Görev Türü",
      source_doctype: "Kaynak Tipi",
      source_name: "Kaynak Kayıt",
      customer: "Müşteri",
      policy: "Poliçe",
      claim: "Hasar",
      office_branch: "Ofis Şubesi",
      assigned_to: "Atanan Kişi",
      status: "Durum",
      priority: "Öncelik",
      due_date: "Bitiş Tarihi",
      reminder_at: "Hatırlatma Tarihi",
      completed_on: "Tamamlanma Tarihi",
      notes: "Notlar",
      owner: "Kayıt Sahibi",
      modified: "Güncellendi",
    },
    "customer-segment-snapshots": {
      name: "Kayıt",
      customer: "Müşteri",
      office_branch: "Ofis Şubesi",
      snapshot_date: "Snapshot Tarihi",
      segment: "Segment",
      value_band: "Değer Aralığı",
      claim_risk: "Hasar Riski",
      score: "Skor",
      source_version: "Kaynak Sürüm",
      strengths_json: "Güçlü Sinyaller",
      risks_json: "Risk Sinyalleri",
      score_reason_json: "Skor Gerekçeleri",
      owner: "Kayıt Sahibi",
      modified: "Güncellendi",
    },
    "call-notes": {
      name: "Kayıt",
      customer: "Müşteri",
      policy: "Poliçe",
      claim: "Hasar",
      channel: "Kanal",
      direction: "Yön",
      call_status: "Arama Durumu",
      call_outcome: "Arama Sonucu",
      note_at: "Not Tarihi",
      next_follow_up_on: "Sonraki Takip",
      notes: "Notlar",
      owner: "Kayıt Sahibi",
      modified: "Güncellendi",
    },
    segments: {
      name: "Kayıt",
      segment_name: "Segment Adı",
      segment_type: "Segment Türü",
      channel_focus: "Kanal Odağı",
      office_branch: "Ofis Şubesi",
      status: "Durum",
      estimated_customer_count: "Tahmini Müşteri Sayısı",
      criteria_json: "Kriterler",
      notes: "Notlar",
      owner: "Kayıt Sahibi",
      modified: "Güncellendi",
    },
    campaigns: {
      name: "Kayıt",
      campaign_name: "Kampanya Adı",
      segment: "Segment",
      template: "Şablon",
      channel: "Kanal",
      office_branch: "Ofis Şubesi",
      status: "Durum",
      scheduled_for: "Planlanan Tarih",
      sent_count: "Gönderim Sayısı",
      matched_customer_count: "Eşleşen Müşteri",
      skipped_count: "Atlanan",
      last_run_on: "Son Çalıştırma",
      last_run_summary: "Son Çalıştırma Özeti",
      notes: "Notlar",
      owner: "Kayıt Sahibi",
      modified: "Güncellendi",
    },
    "customer-relations": {
      name: "Kayıt",
      customer: "Müşteri",
      related_customer: "İlişkili Müşteri",
      relation_type: "İlişki Türü",
      is_household: "Hane Halkı",
      notes: "Notlar",
      owner: "Kayıt Sahibi",
      modified: "Güncellendi",
    },
    "insured-assets": {
      name: "Kayıt",
      customer: "Müşteri",
      policy: "Poliçe",
      asset_type: "Varlık Türü",
      asset_label: "Varlık Etiketi",
      asset_identifier: "Varlık Tanımlayıcı",
      notes: "Notlar",
      owner: "Kayıt Sahibi",
      modified: "Güncellendi",
    },
    files: {
      name: "Kayıt",
      file_name: "Dosya Adı",
      attached_to_doctype: "Bağlı Belge Tipi",
      attached_to_name: "Bağlı Kayıt",
      file_type: "Dosya Türü",
      file_size: "Dosya Boyutu",
      is_private: "Gizli",
      creation: "Yükleme Tarihi",
      modified: "Güncellendi",
      owner: "Yükleyen",
      file_url: "Dosya URL",
    },
    "at-documents": {
      name: "Kayıt",
      display_name: "Sistem Dosya Adı",
      secondary_file_name: "Doküman Adı",
      original_file_name: "Orijinal Dosya Adı",
      file: "Dosya Kaydı",
      reference_doctype: "Bağlantı Türü",
      reference_name: "Bağlı Kayıt",
      policy: "Poliçe",
      customer: "Müşteri",
      claim: "Hasar",
      document_kind: "Doküman Türü",
      document_sub_type: "Doküman Alt Türü",
      is_sensitive: "Hassas Veri",
      is_verified: "Doğrulandı",
      document_date: "Doküman Tarihi",
      upload_date: "Yükleme Tarihi",
      sequence_no: "Sıra No",
      version_no: "Versiyon No",
      status: "Durum",
      notes: "Notlar",
      creation: "Oluşturulma",
      modified: "Güncellendi",
      owner: "Kayıt Sahibi",
    },
  },
  en: {
    "notification-drafts": {
      name: "Record",
      customer: "Customer",
      recipient: "Recipient",
      event_key: "Event Key",
      channel: "Channel",
      status: "Status",
      reference_doctype: "Reference Type",
      reference_name: "Reference Record",
      template: "Template",
      subject: "Subject",
      language: "Language",
      body: "Body",
      sent_at: "Sent At",
      outbox_record: "Outbox Record",
      error_message: "Error Message",
      owner: "Owner",
      modified: "Modified",
    },
    "notification-outbox": {
      name: "Record",
      customer: "Customer",
      recipient: "Recipient",
      event_key: "Event Key",
      channel: "Channel",
      status: "Status",
      provider: "Provider",
      reference_doctype: "Reference Type",
      reference_name: "Reference Record",
      draft: "Draft",
      priority: "Priority",
      attempt_count: "Attempt Count",
      max_attempts: "Max Attempts",
      next_retry_on: "Next Retry On",
      last_attempt_on: "Last Attempt On",
      provider_message_id: "Provider Message ID",
      error_message: "Error Message",
      response_log: "Response Log",
      owner: "Owner",
      modified: "Modified",
    },
    companies: {
      name: "Record",
      company_name: "Company Name",
      company_code: "Company Code",
      is_active: "Active",
      owner: "Owner",
      modified: "Modified",
    },
    branches: {
      name: "Record",
      branch_name: "Branch Name",
      branch_code: "Branch Code",
      insurance_company: "Insurance Company",
      is_active: "Active",
      owner: "Owner",
      modified: "Modified",
    },
    "sales-entities": {
      name: "Record",
      full_name: "Full Name",
      entity_type: "Entity Type",
      office_branch: "Office Branch",
      parent_entity: "Parent Entity",
      owner: "Owner",
      modified: "Modified",
    },
    templates: {
      name: "Record",
      template_key: "Template Key",
      event_key: "Event Key",
      channel: "Channel",
      subject: "Subject",
      language: "Language",
      is_active: "Active",
      body_template: "Template Body",
      owner: "Owner",
      modified: "Modified",
    },
    "accounting-entries": {
      name: "Record",
      source_doctype: "Source DocType",
      source_name: "Source Record",
      policy: "Policy",
      customer: "Customer",
      local_amount_try: "Local Amount (TRY)",
      external_amount_try: "External Amount (TRY)",
      difference_try: "Difference (TRY)",
      local_amount: "Local Amount",
      external_amount: "External Amount",
      status: "Status",
      entry_type: "Entry Type",
      insurance_company: "Insurance Company",
      external_ref: "External Reference",
      needs_reconciliation: "Needs Reconciliation",
      last_synced_on: "Last Synced On",
      sync_attempt_count: "Sync Attempt Count",
      payload_json: "Payload",
      error_message: "Error Message",
      currency: "Currency",
      accounting_entry: "Accounting Entry",
      owner: "Owner",
      modified: "Modified",
    },
    "reconciliation-items": {
      name: "Record",
      accounting_entry: "Accounting Entry",
      source_doctype: "Source DocType",
      source_name: "Source Record",
      mismatch_type: "Mismatch Type",
      difference_try: "Difference (TRY)",
      local_amount_try: "Local Amount (TRY)",
      external_amount_try: "External Amount (TRY)",
      resolution_action: "Resolution Action",
      resolved_by: "Resolved By",
      resolved_on: "Resolved On",
      unique_key: "Unique Key",
      notes: "Notes",
      details_json: "Details",
      status: "Status",
      owner: "Owner",
      modified: "Modified",
    },
    "access-logs": {
      name: "Record",
      reference_doctype: "Reference Type",
      reference_name: "Reference Record",
      viewed_by: "Viewed By",
      action: "Action",
      action_summary: "Action Summary",
      decision_context: "Decision Context",
      ip_address: "IP Address",
      viewed_on: "Viewed On",
      modified: "Modified",
    },
    reminders: {
      name: "Record",
      reminder_title: "Reminder Title",
      source_doctype: "Source Type",
      source_name: "Source Record",
      customer: "Customer",
      policy: "Policy",
      claim: "Claim",
      office_branch: "Office Branch",
      assigned_to: "Assigned To",
      status: "Status",
      priority: "Priority",
      remind_at: "Remind At",
      completed_on: "Completed On",
      notes: "Notes",
      owner: "Owner",
      modified: "Modified",
    },
    activities: {
      name: "Record",
      activity_title: "Activity Title",
      activity_type: "Activity Type",
      source_doctype: "Source Type",
      source_name: "Source Record",
      customer: "Customer",
      policy: "Policy",
      claim: "Claim",
      office_branch: "Office Branch",
      assigned_to: "Assigned To",
      status: "Status",
      activity_at: "Activity Date",
      notes: "Notes",
      owner: "Owner",
      modified: "Modified",
    },
    "ownership-assignments": {
      name: "Record",
      source_doctype: "Source Type",
      source_name: "Source Record",
      customer: "Customer",
      policy: "Policy",
      assigned_to: "Assigned To",
      assignment_role: "Assignment Role",
      status: "Status",
      priority: "Priority",
      due_date: "Due Date",
      office_branch: "Office Branch",
      notes: "Notes",
      owner: "Owner",
      modified: "Modified",
    },
    tasks: {
      name: "Record",
      task_title: "Task Title",
      task_type: "Task Type",
      source_doctype: "Source Type",
      source_name: "Source Record",
      customer: "Customer",
      policy: "Policy",
      claim: "Claim",
      office_branch: "Office Branch",
      assigned_to: "Assigned To",
      status: "Status",
      priority: "Priority",
      due_date: "Due Date",
      reminder_at: "Reminder At",
      completed_on: "Completed On",
      notes: "Notes",
      owner: "Owner",
      modified: "Modified",
    },
    "customer-segment-snapshots": {
      name: "Record",
      customer: "Customer",
      office_branch: "Office Branch",
      snapshot_date: "Snapshot Date",
      segment: "Segment",
      value_band: "Value Band",
      claim_risk: "Claim Risk",
      score: "Score",
      source_version: "Source Version",
      strengths_json: "Strength Signals",
      risks_json: "Risk Signals",
      score_reason_json: "Score Reasons",
      owner: "Owner",
      modified: "Modified",
    },
    "call-notes": {
      name: "Record",
      customer: "Customer",
      policy: "Policy",
      claim: "Claim",
      channel: "Channel",
      direction: "Direction",
      call_status: "Call Status",
      call_outcome: "Call Outcome",
      note_at: "Note At",
      next_follow_up_on: "Next Follow Up",
      notes: "Notes",
      owner: "Owner",
      modified: "Modified",
    },
    segments: {
      name: "Record",
      segment_name: "Segment Name",
      segment_type: "Segment Type",
      channel_focus: "Channel Focus",
      office_branch: "Office Branch",
      status: "Status",
      estimated_customer_count: "Estimated Customer Count",
      criteria_json: "Criteria",
      notes: "Notes",
      owner: "Owner",
      modified: "Modified",
    },
    campaigns: {
      name: "Record",
      campaign_name: "Campaign Name",
      segment: "Segment",
      template: "Template",
      channel: "Channel",
      office_branch: "Office Branch",
      status: "Status",
      scheduled_for: "Scheduled For",
      sent_count: "Sent Count",
      matched_customer_count: "Matched Customers",
      skipped_count: "Skipped Count",
      last_run_on: "Last Run On",
      last_run_summary: "Last Run Summary",
      notes: "Notes",
      owner: "Owner",
      modified: "Modified",
    },
    "customer-relations": {
      name: "Record",
      customer: "Customer",
      related_customer: "Related Customer",
      relation_type: "Relation Type",
      is_household: "Household",
      notes: "Notes",
      owner: "Owner",
      modified: "Modified",
    },
    "insured-assets": {
      name: "Record",
      customer: "Customer",
      policy: "Policy",
      asset_type: "Asset Type",
      asset_label: "Asset Label",
      asset_identifier: "Asset Identifier",
      notes: "Notes",
      owner: "Owner",
      modified: "Modified",
    },
    files: {
      name: "Record",
      file_name: "File Name",
      attached_to_doctype: "Attached To",
      attached_to_name: "Attached Record",
      file_type: "File Type",
      file_size: "File Size",
      is_private: "Private",
      creation: "Upload Date",
      modified: "Modified",
      owner: "Owner",
      file_url: "File URL",
    },
    "at-documents": {
      name: "Record",
      display_name: "System File Name",
      secondary_file_name: "Document Name",
      original_file_name: "Original File Name",
      file: "File Record",
      reference_doctype: "Link Type",
      reference_name: "Linked Record",
      policy: "Policy",
      customer: "Customer",
      claim: "Claim",
      document_kind: "Document Kind",
      document_sub_type: "Document Sub Type",
      is_sensitive: "Sensitive Data",
      is_verified: "Verified",
      document_date: "Document Date",
      upload_date: "Upload Date",
      sequence_no: "Sequence No",
      version_no: "Version No",
      status: "Status",
      notes: "Notes",
      creation: "Created On",
      modified: "Modified",
      owner: "Owner",
    },
  },
};
