function L(tr, en) {
  return { tr, en };
}

function F(key, field, type = "text", extra = {}) {
  return { key, field, type, ...extra };
}

function P(key, label, payload = {}) {
  return { key, label, payload };
}

export const AUX_WORKBENCH_CONFIGS = {
  tasks: {
    key: "tasks",
    routeSegment: "tasks",
    doctype: "AT Renewal Task",
    labels: { list: L("Gorevler", "Tasks"), detail: L("Gorev Detay", "Task Detail"), section: L("Iletisim ve Takip", "Communication & Follow-up") },
    subtitle: L("Yenileme gorevlerini filtreleyin ve takip edin", "Filter and track renewal tasks"),
    titleField: "name",
    statusField: "status",
    statusType: "renewal",
    listFields: ["name", "policy", "customer", "due_date", "renewal_date", "status", "assigned_to", "auto_created", "modified", "owner"],
    searchFields: ["name", "policy", "customer", "assigned_to", "notes"],
    primaryFields: ["policy", "customer"],
    detailFields: ["assigned_to", "due_date"],
    metricFields: ["renewal_date", "auto_created"],
    summaryFields: ["status", "policy", "customer", "due_date"],
    detailGroups: [{ key: "schedule", fields: ["policy_end_date", "renewal_date", "due_date"] }, { key: "assignment", fields: ["assigned_to", "auto_created", "unique_key", "owner", "modified"] }],
    textFields: ["notes"],
    filterDefs: [F("status", "status", "select", { options: ["", "Open", "In Progress", "Done", "Cancelled"] }), F("customer", "customer", "text", { mode: "like" }), F("policy", "policy", "text", { mode: "like" })],
    presetDefs: [
      P("open", L("Acik Gorevler", "Open Tasks"), { status: "Open", sort: "due_date asc" }),
      P("inProgress", L("Devam Edenler", "In Progress"), { status: "In Progress", sort: "due_date asc" }),
      P("completed", L("Tamamlananlar", "Done"), { status: "Done", sort: "modified desc" }),
    ],
    quickCreate: { registryKey: "renewal_task", label: L("Yeni Gorev", "New Task"), showSaveAndOpen: true },
    sortOptions: ["due_date asc", "renewal_date asc", "modified desc"],
    defaultSort: "due_date asc",
    dateFields: ["policy_end_date", "renewal_date", "due_date"],
    boolFields: ["auto_created"],
  },
  "call-notes": {
    key: "call-notes",
    routeSegment: "call-notes",
    doctype: "AT Call Note",
    labels: { list: L("Arama Notlari", "Call Notes"), detail: L("Arama Notu Detay", "Call Note Detail"), section: L("Iletisim ve Takip", "Communication & Follow-up") },
    subtitle: L("Telefon ve cagri etkileşim kayitlari", "Phone and call interaction records"),
    titleField: "call_outcome",
    statusField: "call_status",
    listFields: ["name", "customer", "policy", "claim", "channel", "direction", "call_status", "call_outcome", "note_at", "next_follow_up_on", "modified"],
    searchFields: ["name", "customer", "policy", "claim", "call_outcome", "notes"],
    primaryFields: ["customer", "policy"],
    detailFields: ["channel", "direction", "call_status"],
    metricFields: ["note_at", "next_follow_up_on"],
    summaryFields: ["call_status", "channel", "direction", "note_at"],
    detailGroups: [{ key: "call", fields: ["customer", "policy", "claim", "channel", "direction", "call_status", "call_outcome", "note_at", "next_follow_up_on", "owner", "modified"] }],
    textFields: ["notes"],
    filterDefs: [F("customer", "customer", "text", { mode: "like" }), F("call_status", "call_status", "text", { mode: "like" }), F("channel", "channel", "text", { mode: "like" })],
    quickCreate: { registryKey: "call_note", label: L("Yeni Arama Notu", "New Call Note"), showSaveAndOpen: true },
    quickEdit: { registryKey: "call_note_edit", label: L("Hizli Duzenle", "Quick Edit") },
    sortOptions: ["note_at desc", "modified desc"],
    defaultSort: "note_at desc",
    dateTimeFields: ["note_at", "modified"],
    dateFields: ["next_follow_up_on"],
  },
  segments: {
    key: "segments",
    routeSegment: "segments",
    doctype: "AT Segment",
    labels: { list: L("Segmentler", "Segments"), detail: L("Segment Detay", "Segment Detail"), section: L("Iletisim ve Takip", "Communication & Follow-up") },
    subtitle: L("Kampanya hedef segmentlerini yonetin", "Manage campaign target segments"),
    titleField: "segment_name",
    statusField: "status",
    listFields: ["name", "segment_name", "segment_type", "channel_focus", "office_branch", "status", "estimated_customer_count", "modified"],
    searchFields: ["name", "segment_name", "segment_type", "channel_focus", "status", "notes"],
    primaryFields: ["segment_name", "segment_type"],
    detailFields: ["channel_focus", "office_branch", "status"],
    metricFields: ["estimated_customer_count", "modified"],
    summaryFields: ["status", "channel_focus", "segment_type", "estimated_customer_count"],
    detailGroups: [{ key: "segment", fields: ["segment_name", "segment_type", "channel_focus", "office_branch", "status", "estimated_customer_count", "owner", "modified"] }],
    textFields: ["criteria_json", "notes"],
    filterDefs: [F("status", "status", "text", { mode: "like" }), F("segment_type", "segment_type", "text", { mode: "like" }), F("channel_focus", "channel_focus", "text", { mode: "like" })],
    quickCreate: { registryKey: "segment", label: L("Yeni Segment", "New Segment"), showSaveAndOpen: true },
    quickEdit: { registryKey: "segment_edit", label: L("Hizli Duzenle", "Quick Edit") },
    sortOptions: ["modified desc", "segment_name asc"],
    defaultSort: "modified desc",
    numberFields: ["estimated_customer_count"],
    dateTimeFields: ["modified"],
  },
  campaigns: {
    key: "campaigns",
    routeSegment: "campaigns",
    doctype: "AT Campaign",
    labels: { list: L("Kampanyalar", "Campaigns"), detail: L("Kampanya Detay", "Campaign Detail"), section: L("Iletisim ve Takip", "Communication & Follow-up") },
    subtitle: L("Segment bazli kampanya akisini yonetin", "Manage segment-based campaign flow"),
    titleField: "campaign_name",
    statusField: "status",
    listFields: ["name", "campaign_name", "segment", "template", "channel", "office_branch", "status", "scheduled_for", "sent_count", "matched_customer_count", "skipped_count", "last_run_on", "modified"],
    searchFields: ["name", "campaign_name", "segment", "template", "channel", "status", "last_run_summary", "notes"],
    primaryFields: ["campaign_name", "segment"],
    detailFields: ["channel", "status", "scheduled_for"],
    metricFields: ["sent_count", "matched_customer_count", "skipped_count", "last_run_on"],
    summaryFields: ["status", "channel", "segment", "sent_count", "matched_customer_count", "skipped_count", "last_run_on"],
    detailGroups: [{ key: "campaign", fields: ["campaign_name", "segment", "template", "channel", "office_branch", "status", "scheduled_for", "sent_count", "matched_customer_count", "skipped_count", "last_run_on", "owner", "modified"] }],
    textFields: ["last_run_summary", "notes"],
    filterDefs: [F("status", "status", "text", { mode: "like" }), F("channel", "channel", "text", { mode: "like" }), F("segment", "segment", "text", { mode: "like" })],
    quickCreate: { registryKey: "campaign", label: L("Yeni Kampanya", "New Campaign"), showSaveAndOpen: true },
    quickEdit: { registryKey: "campaign_edit", label: L("Hizli Duzenle", "Quick Edit") },
    sortOptions: ["scheduled_for desc", "modified desc", "campaign_name asc"],
    defaultSort: "scheduled_for desc",
    numberFields: ["sent_count", "matched_customer_count", "skipped_count"],
    dateTimeFields: ["scheduled_for", "last_run_on", "modified"],
  },
  "notification-drafts": {
    key: "notification-drafts",
    routeSegment: "notification-drafts",
    doctype: "AT Notification Draft",
    labels: { list: L("Bildirim Taslaklari", "Notification Drafts"), detail: L("Taslak Detay", "Draft Detail"), section: L("Iletisim ve Takip", "Communication & Follow-up") },
    subtitle: L("Taslak bildirim kayitlari", "Draft notification records"),
    titleField: "event_key",
    statusField: "status",
    statusType: "notification_status",
    secondaryStatusField: "channel",
    secondaryStatusType: "notification_channel",
    listFields: ["name", "event_key", "channel", "customer", "recipient", "reference_doctype", "reference_name", "template", "status", "sent_at", "modified"],
    searchFields: ["name", "event_key", "customer", "recipient", "reference_name", "subject"],
    primaryFields: ["name", "customer"],
    detailFields: ["recipient", "reference_doctype", "reference_name"],
    metricFields: ["template", "sent_at"],
    summaryFields: ["status", "channel", "customer", "recipient"],
    detailGroups: [{ key: "draft", fields: ["template", "event_key", "language", "subject", "outbox_record", "sent_at", "owner", "modified"] }],
    textFields: ["body", "error_message"],
    filterDefs: [F("status", "status", "select", { options: ["", "Draft", "Queued", "Sent", "Failed"] }), F("channel", "channel", "select", { options: ["", "SMS", "Email"] }), F("customer", "customer", "text", { mode: "like" })],
    presetDefs: [
      P("queued", L("Kuyrukta", "Queued"), { status: "Queued" }),
      P("failed", L("Basarisiz", "Failed"), { status: "Failed", sort: "modified desc" }),
      P("sms", L("SMS Taslaklari", "SMS Drafts"), { channel: "SMS" }),
      P("email", L("E-posta Taslaklari", "Email Drafts"), { channel: "Email" }),
    ],
    quickCreate: { registryKey: "notification_draft", label: L("Yeni Taslak", "New Draft"), showSaveAndOpen: true },
    rowQuickActions: { sendDraftNow: true },
    sortOptions: ["modified desc", "sent_at desc", "event_key asc"],
    defaultSort: "modified desc",
    panelRef: { doctypeField: "reference_doctype", nameField: "reference_name" },
    dateTimeFields: ["sent_at", "modified"],
  },
  "notification-outbox": {
    key: "notification-outbox",
    routeSegment: "notification-outbox",
    doctype: "AT Notification Outbox",
    labels: { list: L("Giden Bildirimler", "Notification Outbox"), detail: L("Giden Bildirim Detay", "Outbox Detail"), section: L("Iletisim ve Takip", "Communication & Follow-up") },
    subtitle: L("Outbox kuyrugu ve gonderim kayitlari", "Outbox queue and delivery records"),
    titleField: "event_key",
    statusField: "status",
    statusType: "notification_status",
    secondaryStatusField: "channel",
    secondaryStatusType: "notification_channel",
    listFields: ["name", "event_key", "channel", "customer", "recipient", "reference_doctype", "reference_name", "provider", "status", "attempt_count", "next_retry_on", "modified"],
    searchFields: ["name", "event_key", "customer", "recipient", "reference_name", "provider_message_id"],
    primaryFields: ["name", "customer"],
    detailFields: ["recipient", "provider", "reference_name"],
    metricFields: ["attempt_count", "next_retry_on"],
    summaryFields: ["status", "channel", "provider", "attempt_count"],
    detailGroups: [{ key: "delivery", fields: ["draft", "priority", "provider", "max_attempts", "attempt_count", "next_retry_on", "last_attempt_on", "provider_message_id"] }, { key: "reference", fields: ["reference_doctype", "reference_name", "customer", "owner", "modified"] }],
    textFields: ["error_message", "response_log"],
    filterDefs: [F("status", "status", "select", { options: ["", "Queued", "Processing", "Sent", "Failed", "Dead"] }), F("channel", "channel", "select", { options: ["", "SMS", "Email"] }), F("customer", "customer", "text", { mode: "like" })],
    presetDefs: [
      P("queued", L("Kuyrukta", "Queued"), { status: "Queued", sort: "next_retry_on asc" }),
      P("failed", L("Hata Alanlar", "Failed"), { status: "Failed", sort: "modified desc" }),
      P("dead", L("Kalici Hata", "Dead"), { status: "Dead", sort: "modified desc" }),
      P("sms", L("SMS Gonderimleri", "SMS Outbox"), { channel: "SMS" }),
      P("email", L("E-posta Gonderimleri", "Email Outbox"), { channel: "Email" }),
    ],
    toolbarActions: [
      {
        key: "open_communication_center",
        type: "route",
        routeName: "communication-center",
        label: L("Iletisim Merkezi", "Communication Center"),
        variant: "secondary",
        size: "sm",
      },
    ],
    rowQuickActions: { retry: true, requeue: true },
    sortOptions: ["modified desc", "next_retry_on asc", "attempt_count desc"],
    defaultSort: "modified desc",
    panelRef: { doctypeField: "reference_doctype", nameField: "reference_name" },
    dateTimeFields: ["next_retry_on", "last_attempt_on", "modified"],
    numberFields: ["attempt_count", "max_attempts"],
  },
  companies: {
    key: "companies",
    routeSegment: "insurance-companies",
    doctype: "AT Insurance Company",
    labels: { list: L("Sigorta Sirketleri", "Insurance Companies"), detail: L("Sirket Detay", "Company Detail"), section: L("Ana Veriler", "Master Data") },
    subtitle: L("Sigorta sirketi ana veri kayitlari", "Insurance company master records"),
    titleField: "company_name",
    statusField: "is_active",
    statusType: "boolean_active",
    listFields: ["name", "company_name", "company_code", "is_active", "modified", "owner"],
    searchFields: ["name", "company_name", "company_code"],
    primaryFields: ["name", "company_code"],
    detailFields: ["owner", "modified"],
    metricFields: [],
    summaryFields: ["company_name", "company_code", "is_active", "modified"],
    detailGroups: [{ key: "base", fields: ["company_name", "company_code", "is_active", "owner", "modified"] }],
    textFields: [],
    filterDefs: [F("is_active", "is_active", "select", { options: ["", "1", "0"] }), F("company_code", "company_code", "text", { mode: "like" })],
    presetDefs: [
      P("active", L("Aktif Sirketler", "Active Companies"), { is_active: "1" }),
      P("inactive", L("Pasif Sirketler", "Inactive Companies"), { is_active: "0" }),
    ],
    quickCreate: { registryKey: "insurance_company", label: L("Yeni Sirket", "New Company"), showSaveAndOpen: true },
    quickEdit: { registryKey: "insurance_company_edit", label: L("Hizli Duzenle", "Quick Edit") },
    sortOptions: ["company_name asc", "modified desc"],
    defaultSort: "company_name asc",
    boolFields: ["is_active"],
    dateTimeFields: ["modified"],
  },
  branches: {
    key: "branches",
    routeSegment: "branches",
    doctype: "AT Branch",
    labels: { list: L("Branslar", "Branches"), detail: L("Brans Detay", "Branch Detail"), section: L("Ana Veriler", "Master Data") },
    subtitle: L("Brans ve sirket eslesmeleri", "Branch and company mappings"),
    titleField: "branch_name",
    statusField: "is_active",
    statusType: "boolean_active",
    listFields: ["name", "branch_name", "branch_code", "insurance_company", "is_active", "modified", "owner"],
    searchFields: ["name", "branch_name", "branch_code", "insurance_company"],
    primaryFields: ["name", "branch_code"],
    detailFields: ["insurance_company", "modified"],
    metricFields: [],
    summaryFields: ["branch_name", "insurance_company", "is_active", "branch_code"],
    detailGroups: [{ key: "base", fields: ["branch_name", "branch_code", "insurance_company", "is_active", "owner", "modified"] }],
    textFields: [],
    filterDefs: [F("is_active", "is_active", "select", { options: ["", "1", "0"] }), F("insurance_company", "insurance_company", "text", { mode: "like" })],
    presetDefs: [
      P("active", L("Aktif Branslar", "Active Branches"), { is_active: "1" }),
      P("inactive", L("Pasif Branslar", "Inactive Branches"), { is_active: "0" }),
    ],
    quickCreate: { registryKey: "branch_master", label: L("Yeni Brans", "New Branch"), showSaveAndOpen: true },
    quickEdit: { registryKey: "branch_master_edit", label: L("Hizli Duzenle", "Quick Edit") },
    sortOptions: ["branch_name asc", "modified desc"],
    defaultSort: "branch_name asc",
    boolFields: ["is_active"],
    dateTimeFields: ["modified"],
  },
  "sales-entities": {
    key: "sales-entities",
    routeSegment: "sales-entities",
    doctype: "AT Sales Entity",
    labels: { list: L("Satis Birimleri", "Sales Entities"), detail: L("Satis Birimi Detay", "Sales Entity Detail"), section: L("Ana Veriler", "Master Data") },
    subtitle: L("Satis orgutu kayitlari", "Sales organization records"),
    titleField: "full_name",
    statusField: "entity_type",
    listFields: ["name", "full_name", "entity_type", "parent_entity", "modified", "owner"],
    searchFields: ["name", "full_name", "entity_type", "parent_entity"],
    primaryFields: ["name"],
    detailFields: ["parent_entity", "modified"],
    metricFields: [],
    summaryFields: ["full_name", "entity_type", "parent_entity", "modified"],
    detailGroups: [{ key: "base", fields: ["entity_type", "full_name", "parent_entity", "owner", "modified"] }],
    textFields: [],
    filterDefs: [F("entity_type", "entity_type", "text", { mode: "like" }), F("parent_entity", "parent_entity", "text", { mode: "like" })],
    quickCreate: { registryKey: "sales_entity_master", label: L("Yeni Satis Birimi", "New Sales Entity"), showSaveAndOpen: true },
    quickEdit: { registryKey: "sales_entity_master_edit", label: L("Hizli Duzenle", "Quick Edit") },
    sortOptions: ["full_name asc", "modified desc"],
    defaultSort: "full_name asc",
    dateTimeFields: ["modified"],
  },
  templates: {
    key: "templates",
    routeSegment: "notification-templates",
    doctype: "AT Notification Template",
    labels: { list: L("Bildirim Sablonlari", "Notification Templates"), detail: L("Sablon Detay", "Template Detail"), section: L("Ana Veriler", "Master Data") },
    subtitle: L("Bildirim sablonlarini yonetin", "Manage notification templates"),
    titleField: "template_key",
    statusField: "is_active",
    statusType: "boolean_active",
    secondaryStatusField: "channel",
    secondaryStatusType: "notification_channel",
    listFields: ["name", "template_key", "event_key", "channel", "language", "subject", "is_active", "modified", "owner"],
    searchFields: ["name", "template_key", "event_key", "subject", "channel"],
    primaryFields: ["name", "event_key"],
    detailFields: ["subject", "language"],
    metricFields: ["modified"],
    summaryFields: ["template_key", "event_key", "channel", "is_active"],
    detailGroups: [{ key: "base", fields: ["template_key", "event_key", "channel", "language", "subject", "is_active", "owner", "modified"] }],
    textFields: ["body_template"],
    filterDefs: [F("channel", "channel", "select", { options: ["", "SMS", "Email"] }), F("is_active", "is_active", "select", { options: ["", "1", "0"] })],
    presetDefs: [
      P("active", L("Aktif Sablonlar", "Active Templates"), { is_active: "1" }),
      P("inactive", L("Pasif Sablonlar", "Inactive Templates"), { is_active: "0" }),
      P("sms", L("SMS Sablonlari", "SMS Templates"), { channel: "SMS" }),
      P("email", L("E-posta Sablonlari", "Email Templates"), { channel: "Email" }),
    ],
    quickCreate: { registryKey: "notification_template_master", label: L("Yeni Sablon", "New Template"), showSaveAndOpen: true },
    quickEdit: { registryKey: "notification_template_master_edit", label: L("Hizli Duzenle", "Quick Edit") },
    sortOptions: ["template_key asc", "modified desc"],
    defaultSort: "template_key asc",
    boolFields: ["is_active"],
    dateTimeFields: ["modified"],
  },
  "accounting-entries": {
    key: "accounting-entries",
    routeSegment: "accounting-entries",
    doctype: "AT Accounting Entry",
    labels: { list: L("Muhasebe Kayitlari", "Accounting Entries"), detail: L("Muhasebe Kaydi Detay", "Accounting Entry Detail"), section: L("Finans ve Kontrol", "Finance & Control") },
    subtitle: L("Muhasebe entegrasyon kayitlari", "Accounting integration records"),
    titleField: "name",
    statusField: "status",
    listFields: ["name", "source_doctype", "source_name", "entry_type", "status", "policy", "customer", "local_amount_try", "difference_try", "needs_reconciliation", "modified"],
    searchFields: ["name", "source_doctype", "source_name", "policy", "customer", "external_ref"],
    primaryFields: ["source_doctype", "source_name"],
    detailFields: ["policy", "customer"],
    metricFields: ["local_amount_try", "difference_try"],
    summaryFields: ["status", "entry_type", "local_amount_try", "difference_try"],
    detailGroups: [{ key: "base", fields: ["source_doctype", "source_name", "entry_type", "status", "policy", "customer", "insurance_company", "currency", "local_amount", "local_amount_try", "external_amount", "external_amount_try", "difference_try", "needs_reconciliation", "external_ref", "last_synced_on", "sync_attempt_count", "owner", "modified"] }],
    textFields: ["error_message", "payload_json"],
    filterDefs: [F("status", "status", "text", { mode: "like" }), F("needs_reconciliation", "needs_reconciliation", "select", { options: ["", "1", "0"] }), F("source_doctype", "source_doctype", "text", { mode: "like" })],
    presetDefs: [
      P("reconNeeded", L("Mutabakat Gereken", "Needs Reconciliation"), { needs_reconciliation: "1", sort: "difference_try desc" }),
      P("policySource", L("Police Kaynakli", "Policy Source"), { source_doctype: "AT Policy" }),
      P("highDifference", L("Yuksek Fark", "High Difference"), { sort: "difference_try desc" }),
    ],
    quickCreate: { registryKey: "accounting_entry", label: L("Yeni Muhasebe Kaydi", "New Accounting Entry"), showSaveAndOpen: true },
    quickEdit: { registryKey: "accounting_entry_edit", label: L("Hizli Duzenle", "Quick Edit") },
    sortOptions: ["modified desc", "difference_try desc", "local_amount_try desc"],
    defaultSort: "modified desc",
    panelRef: { doctypeField: "source_doctype", nameField: "source_name" },
    currencyFields: ["local_amount_try", "external_amount_try", "difference_try"],
    numberFields: ["local_amount", "external_amount", "sync_attempt_count"],
    boolFields: ["needs_reconciliation"],
    dateTimeFields: ["last_synced_on", "modified"],
  },
  "reconciliation-items": {
    key: "reconciliation-items",
    routeSegment: "reconciliation-items",
    doctype: "AT Reconciliation Item",
    labels: { list: L("Mutabakat Kalemleri", "Reconciliation Items"), detail: L("Mutabakat Kalemi Detay", "Reconciliation Item Detail"), section: L("Finans ve Kontrol", "Finance & Control") },
    subtitle: L("Mutabakat fark ve cozum kayitlari", "Reconciliation mismatch and resolution records"),
    titleField: "name",
    statusField: "status",
    statusType: "reconciliation",
    listFields: ["name", "accounting_entry", "source_doctype", "source_name", "status", "mismatch_type", "difference_try", "resolution_action", "resolved_on", "modified"],
    searchFields: ["name", "accounting_entry", "source_doctype", "source_name", "mismatch_type", "unique_key"],
    primaryFields: ["accounting_entry", "source_name"],
    detailFields: ["source_doctype", "mismatch_type"],
    metricFields: ["difference_try", "resolved_on"],
    summaryFields: ["status", "mismatch_type", "difference_try", "resolution_action"],
    detailGroups: [{ key: "base", fields: ["accounting_entry", "source_doctype", "source_name", "status", "mismatch_type", "local_amount_try", "external_amount_try", "difference_try", "resolution_action", "resolved_by", "resolved_on", "unique_key", "owner", "modified"] }],
    textFields: ["notes", "details_json"],
    filterDefs: [F("status", "status", "select", { options: ["", "Open", "Resolved", "Ignored"] }), F("mismatch_type", "mismatch_type", "text", { mode: "like" }), F("source_doctype", "source_doctype", "text", { mode: "like" })],
    presetDefs: [
      P("open", L("Acik Kalemler", "Open Items"), { status: "Open", sort: "difference_try desc" }),
      P("resolved", L("Cozulenler", "Resolved"), { status: "Resolved", sort: "resolved_on desc" }),
      P("ignored", L("Yoksayilanlar", "Ignored"), { status: "Ignored", sort: "modified desc" }),
      P("highDifference", L("Yuksek Fark", "High Difference"), { sort: "difference_try desc" }),
    ],
    quickCreate: { registryKey: "reconciliation_item", label: L("Yeni Mutabakat Kalemi", "New Reconciliation Item"), showSaveAndOpen: true },
    quickEdit: { registryKey: "reconciliation_item_edit", label: L("Hizli Duzenle", "Quick Edit") },
    sortOptions: ["modified desc", "difference_try desc", "resolved_on desc"],
    defaultSort: "modified desc",
    panelRef: { doctypeField: "source_doctype", nameField: "source_name" },
    currencyFields: ["local_amount_try", "external_amount_try", "difference_try"],
    dateTimeFields: ["resolved_on", "modified"],
  },
  "customer-relations": {
    key: "customer-relations",
    routeSegment: "customer-relations",
    doctype: "AT Customer Relation",
    labels: { list: L("Musteri Iliskileri", "Customer Relations"), detail: L("Iliski Detay", "Relation Detail"), section: L("Musteri 360", "Customer 360") },
    subtitle: L("Musteriler arasi iliski kayitlarini yonetin", "Manage customer relationship records"),
    titleField: "related_customer",
    listFields: ["name", "customer", "related_customer", "relation_type", "is_household", "modified", "owner"],
    searchFields: ["name", "customer", "related_customer", "relation_type", "notes"],
    primaryFields: ["customer", "related_customer"],
    detailFields: ["relation_type", "is_household"],
    metricFields: ["modified"],
    summaryFields: ["relation_type", "is_household", "modified"],
    detailGroups: [{ key: "base", fields: ["customer", "related_customer", "relation_type", "is_household", "owner", "modified"] }],
    textFields: ["notes"],
    filterDefs: [F("customer", "customer", "text", { mode: "like" }), F("related_customer", "related_customer", "text", { mode: "like" }), F("relation_type", "relation_type", "text", { mode: "like" })],
    quickCreate: { registryKey: "customer_relation", label: L("Yeni Iliski", "New Relation"), showSaveAndOpen: true },
    sortOptions: ["modified desc", "customer asc", "related_customer asc"],
    defaultSort: "modified desc",
    boolFields: ["is_household"],
    dateTimeFields: ["modified"],
  },
  "insured-assets": {
    key: "insured-assets",
    routeSegment: "insured-assets",
    doctype: "AT Insured Asset",
    labels: { list: L("Sigortalanan Varliklar", "Insured Assets"), detail: L("Varlik Detay", "Asset Detail"), section: L("Musteri 360", "Customer 360") },
    subtitle: L("Musteriye bagli sigortalanan varlik kayitlari", "Customer-linked insured asset records"),
    titleField: "asset_label",
    listFields: ["name", "customer", "policy", "asset_type", "asset_label", "asset_identifier", "modified", "owner"],
    searchFields: ["name", "customer", "policy", "asset_type", "asset_label", "asset_identifier", "notes"],
    primaryFields: ["asset_label", "customer"],
    detailFields: ["asset_type", "asset_identifier"],
    metricFields: ["policy", "modified"],
    summaryFields: ["asset_type", "policy", "asset_identifier"],
    detailGroups: [{ key: "base", fields: ["customer", "policy", "asset_type", "asset_label", "asset_identifier", "owner", "modified"] }],
    textFields: ["notes"],
    filterDefs: [F("customer", "customer", "text", { mode: "like" }), F("policy", "policy", "text", { mode: "like" }), F("asset_type", "asset_type", "text", { mode: "like" })],
    quickCreate: { registryKey: "insured_asset", label: L("Yeni Varlik", "New Asset"), showSaveAndOpen: true },
    sortOptions: ["modified desc", "asset_label asc", "customer asc"],
    defaultSort: "modified desc",
    dateTimeFields: ["modified"],
  },
  files: {
    key: "files",
    routeSegment: "files",
    doctype: "File",
    labels: { list: L("Dosyalar", "Files"), detail: L("Dosya Detay", "File Detail"), section: L("Dokuman Merkezi", "Document Center") },
    subtitle: L("Yuklenen dosya ve belge kayitlari", "Uploaded file and document records"),
    titleField: "file_name",
    listFields: ["name", "file_name", "attached_to_doctype", "attached_to_name", "file_type", "file_size", "is_private", "creation", "modified"],
    searchFields: ["name", "file_name", "attached_to_doctype", "attached_to_name", "file_url"],
    primaryFields: ["file_name", "attached_to_name"],
    detailFields: ["attached_to_doctype", "attached_to_name", "file_type"],
    metricFields: ["file_size", "creation"],
    summaryFields: ["attached_to_doctype", "attached_to_name", "is_private", "creation"],
    detailGroups: [{ key: "file", fields: ["file_name", "attached_to_doctype", "attached_to_name", "file_type", "file_size", "is_private", "file_url", "creation", "owner", "modified"] }],
    textFields: ["file_url"],
    filterDefs: [F("attached_to_doctype", "attached_to_doctype", "select", { options: ["", "AT Customer", "AT Policy", "AT Claim", "AT Campaign", "AT Notification Draft", "AT Notification Outbox"] }), F("attached_to_name", "attached_to_name", "text", { mode: "like" })],
    presetDefs: [
      P("customers", L("Musteri Dosyalari", "Customer Files"), { attached_to_doctype: "AT Customer", sort: "creation desc" }),
      P("policies", L("Police Dosyalari", "Policy Files"), { attached_to_doctype: "AT Policy", sort: "creation desc" }),
      P("claims", L("Hasar Dosyalari", "Claim Files"), { attached_to_doctype: "AT Claim", sort: "creation desc" }),
    ],
    sortOptions: ["creation desc", "modified desc", "file_name asc"],
    defaultSort: "creation desc",
    boolFields: ["is_private"],
    numberFields: ["file_size"],
    dateTimeFields: ["creation", "modified"],
    panelRef: { doctypeField: "attached_to_doctype", nameField: "attached_to_name" },
  },
  "customer-segment-snapshots": {
    key: "customer-segment-snapshots",
    routeSegment: "customer-segment-snapshots",
    doctype: "AT Customer Segment Snapshot",
    labels: { list: L("Musteri Segment Snapshotlari", "Customer Segment Snapshots"), detail: L("Snapshot Detay", "Snapshot Detail"), section: L("Musteri 360", "Customer 360") },
    subtitle: L("Gunluk segment ve skor snapshot kayitlari", "Daily segment and score snapshot records"),
    titleField: "customer",
    statusField: "segment",
    listFields: ["name", "customer", "office_branch", "snapshot_date", "segment", "value_band", "claim_risk", "score", "source_version", "strengths_json", "risks_json", "score_reason_json", "modified", "owner"],
    searchFields: ["name", "customer", "office_branch", "segment", "value_band", "claim_risk", "source_version"],
    primaryFields: ["customer", "snapshot_date"],
    detailFields: ["value_band", "claim_risk", "strengths_json"],
    metricFields: ["score", "snapshot_date", "risks_json", "score_reason_json"],
    summaryFields: ["segment", "value_band", "claim_risk", "score", "source_version", "strengths_json", "risks_json"],
    detailGroups: [{ key: "base", fields: ["customer", "office_branch", "snapshot_date", "segment", "value_band", "claim_risk", "score", "source_version", "owner", "modified"] }],
    textFields: ["strengths_json", "risks_json", "score_reason_json"],
    filterDefs: [F("customer", "customer", "text", { mode: "like" }), F("segment", "segment", "text", { mode: "like" }), F("office_branch", "office_branch", "text", { mode: "like" })],
    sortOptions: ["snapshot_date desc", "modified desc", "customer asc"],
    defaultSort: "snapshot_date desc",
    numberFields: ["score"],
    dateFields: ["snapshot_date"],
    dateTimeFields: ["modified"],
  },
  "access-logs": {
    key: "access-logs",
    routeSegment: "access-logs",
    doctype: "AT Access Log",
    labels: { list: L("Erisim ve Audit Kayitlari", "Access & Audit Logs"), detail: L("Audit Kaydi", "Audit Log"), section: L("Izlenebilirlik", "Observability") },
    subtitle: L("Kritik erisim ve mutasyon izlerini inceleyin", "Inspect critical access and mutation traces"),
    titleField: "reference_name",
    statusField: "action",
    listFields: ["name", "reference_doctype", "reference_name", "viewed_by", "action", "action_summary", "decision_context", "ip_address", "viewed_on"],
    searchFields: ["name", "reference_doctype", "reference_name", "viewed_by", "action", "action_summary", "decision_context", "ip_address"],
    primaryFields: ["reference_doctype", "reference_name"],
    detailFields: ["viewed_by", "action", "viewed_on"],
    metricFields: ["action", "viewed_on"],
    summaryFields: ["action", "viewed_by", "action_summary", "decision_context", "viewed_on"],
    detailGroups: [{ key: "audit", fields: ["reference_doctype", "reference_name", "viewed_by", "action", "viewed_on", "ip_address"] }],
    textFields: ["action_summary", "decision_context"],
    filterDefs: [
      F("reference_doctype", "reference_doctype", "text", { mode: "like" }),
      F("action", "action", "select", { options: ["", "View", "Create", "Edit", "Delete", "Run", "Export"] }),
      F("viewed_by", "viewed_by", "text", { mode: "like" }),
    ],
    presetDefs: [
      P("create", L("Olusturma Izleri", "Create Events"), { action: "Create", sort: "viewed_on desc" }),
      P("edit", L("Duzenleme Izleri", "Edit Events"), { action: "Edit", sort: "viewed_on desc" }),
      P("delete", L("Silme Izleri", "Delete Events"), { action: "Delete", sort: "viewed_on desc" }),
      P("run", L("Calistirma Izleri", "Run Events"), { action: "Run", sort: "viewed_on desc" }),
      P("recent", L("Son Kayitlar", "Recent Events"), { sort: "viewed_on desc" }),
    ],
    sortOptions: ["viewed_on desc", "modified desc", "reference_name asc"],
    defaultSort: "viewed_on desc",
    dateTimeFields: ["viewed_on"],
  },
  "ownership-assignments": {
    key: "ownership-assignments",
    routeSegment: "ownership-assignments",
    doctype: "AT Ownership Assignment",
    labels: { list: L("Atamalar", "Ownership Assignments"), detail: L("Atama Detay", "Assignment Detail"), section: L("Operasyon", "Operations") },
    subtitle: L("Kayit sahipligi ve operasyon atamalarini yonetin", "Manage record ownership and operational assignments"),
    titleField: "assigned_to",
    statusField: "status",
    listFields: ["name", "source_doctype", "source_name", "customer", "policy", "assigned_to", "assignment_role", "status", "priority", "due_date", "modified"],
    searchFields: ["name", "source_doctype", "source_name", "customer", "policy", "assigned_to", "notes"],
    primaryFields: ["assigned_to", "source_name"],
    detailFields: ["assignment_role", "priority", "due_date"],
    metricFields: ["status", "modified"],
    summaryFields: ["status", "assignment_role", "priority", "due_date"],
    detailGroups: [{ key: "assignment", fields: ["source_doctype", "source_name", "customer", "policy", "office_branch", "assigned_to", "assignment_role", "status", "priority", "due_date", "owner", "modified"] }],
    textFields: ["notes"],
    filterDefs: [F("status", "status", "text", { mode: "like" }), F("assigned_to", "assigned_to", "text", { mode: "like" }), F("source_name", "source_name", "text", { mode: "like" })],
    quickCreate: { registryKey: "ownership_assignment", label: L("Yeni Atama", "New Assignment"), showSaveAndOpen: true },
    quickEdit: { registryKey: "ownership_assignment_edit", label: L("Hizli Duzenle", "Quick Edit") },
    sortOptions: ["due_date asc", "modified desc"],
    defaultSort: "due_date asc",
    dateFields: ["due_date"],
    dateTimeFields: ["modified"],
  },
  tasks: {
    key: "tasks",
    routeSegment: "tasks",
    doctype: "AT Task",
    labels: { list: L("Gorevler", "Tasks"), detail: L("Gorev Detay", "Task Detail"), section: L("Operasyon", "Operations") },
    subtitle: L("Takim gorevlerini ve takip kayitlarini yonetin", "Manage team tasks and follow-up records"),
    titleField: "task_title",
    statusField: "status",
    listFields: ["name", "task_title", "task_type", "source_doctype", "source_name", "customer", "assigned_to", "status", "priority", "due_date", "modified"],
    searchFields: ["name", "task_title", "source_name", "customer", "policy", "claim", "assigned_to", "notes"],
    primaryFields: ["task_title", "assigned_to"],
    detailFields: ["task_type", "priority", "due_date", "reminder_at"],
    metricFields: ["status", "modified"],
    summaryFields: ["status", "task_type", "priority", "due_date"],
    detailGroups: [{ key: "task", fields: ["source_doctype", "source_name", "customer", "policy", "claim", "office_branch", "assigned_to", "task_type", "status", "priority", "due_date", "reminder_at", "completed_on", "owner", "modified"] }],
    textFields: ["notes"],
    filterDefs: [F("status", "status", "text", { mode: "like" }), F("assigned_to", "assigned_to", "text", { mode: "like" }), F("task_type", "task_type", "text", { mode: "like" })],
    quickCreate: { registryKey: "task", label: L("Yeni Gorev", "New Task"), showSaveAndOpen: true },
    quickEdit: { registryKey: "task_edit", label: L("Hizli Duzenle", "Quick Edit") },
    sortOptions: ["due_date asc", "modified desc"],
    defaultSort: "due_date asc",
    dateFields: ["due_date"],
    dateTimeFields: ["reminder_at", "completed_on", "modified"],
  },
  activities: {
    key: "activities",
    routeSegment: "activities",
    doctype: "AT Activity",
    labels: { list: L("Aktiviteler", "Activities"), detail: L("Aktivite Detay", "Activity Detail"), section: L("Operasyon", "Operations") },
    subtitle: L("Gerceklesen operasyon adimlarini ve notlari yonetin", "Manage completed operational steps and notes"),
    titleField: "activity_title",
    statusField: "status",
    listFields: ["name", "activity_title", "activity_type", "source_doctype", "source_name", "customer", "assigned_to", "status", "activity_at", "modified"],
    searchFields: ["name", "activity_title", "source_name", "customer", "policy", "claim", "assigned_to", "notes"],
    primaryFields: ["activity_title", "assigned_to"],
    detailFields: ["activity_type", "activity_at", "source_name"],
    metricFields: ["status", "modified"],
    summaryFields: ["status", "activity_type", "activity_at"],
    detailGroups: [{ key: "activity", fields: ["source_doctype", "source_name", "customer", "policy", "claim", "office_branch", "assigned_to", "activity_type", "status", "activity_at", "owner", "modified"] }],
    textFields: ["notes"],
    filterDefs: [F("status", "status", "text", { mode: "like" }), F("assigned_to", "assigned_to", "text", { mode: "like" }), F("activity_type", "activity_type", "text", { mode: "like" })],
    quickCreate: { registryKey: "activity", label: L("Yeni Aktivite", "New Activity"), showSaveAndOpen: true },
    quickEdit: { registryKey: "activity_edit", label: L("Hizli Duzenle", "Quick Edit") },
    sortOptions: ["activity_at desc", "modified desc"],
    defaultSort: "activity_at desc",
    dateTimeFields: ["activity_at", "modified"],
  },
};

export function getAuxWorkbenchConfig(key) {
  return AUX_WORKBENCH_CONFIGS[key] || null;
}

export const AUX_WORKBENCH_ROUTE_DEFS = Object.values(AUX_WORKBENCH_CONFIGS).map((cfg) => ({
  key: cfg.key,
  listPath: `/${cfg.routeSegment}`,
  detailPath: `/${cfg.routeSegment}/:name`,
  listName: `${cfg.key}-list`,
  detailName: `${cfg.key}-detail`,
  meta: { title: cfg.labels.list, section: cfg.labels.section },
  detailMeta: { title: cfg.labels.detail, section: cfg.labels.section },
}));
