function i18nLabel(tr, en) {
  return { tr, en };
}

function option(value, tr, en) {
  return { value, label: i18nLabel(tr, en) };
}

export const quickCreateRegistry = {
  offer: {
    key: "offer",
    title: i18nLabel("Detayli Hizli Teklif", "Detailed Quick Offer"),
    subtitle: i18nLabel("Musteri, urun ve finans alanlariyla taslak teklif olustur", "Create a draft offer with customer, product and financial fields"),
    submitUrl: "acentem_takipte.acentem_takipte.doctype.at_offer.at_offer.create_quick_offer",
    resultKey: "offer",
    openRouteName: "offer-detail",
    successRefreshTargets: ["offer_list", "offer_board"],
    defaults: {
      branch: "",
      insurance_company: "",
      sales_entity: "",
      offer_date: "",
      valid_until: "",
      currency: "TRY",
      status: "Draft",
      gross_premium: "",
      net_premium: "",
      tax_amount: "0",
      commission_amount: "0",
      notes: "",
    },
    fields: [
      { name: "sales_entity", type: "select", label: i18nLabel("Satis Birimi", "Sales Entity"), optionsSource: "salesEntities", fullWidth: false },
      { name: "insurance_company", type: "select", label: i18nLabel("Sigorta Sirketi", "Insurance Company"), optionsSource: "insuranceCompanies", fullWidth: false },
      { name: "branch", type: "select", label: i18nLabel("Sigorta Bransi", "Insurance Branch"), optionsSource: "branches", fullWidth: false },
      { name: "status", type: "select", label: i18nLabel("Durum", "Status"), options: [
        option("Draft", "Taslak", "Draft"),
        option("Sent", "Musteriye Gonderildi", "Sent"),
        option("Accepted", "Kabul Edildi", "Accepted"),
        option("Rejected", "Reddedildi", "Rejected"),
      ], fullWidth: false },
      { name: "offer_date", type: "date", label: i18nLabel("Teklif Tarihi", "Offer Date"), fullWidth: false },
      { name: "valid_until", type: "date", label: i18nLabel("Gecerlilik Tarihi", "Valid Until"), fullWidth: false },
      { name: "currency", type: "select", label: i18nLabel("Doviz", "Currency"), options: [option("TRY", "TRY", "TRY"), option("USD", "USD", "USD"), option("EUR", "EUR", "EUR")], fullWidth: false },
      { name: "gross_premium", type: "number", label: i18nLabel("Brut Prim", "Gross Premium"), min: 0, step: "0.01", fullWidth: false },
      { name: "net_premium", type: "number", label: i18nLabel("Net Prim", "Net Premium"), min: 0, step: "0.01", fullWidth: false },
      { name: "tax_amount", type: "number", label: i18nLabel("Vergi Tutari", "Tax Amount"), min: 0, step: "0.01", fullWidth: false },
      { name: "commission_amount", type: "number", label: i18nLabel("Komisyon Tutari", "Commission Amount"), min: 0, step: "0.01", fullWidth: false },
      { name: "notes", type: "textarea", label: i18nLabel("Aciklama / Not", "Notes"), rows: 3, fullWidth: true },
    ],
  },
  policy: {
    key: "policy",
    title: i18nLabel("Hizli Police Kaydi", "Quick Policy Entry"),
    subtitle: i18nLabel("Temel police alanlariyla kayit olustur", "Create a policy with core fields"),
    submitUrl: "acentem_takipte.api.quick_create.create_quick_policy",
    resultKey: "policy",
    openRouteName: "policy-detail",
    successRefreshTargets: ["policy_list"],
    defaults: {
      customer: "",
      sales_entity: "",
      insurance_company: "",
      branch: "",
      policy_no: "",
      source_offer: "",
      status: "Active",
      issue_date: "",
      start_date: "",
      end_date: "",
      currency: "TRY",
      gross_premium: "",
      net_premium: "",
      tax_amount: "0",
      commission_amount: "0",
      notes: "",
    },
    fields: [
      { name: "customer", type: "select", label: i18nLabel("Musteri", "Customer"), optionsSource: "customers", required: true },
      { name: "sales_entity", type: "select", label: i18nLabel("Satis Birimi", "Sales Entity"), optionsSource: "salesEntities", required: true },
      { name: "insurance_company", type: "select", label: i18nLabel("Sigorta Sirketi", "Insurance Company"), optionsSource: "insuranceCompanies", required: true },
      { name: "branch", type: "select", label: i18nLabel("Sigorta Bransi", "Insurance Branch"), optionsSource: "branches", required: true },
      { name: "policy_no", type: "text", label: i18nLabel("Police No", "Policy Number") },
      { name: "source_offer", type: "select", label: i18nLabel("Kaynak Teklif", "Source Offer"), optionsSource: "offers" },
      { name: "status", type: "select", label: i18nLabel("Durum", "Status"), options: [
        option("Active", "Aktif", "Active"),
        option("KYT", "KYT", "KYT"),
        option("IPT", "IPT", "IPT"),
      ] },
      { name: "issue_date", type: "date", label: i18nLabel("Tanzim Tarihi", "Issue Date") },
      { name: "start_date", type: "date", label: i18nLabel("Baslangic", "Start Date") },
      { name: "end_date", type: "date", label: i18nLabel("Bitis", "End Date") },
      { name: "currency", type: "select", label: i18nLabel("Doviz", "Currency"), options: [option("TRY", "TRY", "TRY"), option("USD", "USD", "USD"), option("EUR", "EUR", "EUR")] },
      { name: "gross_premium", type: "number", label: i18nLabel("Brut Prim", "Gross Premium"), required: true, min: 0, step: "0.01" },
      { name: "net_premium", type: "number", label: i18nLabel("Net Prim", "Net Premium"), min: 0, step: "0.01" },
      { name: "tax_amount", type: "number", label: i18nLabel("Vergi Tutari", "Tax Amount"), min: 0, step: "0.01" },
      { name: "commission_amount", type: "number", label: i18nLabel("Komisyon Tutari", "Commission Amount"), min: 0, step: "0.01" },
      { name: "notes", type: "textarea", label: i18nLabel("Not", "Notes"), rows: 3, fullWidth: true },
    ],
  },
  lead: {
    key: "lead",
    title: i18nLabel("Hizli Lead Olustur", "Quick Lead"),
    subtitle: i18nLabel("Temel satis ve potansiyel bilgileriyle lead olustur", "Create a lead with sales and potential details"),
    submitUrl: "acentem_takipte.api.quick_create.create_quick_lead",
    resultKey: "lead",
    openRouteName: "lead-detail",
    successRefreshTargets: ["lead_list"],
    defaults: {
      first_name: "",
      last_name: "",
      phone: "",
      tax_id: "",
      email: "",
      status: "Open",
      customer: "",
      sales_entity: "",
      insurance_company: "",
      branch: "",
      estimated_gross_premium: "",
      notes: "",
    },
    fields: [
      { name: "first_name", type: "text", label: i18nLabel("Ad", "First Name"), required: true },
      { name: "last_name", type: "text", label: i18nLabel("Soyad", "Last Name") },
      { name: "phone", type: "text", label: i18nLabel("Telefon", "Phone") },
      { name: "tax_id", type: "text", label: i18nLabel("TC/VKN", "Tax ID") },
      { name: "email", type: "email", label: i18nLabel("E-posta", "Email") },
      { name: "status", type: "select", label: i18nLabel("Lead Durumu", "Lead Status"), options: [
        option("Draft", "Taslak", "Draft"),
        option("Open", "Acik", "Open"),
        option("Replied", "Gorusuldu", "Replied"),
        option("Closed", "Kapandi", "Closed"),
      ] },
      { name: "customer", type: "select", label: i18nLabel("Musteri (Opsiyonel)", "Customer (Optional)"), optionsSource: "customers" },
      { name: "sales_entity", type: "select", label: i18nLabel("Satis Birimi", "Sales Entity"), optionsSource: "salesEntities" },
      { name: "insurance_company", type: "select", label: i18nLabel("Sigorta Sirketi", "Insurance Company"), optionsSource: "insuranceCompanies" },
      { name: "branch", type: "select", label: i18nLabel("Brans", "Branch"), optionsSource: "branches" },
      { name: "estimated_gross_premium", type: "number", label: i18nLabel("Tahmini Brut Prim", "Estimated Gross Premium"), min: 0, step: "0.01" },
      { name: "notes", type: "textarea", label: i18nLabel("Not", "Notes"), rows: 3, fullWidth: true },
    ],
  },
  customer: {
    key: "customer",
    title: i18nLabel("Hizli Musteri Olustur", "Quick Customer"),
    subtitle: i18nLabel("Sigortali bilgileriyle musteri kaydi olustur", "Create a customer with insured profile fields"),
    submitUrl: "acentem_takipte.api.quick_create.create_quick_customer",
    resultKey: "customer",
    openRouteName: "customer-detail",
    successRefreshTargets: ["customer_list"],
    defaults: {
      full_name: "",
      tax_id: "",
      phone: "",
      email: "",
      address: "",
      birth_date: "",
      gender: "Unknown",
      marital_status: "Unknown",
      occupation: "",
      consent_status: "Unknown",
      assigned_agent: "",
    },
    fields: [
      { name: "full_name", type: "text", label: i18nLabel("Ad Soyad", "Full Name"), required: true, fullWidth: true },
      { name: "tax_id", type: "text", label: i18nLabel("TC/VKN", "Tax ID"), required: true },
      { name: "birth_date", type: "date", label: i18nLabel("Dogum Tarihi", "Birth Date") },
      { name: "phone", type: "text", label: i18nLabel("Telefon", "Phone") },
      { name: "email", type: "email", label: i18nLabel("E-posta", "Email") },
      { name: "gender", type: "select", label: i18nLabel("Cinsiyet", "Gender"), options: [
        option("Unknown", "Bilinmiyor", "Unknown"),
        option("Male", "Erkek", "Male"),
        option("Female", "Kadin", "Female"),
        option("Other", "Diger", "Other"),
      ] },
      { name: "marital_status", type: "select", label: i18nLabel("Medeni Durumu", "Marital Status"), options: [
        option("Unknown", "Bilinmiyor", "Unknown"),
        option("Single", "Bekar", "Single"),
        option("Married", "Evli", "Married"),
        option("Divorced", "Bosanmis", "Divorced"),
        option("Widowed", "Dul", "Widowed"),
      ] },
      { name: "consent_status", type: "select", label: i18nLabel("Izin Durumu", "Consent Status"), options: [
        option("Unknown", "Bilinmiyor", "Unknown"),
        option("Granted", "Onayli", "Granted"),
        option("Revoked", "Iptal", "Revoked"),
      ] },
      { name: "assigned_agent", type: "text", label: i18nLabel("Temsilci (User)", "Assigned Agent (User)") },
      { name: "occupation", type: "text", label: i18nLabel("Meslek", "Occupation"), fullWidth: true },
      { name: "address", type: "textarea", label: i18nLabel("Adres", "Address"), rows: 3, fullWidth: true },
    ],
  },
  claim: {
    key: "claim",
    title: i18nLabel("Hizli Hasar Ac", "Quick Claim"),
    subtitle: i18nLabel("Policeye bagli hasar kaydi olustur", "Create a claim linked to a policy"),
    submitUrl: "acentem_takipte.api.quick_create.create_quick_claim",
    resultKey: "claim",
    successRefreshTargets: ["claim_list"],
    defaults: {
      policy: "",
      customer: "",
      claim_no: "",
      claim_type: "Damage",
      claim_status: "Open",
      incident_date: "",
      reported_date: "",
      currency: "TRY",
      estimated_amount: "",
      approved_amount: "",
      notes: "",
    },
    fields: [
      { name: "policy", type: "select", label: i18nLabel("Police", "Policy"), optionsSource: "policies", required: true },
      { name: "customer", type: "select", label: i18nLabel("Musteri", "Customer"), optionsSource: "customers", required: true },
      { name: "claim_no", type: "text", label: i18nLabel("Hasar No", "Claim Number") },
      { name: "claim_type", type: "select", label: i18nLabel("Hasar Turu", "Claim Type"), options: [
        option("Damage", "Hasar", "Damage"),
        option("Health", "Saglik", "Health"),
        option("Theft", "Hirsizlik", "Theft"),
        option("Liability", "Sorumluluk", "Liability"),
        option("Other", "Diger", "Other"),
      ] },
      { name: "claim_status", type: "select", label: i18nLabel("Durum", "Status"), options: [
        option("Draft", "Taslak", "Draft"),
        option("Open", "Acik", "Open"),
        option("Under Review", "Inceleme", "Under Review"),
        option("Approved", "Onaylandi", "Approved"),
        option("Rejected", "Reddedildi", "Rejected"),
      ] },
      { name: "incident_date", type: "date", label: i18nLabel("Hasar Tarihi", "Incident Date"), required: true },
      { name: "reported_date", type: "date", label: i18nLabel("Bildirim Tarihi", "Reported Date"), required: true },
      { name: "currency", type: "select", label: i18nLabel("Doviz", "Currency"), options: [option("TRY", "TRY", "TRY"), option("USD", "USD", "USD"), option("EUR", "EUR", "EUR")] },
      { name: "estimated_amount", type: "number", label: i18nLabel("Talep Tutari", "Estimated Amount"), min: 0, step: "0.01" },
      { name: "approved_amount", type: "number", label: i18nLabel("Onaylanan Tutar", "Approved Amount"), min: 0, step: "0.01" },
      { name: "notes", type: "textarea", label: i18nLabel("Aciklama", "Notes"), rows: 3, fullWidth: true },
    ],
  },
  payment: {
    key: "payment",
    title: i18nLabel("Hizli Odeme/Tahsilat", "Quick Payment"),
    subtitle: i18nLabel("Tahsilat veya odeme hareketi olustur", "Create an inbound or outbound payment record"),
    submitUrl: "acentem_takipte.api.quick_create.create_quick_payment",
    resultKey: "payment",
    successRefreshTargets: ["payment_list"],
    defaults: {
      customer: "",
      policy: "",
      claim: "",
      sales_entity: "",
      payment_direction: "Inbound",
      payment_purpose: "Premium Collection",
      status: "Draft",
      payment_date: "",
      due_date: "",
      currency: "TRY",
      amount: "",
      reference_no: "",
      notes: "",
    },
    fields: [
      { name: "payment_direction", type: "select", label: i18nLabel("Yon", "Direction"), options: [
        option("Inbound", "Tahsilat", "Inbound"),
        option("Outbound", "Odeme", "Outbound"),
      ] },
      { name: "payment_purpose", type: "select", label: i18nLabel("Amac", "Purpose"), options: [
        option("Premium Collection", "Prim Tahsilati", "Premium Collection"),
        option("Commission Payout", "Komisyon Odemesi", "Commission Payout"),
        option("Claim Payout", "Hasar Odemesi", "Claim Payout"),
        option("Other", "Diger", "Other"),
      ] },
      { name: "customer", type: "select", label: i18nLabel("Musteri", "Customer"), optionsSource: "customers", required: true },
      { name: "policy", type: "select", label: i18nLabel("Police", "Policy"), optionsSource: "policies" },
      { name: "claim", type: "select", label: i18nLabel("Hasar", "Claim"), optionsSource: "claims" },
      { name: "sales_entity", type: "select", label: i18nLabel("Satis Birimi", "Sales Entity"), optionsSource: "salesEntities" },
      { name: "status", type: "select", label: i18nLabel("Durum", "Status"), options: [
        option("Draft", "Taslak", "Draft"),
        option("Paid", "Odendi", "Paid"),
        option("Cancelled", "Iptal", "Cancelled"),
      ] },
      { name: "payment_date", type: "date", label: i18nLabel("Tarih", "Payment Date"), required: true },
      { name: "due_date", type: "date", label: i18nLabel("Vade", "Due Date") },
      { name: "currency", type: "select", label: i18nLabel("Doviz", "Currency"), options: [option("TRY", "TRY", "TRY"), option("USD", "USD", "USD"), option("EUR", "EUR", "EUR")] },
      { name: "amount", type: "number", label: i18nLabel("Tutar", "Amount"), required: true, min: 0.01, step: "0.01" },
      { name: "reference_no", type: "text", label: i18nLabel("Dis Referans", "External Reference") },
      { name: "notes", type: "textarea", label: i18nLabel("Aciklama", "Notes"), rows: 3, fullWidth: true },
    ],
  },
  renewal_task: {
    key: "renewal_task",
    title: i18nLabel("Hizli Yenileme Gorevi", "Quick Renewal Task"),
    subtitle: i18nLabel("Policeye bagli yenileme takip gorevi olustur", "Create a policy renewal follow-up task"),
    submitUrl: "acentem_takipte.api.quick_create.create_quick_renewal_task",
    resultKey: "renewal_task",
    openRouteName: "tasks-detail",
    successRefreshTargets: ["renewal_list"],
    defaults: {
      policy: "",
      customer: "",
      renewal_date: "",
      due_date: "",
      status: "Open",
      assigned_to: "",
      notes: "",
      auto_created: false,
    },
    fields: [
      { name: "policy", type: "select", label: i18nLabel("Police", "Policy"), optionsSource: "policies", required: true },
      { name: "customer", type: "select", label: i18nLabel("Musteri", "Customer"), optionsSource: "customers", required: true },
      { name: "renewal_date", type: "date", label: i18nLabel("Yenileme Tarihi", "Renewal Date"), required: true },
      { name: "due_date", type: "date", label: i18nLabel("Son Tarih", "Due Date"), required: true },
      { name: "status", type: "select", label: i18nLabel("Durum", "Status"), options: [
        option("Open", "Acik", "Open"),
        option("In Progress", "Devam Ediyor", "In Progress"),
        option("Done", "Tamamlandi", "Done"),
        option("Cancelled", "Iptal", "Cancelled"),
      ] },
      { name: "assigned_to", type: "text", label: i18nLabel("Atanan Kisi (User)", "Assigned To (User)") },
      { name: "auto_created", type: "checkbox", label: i18nLabel("Otomatik Olusturuldu", "Auto Created") },
      { name: "notes", type: "textarea", label: i18nLabel("Not", "Notes"), rows: 3, fullWidth: true },
    ],
  },
  notification_draft: {
    key: "notification_draft",
    title: i18nLabel("Hizli Bildirim Taslagi", "Quick Notification Draft"),
    subtitle: i18nLabel("Sablon tabanli bildirim taslagi olustur", "Create a template-based notification draft"),
    submitUrl: "acentem_takipte.api.communication.create_quick_notification_draft",
    resultKey: "draft",
    openRouteName: "notification-drafts-detail",
    successRefreshTargets: ["notification_draft_list", "aux_list", "communication_snapshot"],
    defaults: {
      template: "",
      channel: "",
      language: "tr",
      customer: "",
      recipient: "",
      reference_doctype: "",
      reference_name: "",
      subject: "",
      body: "",
      status: "Draft",
    },
    fields: [
      { name: "template", type: "select", label: i18nLabel("Sablon", "Template"), optionsSource: "notificationTemplates", required: true },
      {
        name: "channel",
        type: "select",
        label: i18nLabel("Kanal", "Channel"),
        options: [option("", "Template Kanal", "Template Channel"), option("SMS", "SMS", "SMS"), option("Email", "E-posta", "Email")],
      },
      { name: "language", type: "select", label: i18nLabel("Dil", "Language"), options: [option("tr", "Turkce", "Turkish"), option("en", "Ingilizce", "English")] },
      { name: "customer", type: "select", label: i18nLabel("Musteri", "Customer"), optionsSource: "customers" },
      { name: "recipient", type: "text", label: i18nLabel("Alici", "Recipient"), required: true },
      {
        name: "reference_doctype",
        type: "select",
        label: i18nLabel("Referans Tipi", "Reference Type"),
        options: [
          option("", "Yok", "None"),
          option("AT Lead", "Lead", "Lead"),
          option("AT Offer", "Teklif", "Offer"),
          option("AT Policy", "Police", "Policy"),
          option("AT Customer", "Musteri", "Customer"),
          option("AT Claim", "Hasar", "Claim"),
          option("AT Payment", "Odeme", "Payment"),
          option("AT Renewal Task", "Yenileme Gorevi", "Renewal Task"),
        ],
      },
      { name: "reference_name", type: "text", label: i18nLabel("Referans Kayit", "Reference Record") },
      { name: "status", type: "select", label: i18nLabel("Durum", "Status"), options: [
        option("Draft", "Taslak", "Draft"),
        option("Queued", "Kuyrukta", "Queued"),
      ] },
      { name: "subject", type: "text", label: i18nLabel("Konu", "Subject"), fullWidth: true },
      { name: "body", type: "textarea", label: i18nLabel("Mesaj", "Message"), rows: 4, fullWidth: true },
    ],
  },
  communication_message: {
    key: "communication_message",
    title: i18nLabel("Hizli Iletisim", "Quick Communication"),
    subtitle: i18nLabel("Taslak kaydet veya hemen gonder", "Save as draft or send immediately"),
    submitUrl: "acentem_takipte.api.communication.create_quick_notification_draft",
    resultKey: "draft",
    successRefreshTargets: ["communication_snapshot", "notification_draft_list"],
    defaults: {
      template: "",
      channel: "",
      language: "tr",
      customer: "",
      recipient: "",
      reference_doctype: "",
      reference_name: "",
      subject: "",
      body: "",
    },
    fields: [
      { name: "template", type: "select", label: i18nLabel("Sablon", "Template"), optionsSource: "notificationTemplates", required: true },
      {
        name: "channel",
        type: "select",
        label: i18nLabel("Kanal", "Channel"),
        options: [option("", "Template Kanal", "Template Channel"), option("SMS", "SMS", "SMS"), option("Email", "E-posta", "Email")],
      },
      { name: "language", type: "select", label: i18nLabel("Dil", "Language"), options: [option("tr", "Turkce", "Turkish"), option("en", "Ingilizce", "English")] },
      { name: "customer", type: "select", label: i18nLabel("Musteri", "Customer"), optionsSource: "customers" },
      { name: "recipient", type: "text", label: i18nLabel("Alici", "Recipient"), required: true },
      {
        name: "reference_doctype",
        type: "select",
        label: i18nLabel("Referans Tipi", "Reference Type"),
        options: [
          option("", "Yok", "None"),
          option("AT Lead", "Lead", "Lead"),
          option("AT Offer", "Teklif", "Offer"),
          option("AT Policy", "Police", "Policy"),
          option("AT Customer", "Musteri", "Customer"),
          option("AT Claim", "Hasar", "Claim"),
          option("AT Payment", "Odeme", "Payment"),
          option("AT Renewal Task", "Yenileme Gorevi", "Renewal Task"),
        ],
      },
      { name: "reference_name", type: "text", label: i18nLabel("Referans Kayit", "Reference Record") },
      { name: "subject", type: "text", label: i18nLabel("Konu (E-posta)", "Subject (Email)"), fullWidth: true },
      { name: "body", type: "textarea", label: i18nLabel("Mesaj", "Message"), rows: 4, fullWidth: true },
    ],
  },
  insurance_company: {
    key: "insurance_company",
    title: i18nLabel("Hizli Sigorta Sirketi", "Quick Insurance Company"),
    subtitle: i18nLabel("Ana veri sirket kaydi olustur", "Create an insurance company master record"),
    submitUrl: "acentem_takipte.api.quick_create.create_quick_insurance_company",
    resultKey: "company",
    openRouteName: "companies-detail",
    successRefreshTargets: ["aux_list"],
    defaults: { company_name: "", company_code: "", is_active: true },
    fields: [
      { name: "company_name", type: "text", label: i18nLabel("Sirket Adi", "Company Name"), required: true, fullWidth: true },
      { name: "company_code", type: "text", label: i18nLabel("Sirket Kodu", "Company Code") },
      { name: "is_active", type: "checkbox", label: i18nLabel("Aktif", "Active"), checkboxLabel: i18nLabel("Aktif sirket", "Active company") },
    ],
  },
  branch_master: {
    key: "branch_master",
    title: i18nLabel("Hizli Brans", "Quick Branch"),
    subtitle: i18nLabel("Brans ve sirket eslesmesi olustur", "Create a branch and company mapping"),
    submitUrl: "acentem_takipte.api.quick_create.create_quick_branch",
    resultKey: "branch",
    openRouteName: "branches-detail",
    successRefreshTargets: ["aux_list"],
    defaults: { branch_name: "", branch_code: "", insurance_company: "", is_active: true },
    fields: [
      { name: "branch_name", type: "text", label: i18nLabel("Brans Adi", "Branch Name"), required: true, fullWidth: true },
      { name: "branch_code", type: "text", label: i18nLabel("Brans Kodu", "Branch Code") },
      { name: "insurance_company", type: "select", label: i18nLabel("Sigorta Sirketi", "Insurance Company"), optionsSource: "insuranceCompanies" },
      { name: "is_active", type: "checkbox", label: i18nLabel("Aktif", "Active"), checkboxLabel: i18nLabel("Aktif brans", "Active branch") },
    ],
  },
  sales_entity_master: {
    key: "sales_entity_master",
    title: i18nLabel("Hizli Satis Birimi", "Quick Sales Entity"),
    subtitle: i18nLabel("Satis orgutu kaydi olustur", "Create a sales organization record"),
    submitUrl: "acentem_takipte.api.quick_create.create_quick_sales_entity",
    resultKey: "sales_entity",
    openRouteName: "sales-entities-detail",
    successRefreshTargets: ["aux_list"],
    defaults: { entity_type: "Agency", full_name: "", parent_entity: "" },
    fields: [
      { name: "entity_type", type: "select", label: i18nLabel("Tip", "Entity Type"), required: true, options: [
        option("Agency", "Acente", "Agency"),
        option("Sub-Account", "Alt Hesap", "Sub-Account"),
        option("Representative", "Temsilci", "Representative"),
      ] },
      { name: "full_name", type: "text", label: i18nLabel("Tam Ad", "Full Name"), required: true, fullWidth: true },
      { name: "parent_entity", type: "select", label: i18nLabel("Bagli Birim", "Parent Entity"), optionsSource: "salesEntities" },
    ],
  },
  notification_template_master: {
    key: "notification_template_master",
    title: i18nLabel("Hizli Bildirim Sablonu", "Quick Notification Template"),
    subtitle: i18nLabel("Kanal ve dil bazli sablon olustur", "Create a channel/language template"),
    submitUrl: "acentem_takipte.api.quick_create.create_quick_notification_template",
    resultKey: "template",
    openRouteName: "templates-detail",
    successRefreshTargets: ["aux_list"],
    defaults: { template_key: "", event_key: "", channel: "Both", language: "tr", subject: "", body_template: "", is_active: true },
    fields: [
      { name: "template_key", type: "text", label: i18nLabel("Sablon Anahtari", "Template Key"), required: true },
      { name: "event_key", type: "text", label: i18nLabel("Event Anahtari", "Event Key"), required: true },
      { name: "channel", type: "select", label: i18nLabel("Kanal", "Channel"), required: true, options: [option("SMS","SMS","SMS"), option("Email","E-posta","Email"), option("Both","Her Ikisi","Both")] },
      { name: "language", type: "select", label: i18nLabel("Dil", "Language"), required: true, options: [option("tr","Turkce","Turkish"), option("en","Ingilizce","English")] },
      { name: "subject", type: "text", label: i18nLabel("Konu", "Subject"), fullWidth: true },
      { name: "body_template", type: "textarea", label: i18nLabel("Sablon Govdesi", "Body Template"), required: true, rows: 5, fullWidth: true },
      { name: "is_active", type: "checkbox", label: i18nLabel("Aktif", "Active"), checkboxLabel: i18nLabel("Aktif sablon", "Active template") },
    ],
  },
  accounting_entry: {
    key: "accounting_entry",
    title: i18nLabel("Hizli Muhasebe Kaydi", "Quick Accounting Entry"),
    subtitle: i18nLabel("Mutabakat odakli muhasebe kaydi olustur", "Create an accounting entry for reconciliation workflows"),
    submitUrl: "acentem_takipte.api.quick_create.create_quick_accounting_entry",
    resultKey: "accounting_entry",
    openRouteName: "accounting-entries-detail",
    successRefreshTargets: ["aux_list"],
    defaults: {
      source_doctype: "AT Policy",
      source_name: "",
      entry_type: "Policy",
      status: "Draft",
      policy: "",
      customer: "",
      insurance_company: "",
      currency: "TRY",
      local_amount: "",
      local_amount_try: "",
      external_amount: "",
      external_amount_try: "",
      external_ref: "",
    },
    fields: [
      { name: "source_doctype", type: "select", label: i18nLabel("Kaynak Tipi", "Source DocType"), required: true, options: [
        option("AT Policy","Police","Policy"),
        option("AT Payment","Odeme","Payment"),
        option("AT Claim","Hasar","Claim"),
      ]},
      { name: "source_name", type: "text", label: i18nLabel("Kaynak Kayit", "Source Name"), required: true },
      { name: "entry_type", type: "select", label: i18nLabel("Kayit Turu", "Entry Type"), required: true, options: [
        option("Policy","Police","Policy"),
        option("Payment","Odeme","Payment"),
        option("Claim","Hasar","Claim"),
      ]},
      { name: "status", type: "select", label: i18nLabel("Durum", "Status"), required: true, options: [
        option("Draft","Taslak","Draft"),
        option("Synced","Senkron","Synced"),
        option("Failed","Basarisiz","Failed"),
      ]},
      { name: "policy", type: "select", label: i18nLabel("Police", "Policy"), optionsSource: "policies" },
      { name: "customer", type: "select", label: i18nLabel("Musteri", "Customer"), optionsSource: "customers" },
      { name: "insurance_company", type: "select", label: i18nLabel("Sigorta Sirketi", "Insurance Company"), optionsSource: "insuranceCompanies" },
      { name: "currency", type: "select", label: i18nLabel("Doviz", "Currency"), options: [option("TRY","TRY","TRY"), option("USD","USD","USD"), option("EUR","EUR","EUR")] },
      { name: "local_amount", type: "number", label: i18nLabel("Yerel Tutar", "Local Amount"), step: "0.01" },
      { name: "local_amount_try", type: "number", label: i18nLabel("Yerel Tutar TRY", "Local Amount TRY"), step: "0.01" },
      { name: "external_amount", type: "number", label: i18nLabel("Dis Tutar", "External Amount"), step: "0.01" },
      { name: "external_amount_try", type: "number", label: i18nLabel("Dis Tutar TRY", "External Amount TRY"), step: "0.01" },
      { name: "external_ref", type: "text", label: i18nLabel("Dis Referans", "External Ref"), fullWidth: true },
    ],
  },
  reconciliation_item: {
    key: "reconciliation_item",
    title: i18nLabel("Hizli Mutabakat Kalemi", "Quick Reconciliation Item"),
    subtitle: i18nLabel("Mutabakat fark kaydi olustur", "Create a reconciliation mismatch record"),
    submitUrl: "acentem_takipte.api.quick_create.create_quick_reconciliation_item",
    resultKey: "reconciliation_item",
    openRouteName: "reconciliation-items-detail",
    successRefreshTargets: ["aux_list"],
    defaults: {
      accounting_entry: "",
      source_doctype: "",
      source_name: "",
      status: "Open",
      mismatch_type: "Amount",
      local_amount_try: "",
      external_amount_try: "",
      resolution_action: "",
      notes: "",
    },
    fields: [
      { name: "accounting_entry", type: "select", label: i18nLabel("Muhasebe Kaydi", "Accounting Entry"), optionsSource: "accountingEntries", required: true, fullWidth: true },
      { name: "source_doctype", type: "select", label: i18nLabel("Kaynak Tipi", "Source DocType"), options: [
        option("","Bos Birak","Blank"),
        option("AT Policy","Police","Policy"),
        option("AT Payment","Odeme","Payment"),
        option("AT Claim","Hasar","Claim"),
      ]},
      { name: "source_name", type: "text", label: i18nLabel("Kaynak Kayit", "Source Name") },
      { name: "status", type: "select", label: i18nLabel("Durum", "Status"), required: true, options: [
        option("Open","Acik","Open"),
        option("Resolved","Cozuldu","Resolved"),
        option("Ignored","Yoksayildi","Ignored"),
      ]},
      { name: "mismatch_type", type: "select", label: i18nLabel("Uyumsuzluk Tipi", "Mismatch Type"), required: true, options: [
        option("Amount","Tutar","Amount"),
        option("Currency","Doviz","Currency"),
        option("Missing External","Dis Kayit Eksik","Missing External"),
        option("Missing Local","Yerel Kayit Eksik","Missing Local"),
        option("Status","Durum","Status"),
        option("Other","Diger","Other"),
      ]},
      { name: "local_amount_try", type: "number", label: i18nLabel("Yerel TRY", "Local TRY"), step: "0.01" },
      { name: "external_amount_try", type: "number", label: i18nLabel("Dis TRY", "External TRY"), step: "0.01" },
      { name: "resolution_action", type: "select", label: i18nLabel("Cozum Aksiyonu", "Resolution Action"), options: [
        option("","Seciniz","Select"),
        option("Matched","Eslesti","Matched"),
        option("Adjusted","Duzeltildi","Adjusted"),
        option("Manual Override","Manuel Override","Manual Override"),
        option("Ignored","Yoksayildi","Ignored"),
      ]},
      { name: "notes", type: "textarea", label: i18nLabel("Not", "Notes"), rows: 3, fullWidth: true },
    ],
  },
};

function addQuickEditVariant(baseKey, editKey, trTitle, enTitle, trSubtitle, enSubtitle) {
  const base = quickCreateRegistry[baseKey];
  if (!base) return;
  quickCreateRegistry[editKey] = {
    ...base,
    key: editKey,
    title: i18nLabel(trTitle, enTitle),
    subtitle: i18nLabel(trSubtitle, enSubtitle),
    submitUrl: "acentem_takipte.api.quick_create.update_quick_aux_record",
    resultKey: "record",
    openRouteName: "",
    successRefreshTargets: ["aux_detail"],
  };
}

addQuickEditVariant(
  "insurance_company",
  "insurance_company_edit",
  "Sigorta Sirketini Duzenle",
  "Edit Insurance Company",
  "Ana veri sirket kaydini guncelle",
  "Update the insurance company master record"
);
addQuickEditVariant(
  "branch_master",
  "branch_master_edit",
  "Bransi Duzenle",
  "Edit Branch",
  "Brans ve sirket eslesmesini guncelle",
  "Update branch and company mapping"
);
addQuickEditVariant(
  "sales_entity_master",
  "sales_entity_master_edit",
  "Satis Birimini Duzenle",
  "Edit Sales Entity",
  "Satis orgutu kaydini guncelle",
  "Update sales organization record"
);
addQuickEditVariant(
  "notification_template_master",
  "notification_template_master_edit",
  "Bildirim Sablonunu Duzenle",
  "Edit Notification Template",
  "Sablon alanlarini guncelle",
  "Update notification template fields"
);
addQuickEditVariant(
  "accounting_entry",
  "accounting_entry_edit",
  "Muhasebe Kaydini Duzenle",
  "Edit Accounting Entry",
  "Muhasebe ve mutabakat alanlarini guncelle",
  "Update accounting and reconciliation fields"
);
addQuickEditVariant(
  "reconciliation_item",
  "reconciliation_item_edit",
  "Mutabakat Kalemini Duzenle",
  "Edit Reconciliation Item",
  "Mutabakat fark kaydini guncelle",
  "Update reconciliation mismatch record"
);

export function getQuickCreateConfig(key) {
  return quickCreateRegistry[key] || null;
}

export function buildQuickCreateDraft(config, overrides = {}) {
  if (!config) return {};
  return { ...(config.defaults || {}), ...overrides };
}

export function getLocalizedText(value, locale = "tr") {
  if (value == null) return "";
  if (typeof value === "string") return value;
  if (typeof value === "object") return value[locale] || value.tr || value.en || "";
  return String(value);
}
