function i18nLabel(tr, en) {
  return { tr, en };
}

function option(value, tr, en) {
  return { value, label: i18nLabel(tr, en) };
}

export const quickCreateRegistry = {
  offer: {
    key: "offer",
    title: i18nLabel("Detaylı Hızlı Teklif", "Detailed Quick Offer"),
    subtitle: i18nLabel("Müşteri, ürün ve finans alanlarıyla taslak teklif oluştur", "Create a draft offer with customer, product and financial fields"),
    submitUrl: "acentem_takipte.acentem_takipte.doctype.at_offer.at_offer.create_quick_offer",
    resultKey: "offer",
    openRouteName: "offer-detail",
    successRefreshTargets: ["offer_list", "offer_board"],
    defaults: {
      branch: "",
      insurance_company: "",
      sales_entity: "",
      offer_date: "",
      valid_until: "",
      currency: "TRY",
      status: "Draft",
      gross_premium: "",
      net_premium: "",
      tax_amount: "0",
      commission_amount: "0",
      notes: "",
    },
    fields: [
      { name: "sales_entity", type: "select", label: i18nLabel("Satış Birimi", "Sales Entity"), optionsSource: "salesEntities", fullWidth: false },
      { name: "insurance_company", type: "select", label: i18nLabel("Sigorta Şirketi", "Insurance Company"), optionsSource: "insuranceCompanies", fullWidth: false },
      { name: "branch", type: "select", label: i18nLabel("Sigorta Branşı", "Insurance Branch"), optionsSource: "branches", fullWidth: false },
      { name: "status", type: "select", label: i18nLabel("Durum", "Status"), options: [
        option("Draft", "Taslak", "Draft"),
        option("Sent", "Müşteriye Gönderildi", "Sent"),
        option("Açcepted", "Kabul Edildi", "Açcepted"),
        option("Rejected", "Reddedildi", "Rejected"),
      ], fullWidth: false },
      { name: "offer_date", type: "date", label: i18nLabel("Teklif Tarihi", "Offer Date"), fullWidth: false },
      { name: "valid_until", type: "date", label: i18nLabel("Geçerlilik Tarihi", "Valid Until"), fullWidth: false },
      { name: "currency", type: "select", label: i18nLabel("Döviz", "Currency"), options: [option("TRY", "TRY", "TRY"), option("USD", "USD", "USD"), option("EUR", "EUR", "EUR")], fullWidth: false },
      { name: "gross_premium", type: "number", label: i18nLabel("Brüt Prim", "Gross Premium"), min: 0, step: "0.01", fullWidth: false },
      { name: "net_premium", type: "number", label: i18nLabel("Net Prim", "Net Premium"), min: 0, step: "0.01", fullWidth: false },
      { name: "tax_amount", type: "number", label: i18nLabel("Vergi Tutarı", "Tax Amount"), min: 0, step: "0.01", fullWidth: false },
      { name: "commission_amount", type: "number", label: i18nLabel("Komisyon Tutarı", "Commission Amount"), min: 0, step: "0.01", fullWidth: false },
      { name: "notes", type: "textarea", label: i18nLabel("Açıklama / Not", "Notes"), rows: 3, fullWidth: true },
    ],
  },
  policy: {
    key: "policy",
    title: i18nLabel("Hızlı Poliçe Kaydı", "Quick Policy Entry"),
    subtitle: i18nLabel("Sistem kayıt numarası otomatik üretilir, şirket poliçe numarası opsiyoneldir", "Create a policy with an auto-generated record number and an optional carrier policy number"),
    submitUrl: "acentem_takipte.acentem_takipte.api.quick_create.create_quick_policy",
    resultKey: "policy",
    openRouteName: "policy-detail",
    successRefreshTargets: ["policy_list"],
    defaults: {
      customer: "",
      sales_entity: "",
      insurance_company: "",
      branch: "",
      policy_no: "",
      source_offer: "",
      status: "Active",
      issue_date: "",
      start_date: "",
      end_date: "",
      currency: "TRY",
      gross_premium: "",
      net_premium: "",
      tax_amount: "0",
      commission_amount: "0",
      notes: "",
    },
    fields: [
      { name: "customer", type: "select", label: i18nLabel("Müşteri", "Customer"), optionsSource: "customers", required: true },
      { name: "sales_entity", type: "select", label: i18nLabel("Satış Birimi", "Sales Entity"), optionsSource: "salesEntities", required: true },
      { name: "insurance_company", type: "select", label: i18nLabel("Sigorta Şirketi", "Insurance Company"), optionsSource: "insuranceCompanies", required: true },
      { name: "branch", type: "select", label: i18nLabel("Sigorta Branşı", "Insurance Branch"), optionsSource: "branches", required: true },
      { name: "policy_no", type: "text", label: i18nLabel("Sigorta Şirketi Poliçe No", "Carrier Policy Number") },
      { name: "source_offer", type: "select", label: i18nLabel("Kaynak Teklif", "Source Offer"), optionsSource: "offers" },
      { name: "status", type: "select", label: i18nLabel("Durum", "Status"), options: [
        option("Active", "Aktif", "Active"),
        option("KYT", "KYT", "KYT"),
        option("IPT", "IPT", "IPT"),
      ] },
      { name: "issue_date", type: "date", label: i18nLabel("Tanzim Tarihi", "Issue Date") },
      { name: "start_date", type: "date", label: i18nLabel("Başlangıç", "Start Date") },
      { name: "end_date", type: "date", label: i18nLabel("Bitiş", "End Date") },
      { name: "currency", type: "select", label: i18nLabel("Döviz", "Currency"), options: [option("TRY", "TRY", "TRY"), option("USD", "USD", "USD"), option("EUR", "EUR", "EUR")] },
      { name: "gross_premium", type: "number", label: i18nLabel("Brüt Prim", "Gross Premium"), required: true, min: 0, step: "0.01" },
      { name: "net_premium", type: "number", label: i18nLabel("Net Prim", "Net Premium"), min: 0, step: "0.01" },
      { name: "tax_amount", type: "number", label: i18nLabel("Vergi Tutarı", "Tax Amount"), min: 0, step: "0.01" },
      { name: "commission_amount", type: "number", label: i18nLabel("Komisyon Tutarı", "Commission Amount"), min: 0, step: "0.01" },
      { name: "notes", type: "textarea", label: i18nLabel("Not", "Notes"), rows: 3, fullWidth: true },
    ],
  },
  lead: {
    key: "lead",
    title: i18nLabel("Hızlı Lead Oluştur", "Quick Lead"),
    subtitle: i18nLabel("Temel satış ve potansiyel bilgileriyle fırsat oluştur", "Create a lead with sales and potential details"),
    submitUrl: "acentem_takipte.acentem_takipte.api.quick_create.create_quick_lead",
    resultKey: "lead",
    openRouteName: "lead-detail",
    successRefreshTargets: ["lead_list"],
    defaults: {
      first_name: "",
      last_name: "",
      phone: "",
      tax_id: "",
      email: "",
      status: "Open",
      customer: "",
      sales_entity: "",
      insurance_company: "",
      branch: "",
      estimated_gross_premium: "",
      notes: "",
    },
    fields: [
      { name: "first_name", type: "text", label: i18nLabel("Ad", "First Name"), required: true },
      { name: "last_name", type: "text", label: i18nLabel("Soyad", "Last Name") },
      { name: "phone", type: "text", label: i18nLabel("Telefon", "Phone") },
      { name: "tax_id", type: "text", label: i18nLabel("TC/VKN", "Tax ID") },
      { name: "email", type: "email", label: i18nLabel("E-posta", "Email") },
      { name: "status", type: "select", label: i18nLabel("Lead Durumu", "Lead Status"), options: [
        option("Draft", "Taslak", "Draft"),
        option("Open", "Açık", "Open"),
        option("Replied", "Görüşüldü", "Replied"),
        option("Closed", "Kapandı", "Closed"),
      ] },
      { name: "customer", type: "select", label: i18nLabel("Müşteri (Opsiyonel)", "Customer (Optional)"), optionsSource: "customers" },
      { name: "sales_entity", type: "select", label: i18nLabel("Satış Birimi", "Sales Entity"), optionsSource: "salesEntities" },
      { name: "insurance_company", type: "select", label: i18nLabel("Sigorta Şirketi", "Insurance Company"), optionsSource: "insuranceCompanies" },
      { name: "branch", type: "select", label: i18nLabel("Branş", "Branch"), optionsSource: "branches" },
      { name: "estimated_gross_premium", type: "number", label: i18nLabel("Tahmini Brüt Prim", "Estimated Gross Premium"), min: 0, step: "0.01" },
      { name: "notes", type: "textarea", label: i18nLabel("Not", "Notes"), rows: 3, fullWidth: true },
    ],
  },
  customer: {
    key: "customer",
    title: i18nLabel("Hızlı Müşteri Oluştur", "Quick Customer"),
    subtitle: i18nLabel("Sigortalı bilgileriyle müşteri kaydı oluştur", "Create a customer with insured profile fields"),
    submitUrl: "acentem_takipte.acentem_takipte.api.quick_create.create_quick_customer",
    resultKey: "customer",
    openRouteName: "customer-detail",
    successRefreshTargets: ["customer_list"],
    defaults: {
      full_name: "",
      tax_id: "",
      phone: "",
      email: "",
      address: "",
      birth_date: "",
      gender: "Unknown",
      marital_status: "Unknown",
      occupation: "",
      consent_status: "Unknown",
      assigned_agent: "",
    },
    fields: [
      { name: "full_name", type: "text", label: i18nLabel("Ad Soyad", "Full Name"), required: true, fullWidth: true },
      { name: "tax_id", type: "text", label: i18nLabel("TC/VKN", "Tax ID"), required: true },
      { name: "birth_date", type: "date", label: i18nLabel("Doğum Tarihi", "Birth Date") },
      { name: "phone", type: "text", label: i18nLabel("Telefon", "Phone") },
      { name: "email", type: "email", label: i18nLabel("E-posta", "Email") },
      { name: "gender", type: "select", label: i18nLabel("Cinsiyet", "Gender"), options: [
        option("Unknown", "Bilinmiyor", "Unknown"),
        option("Male", "Erkek", "Male"),
        option("Female", "Kadın", "Female"),
        option("Other", "Diğer", "Other"),
      ] },
      { name: "marital_status", type: "select", label: i18nLabel("Medeni Durumu", "Marital Status"), options: [
        option("Unknown", "Bilinmiyor", "Unknown"),
        option("Single", "Bekar", "Single"),
        option("Married", "Evli", "Married"),
        option("Divorced", "Boşanmış", "Divorced"),
        option("Widowed", "Dul", "Widowed"),
      ] },
      { name: "consent_status", type: "select", label: i18nLabel("İzin Durumu", "Consent Status"), options: [
        option("Unknown", "Bilinmiyor", "Unknown"),
        option("Granted", "Onaylı", "Granted"),
        option("Revoked", "İptal", "Revoked"),
      ] },
      { name: "assigned_agent", type: "text", label: i18nLabel("Temsilci (User)", "Assigned Agent (User)") },
      { name: "occupation", type: "text", label: i18nLabel("Meslek", "Occupation"), fullWidth: true },
      { name: "address", type: "textarea", label: i18nLabel("Adres", "Address"), rows: 3, fullWidth: true },
    ],
  },
  claim: {
    key: "claim",
    title: i18nLabel("Hızlı Hasar Aç", "Quick Claim"),
    subtitle: i18nLabel("Poliçeye bağlı hasar kaydı oluştur", "Create a claim linked to a policy"),
    submitUrl: "acentem_takipte.acentem_takipte.api.quick_create.create_quick_claim",
    resultKey: "claim",
    successRefreshTargets: ["claim_list"],
    defaults: {
      policy: "",
      customer: "",
      claim_no: "",
      claim_type: "Damage",
      claim_status: "Open",
      incident_date: "",
      reported_date: "",
      currency: "TRY",
      estimated_amount: "",
      approved_amount: "",
      notes: "",
    },
    fields: [
      { name: "policy", type: "select", label: i18nLabel("Poliçe", "Policy"), optionsSource: "policies", required: true },
      { name: "customer", type: "select", label: i18nLabel("Müşteri", "Customer"), optionsSource: "customers", required: true },
      { name: "claim_no", type: "text", label: i18nLabel("Hasar No", "Claim Number") },
      { name: "claim_type", type: "select", label: i18nLabel("Hasar Türü", "Claim Type"), options: [
        option("Damage", "Hasar", "Damage"),
        option("Health", "Saglik", "Health"),
        option("Theft", "Hirsizlik", "Theft"),
        option("Liability", "Sorumluluk", "Liability"),
        option("Other", "Diğer", "Other"),
      ] },
      { name: "claim_status", type: "select", label: i18nLabel("Durum", "Status"), options: [
        option("Draft", "Taslak", "Draft"),
        option("Open", "Açık", "Open"),
        option("Under Review", "Inceleme", "Under Review"),
        option("Approved", "Onaylandi", "Approved"),
        option("Rejected", "Reddedildi", "Rejected"),
      ] },
      { name: "incident_date", type: "date", label: i18nLabel("Hasar Tarihi", "Incident Date"), required: true },
      { name: "reported_date", type: "date", label: i18nLabel("Bildirim Tarihi", "Reported Date"), required: true },
      { name: "currency", type: "select", label: i18nLabel("Döviz", "Currency"), options: [option("TRY", "TRY", "TRY"), option("USD", "USD", "USD"), option("EUR", "EUR", "EUR")] },
      { name: "estimated_amount", type: "number", label: i18nLabel("Talep Tutarı", "Estimated Amount"), min: 0, step: "0.01" },
      { name: "approved_amount", type: "number", label: i18nLabel("Onaylanan Tutar", "Approved Amount"), min: 0, step: "0.01" },
      { name: "notes", type: "textarea", label: i18nLabel("Açıklama", "Notes"), rows: 3, fullWidth: true },
    ],
  },
  payment: {
    key: "payment",
    title: i18nLabel("Hızlı Ödeme/Tahsilat", "Quick Payment"),
    subtitle: i18nLabel("Tahsilat veya ödeme hareketi oluştur", "Create an inbound or outbound payment record"),
    submitUrl: "acentem_takipte.acentem_takipte.api.quick_create.create_quick_payment",
    resultKey: "payment",
    successRefreshTargets: ["payment_list"],
    defaults: {
      customer: "",
      policy: "",
      claim: "",
      sales_entity: "",
      payment_direction: "Inbound",
      payment_purpose: "Premium Collection",
      status: "Draft",
      payment_date: "",
      due_date: "",
      installment_count: "1",
      installment_interval_days: "30",
      currency: "TRY",
      amount: "",
      reference_no: "",
      notes: "",
    },
    fields: [
      { name: "payment_direction", type: "select", label: i18nLabel("Yön", "Direction"), options: [
        option("Inbound", "Tahsilat", "Inbound"),
        option("Outbound", "Ödeme", "Outbound"),
      ] },
      { name: "payment_purpose", type: "select", label: i18nLabel("Amac", "Purpose"), options: [
        option("Premium Collection", "Prim Tahsilati", "Premium Collection"),
        option("Commission Payout", "Komisyon Ödemesi", "Commission Payout"),
        option("Claim Payout", "Hasar Ödemesi", "Claim Payout"),
        option("Other", "Diğer", "Other"),
      ] },
      { name: "customer", type: "select", label: i18nLabel("Müşteri", "Customer"), optionsSource: "customers", required: true },
      { name: "policy", type: "select", label: i18nLabel("Poliçe", "Policy"), optionsSource: "policies" },
      { name: "claim", type: "select", label: i18nLabel("Hasar", "Claim"), optionsSource: "claims" },
      { name: "sales_entity", type: "select", label: i18nLabel("Satış Birimi", "Sales Entity"), optionsSource: "salesEntities" },
      { name: "status", type: "select", label: i18nLabel("Durum", "Status"), options: [
        option("Draft", "Taslak", "Draft"),
        option("Paid", "Odendi", "Paid"),
        option("Cancelled", "İptal", "Cancelled"),
      ] },
      { name: "payment_date", type: "date", label: i18nLabel("Tarih", "Payment Date"), required: true },
      { name: "due_date", type: "date", label: i18nLabel("Vade", "Due Date") },
      { name: "installment_count", type: "number", label: i18nLabel("Taksit Sayisi", "Installment Count"), min: 1, step: "1" },
      { name: "installment_interval_days", type: "number", label: i18nLabel("Taksit Araligi (Gun)", "Installment Interval (Days)"), min: 1, step: "1" },
      { name: "currency", type: "select", label: i18nLabel("Döviz", "Currency"), options: [option("TRY", "TRY", "TRY"), option("USD", "USD", "USD"), option("EUR", "EUR", "EUR")] },
      { name: "amount", type: "number", label: i18nLabel("Tutar", "Amount"), required: true, min: 0.01, step: "0.01" },
      { name: "reference_no", type: "text", label: i18nLabel("Dış Referans", "External Reference") },
      { name: "notes", type: "textarea", label: i18nLabel("Açıklama", "Notes"), rows: 3, fullWidth: true },
    ],
  },
  renewal_task: {
    key: "renewal_task",
    title: i18nLabel("Hızlı Yenileme Görevi", "Quick Renewal Task"),
    subtitle: i18nLabel("Poliçeye bağlı yenileme takip görevi oluştur", "Create a policy renewal follow-up task"),
    submitUrl: "acentem_takipte.acentem_takipte.api.quick_create.create_quick_renewal_task",
    resultKey: "renewal_task",
    openRouteName: "tasks-detail",
    successRefreshTargets: ["renewal_list"],
    defaults: {
      policy: "",
      customer: "",
      renewal_date: "",
      due_date: "",
      status: "Open",
      lost_reason_code: "",
      competitor_name: "",
      assigned_to: "",
      notes: "",
      auto_created: false,
    },
    fields: [
      { name: "policy", type: "select", label: i18nLabel("Poliçe", "Policy"), optionsSource: "policies", required: true },
      { name: "customer", type: "select", label: i18nLabel("Müşteri", "Customer"), optionsSource: "customers", required: true },
      { name: "renewal_date", type: "date", label: i18nLabel("Yenileme Tarihi", "Renewal Date"), required: true },
      { name: "due_date", type: "date", label: i18nLabel("Son Tarih", "Due Date"), required: true },
      { name: "status", type: "select", label: i18nLabel("Durum", "Status"), options: [
        option("Open", "Açık", "Open"),
        option("In Progress", "Devam Ediyor", "In Progress"),
        option("Done", "Tamamlandı", "Done"),
        option("Cancelled", "İptal", "Cancelled"),
      ] },
      { name: "lost_reason_code", type: "select", label: i18nLabel("Kayip Sebebi", "Lost Reason"), options: [
        option("", "Bos Birak", "Blank"),
        option("Price", "Fiyat", "Price"),
        option("Competitor", "Rakip", "Competitor"),
        option("Service", "Hizmet", "Service"),
        option("Customer Declined", "Müşteri Vazgeçti", "Customer Declined"),
        option("Coverage Mismatch", "Teminat Uyumsuzlugu", "Coverage Mismatch"),
        option("Other", "Diğer", "Other"),
      ] },
      { name: "competitor_name", type: "text", label: i18nLabel("Rakip Adi", "Competitor Name"), fullWidth: true },
      { name: "assigned_to", type: "text", label: i18nLabel("Atanan Kişi (User)", "Assigned To (User)") },
      { name: "auto_created", type: "checkbox", label: i18nLabel("Otomatik Oluşturuldu", "Auto Created") },
      { name: "notes", type: "textarea", label: i18nLabel("Not", "Notes"), rows: 3, fullWidth: true },
    ],
  },
  customer_relation: {
    key: "customer_relation",
    title: i18nLabel("Hızlı Müşteri İlişkisi", "Quick Customer Relation"),
    subtitle: i18nLabel("Müşteriler arası ilişki kaydı oluştur", "Create a relationship between customers"),
    submitUrl: "acentem_takipte.acentem_takipte.api.quick_create.create_quick_customer_relation",
    resultKey: "customer_relation",
    openRouteName: "customer-relations-detail",
    successRefreshTargets: ["customer-relations-list"],
    defaults: {
      customer: "",
      related_customer: "",
      relation_type: "Other",
      is_household: false,
      notes: "",
    },
    fields: [
      { name: "customer", type: "select", label: i18nLabel("Müşteri", "Customer"), optionsSource: "customers", required: true },
      { name: "related_customer", type: "select", label: i18nLabel("İlişkili Müşteri", "Related Customer"), optionsSource: "customers", required: true },
      { name: "relation_type", type: "select", label: i18nLabel("İlişki Turu", "Relation Type"), options: [
        option("Spouse", "Es", "Spouse"),
        option("Child", "Cocuk", "Child"),
        option("Parent", "Ebeveyn", "Parent"),
        option("Sibling", "Kardes", "Sibling"),
        option("Partner", "Partner", "Partner"),
        option("Household", "Hane", "Household"),
        option("Other", "Diğer", "Other"),
      ] },
      { name: "is_household", type: "checkbox", label: i18nLabel("Aynı Hane", "Same Household") },
      { name: "notes", type: "textarea", label: i18nLabel("Not", "Notes"), rows: 3, fullWidth: true },
    ],
  },
  insured_asset: {
    key: "insured_asset",
    title: i18nLabel("Hızlı Sigortalanan Varlık", "Quick Insured Asset"),
    subtitle: i18nLabel("Müşteriye bağlı sigortalanan varlık kaydı oluştur", "Create an insured asset linked to a customer"),
    submitUrl: "acentem_takipte.acentem_takipte.api.quick_create.create_quick_insured_asset",
    resultKey: "insured_asset",
    openRouteName: "insured-assets-detail",
    successRefreshTargets: ["insured-assets-list"],
    defaults: {
      customer: "",
      policy: "",
      asset_type: "Other",
      asset_label: "",
      asset_identifier: "",
      notes: "",
    },
    fields: [
      { name: "customer", type: "select", label: i18nLabel("Müşteri", "Customer"), optionsSource: "customers", required: true },
      { name: "policy", type: "select", label: i18nLabel("Poliçe", "Policy"), optionsSource: "policies" },
      { name: "asset_type", type: "select", label: i18nLabel("Varlık Turu", "Asset Type"), options: [
        option("Vehicle", "Araç", "Vehicle"),
        option("Home", "Konut", "Home"),
        option("Health Person", "Saglik Kişi", "Health Person"),
        option("Workplace", "Isyeri", "Workplace"),
        option("Travel", "Seyahat", "Travel"),
        option("Boat", "Tekne", "Boat"),
        option("Farm", "Tarim", "Farm"),
        option("Other", "Diğer", "Other"),
      ] },
      { name: "asset_label", type: "text", label: i18nLabel("Varlık Basligi", "Asset Label"), required: true, fullWidth: true },
      { name: "asset_identifier", type: "text", label: i18nLabel("Varlık Kimligi", "Asset Identifier"), fullWidth: true },
      { name: "notes", type: "textarea", label: i18nLabel("Not", "Notes"), rows: 3, fullWidth: true },
    ],
  },
  call_note: {
    key: "call_note",
    title: i18nLabel("Hızlı Arama Notu", "Quick Call Note"),
    subtitle: i18nLabel("Müşteriyle yapılan arama kaydını oluştur", "Create a phone interaction record"),
    submitUrl: "acentem_takipte.acentem_takipte.api.quick_create.create_quick_call_note",
    resultKey: "call_note",
    openRouteName: "call-notes-detail",
    successRefreshTargets: ["call-notes-list"],
    defaults: {
      customer: "",
      policy: "",
      claim: "",
      channel: "Phone Call",
      direction: "Outbound",
      call_status: "Completed",
      call_outcome: "",
      note_at: "",
      next_follow_up_on: "",
      notes: "",
    },
    fields: [
      { name: "customer", type: "select", label: i18nLabel("Müşteri", "Customer"), optionsSource: "customers", required: true },
      { name: "policy", type: "select", label: i18nLabel("Poliçe", "Policy"), optionsSource: "policies" },
      { name: "claim", type: "select", label: i18nLabel("Hasar", "Claim"), optionsSource: "claims" },
      { name: "channel", type: "select", label: i18nLabel("Kanal", "Channel"), options: [
        option("Phone Call", "Telefon", "Phone Call"),
        option("WhatsApp Call", "WhatsApp Arama", "WhatsApp Call"),
        option("Video Call", "Görüntülü Arama", "Video Call"),
        option("Other", "Diğer", "Other"),
      ] },
      { name: "direction", type: "select", label: i18nLabel("Yön", "Direction"), options: [
        option("Inbound", "Gelen", "Inbound"),
        option("Outbound", "Giden", "Outbound"),
      ] },
      { name: "call_status", type: "select", label: i18nLabel("Arama Durumu", "Call Status"), options: [
        option("Planned", "Planlandi", "Planned"),
        option("Completed", "Tamamlandı", "Completed"),
        option("Missed", "Kacirildi", "Missed"),
        option("No Answer", "Ulaşılamadı", "No Answer"),
        option("Cancelled", "İptal", "Cancelled"),
      ] },
      { name: "call_outcome", type: "text", label: i18nLabel("Arama Sonucu", "Call Outcome"), fullWidth: true },
      { name: "note_at", type: "datetime", label: i18nLabel("Not Zamani", "Note At"), required: true },
      { name: "next_follow_up_on", type: "date", label: i18nLabel("Sonraki Takip", "Next Follow Up") },
      { name: "notes", type: "textarea", label: i18nLabel("Not", "Notes"), rows: 3, fullWidth: true },
    ],
  },
  segment: {
    key: "segment",
    title: i18nLabel("Hızlı Segment", "Quick Segment"),
    subtitle: i18nLabel("Kampanya hedef segmenti oluştur", "Create a campaign target segment"),
    submitUrl: "acentem_takipte.acentem_takipte.api.quick_create.create_quick_segment",
    resultKey: "segment",
    openRouteName: "segments-detail",
    successRefreshTargets: ["segments-list"],
    defaults: {
      segment_name: "",
      segment_type: "Static",
      channel_focus: "WHATSAPP",
      status: "Draft",
      criteria_json: "",
      notes: "",
    },
    fields: [
      { name: "segment_name", type: "text", label: i18nLabel("Segment Adi", "Segment Name"), required: true, fullWidth: true },
      { name: "segment_type", type: "select", label: i18nLabel("Segment Türü", "Segment Type"), options: [
        option("Static", "Statik", "Static"),
        option("Dynamic", "Dinamik", "Dynamic"),
        option("Operational", "Operasyonel", "Operational"),
      ] },
      { name: "channel_focus", type: "select", label: i18nLabel("Kanal Odagi", "Channel Focus"), options: [
        option("WHATSAPP", "WhatsApp", "WhatsApp"),
        option("SMS", "SMS", "SMS"),
        option("Email", "E-posta", "Email"),
        option("Phone Call", "Telefon", "Phone Call"),
      ] },
      { name: "status", type: "select", label: i18nLabel("Durum", "Status"), options: [
        option("Draft", "Taslak", "Draft"),
        option("Active", "Aktif", "Active"),
        option("Archived", "Arşiv", "Archived"),
      ] },
      { name: "criteria_json", type: "textarea", label: i18nLabel("Kriter JSON", "Criteria JSON"), rows: 4, fullWidth: true },
      { name: "notes", type: "textarea", label: i18nLabel("Not", "Notes"), rows: 3, fullWidth: true },
    ],
  },
  campaign: {
    key: "campaign",
    title: i18nLabel("Hızlı Kampanya", "Quick Campaign"),
    subtitle: i18nLabel("Segmente bağlı kampanya oluştur", "Create a segment-based campaign"),
    submitUrl: "acentem_takipte.acentem_takipte.api.quick_create.create_quick_campaign",
    resultKey: "campaign",
    openRouteName: "campaigns-detail",
    successRefreshTargets: ["campaigns-list"],
    defaults: {
      campaign_name: "",
      segment: "",
      template: "",
      channel: "WHATSAPP",
      status: "Draft",
      scheduled_for: "",
      notes: "",
    },
    fields: [
      { name: "campaign_name", type: "text", label: i18nLabel("Kampanya Adi", "Campaign Name"), required: true, fullWidth: true },
      { name: "segment", type: "select", label: i18nLabel("Segment", "Segment"), optionsSource: "segments", required: true },
      { name: "template", type: "select", label: i18nLabel("Şablon", "Template"), optionsSource: "notificationTemplates" },
      { name: "channel", type: "select", label: i18nLabel("Kanal", "Channel"), options: [
        option("WHATSAPP", "WhatsApp", "WhatsApp"),
        option("SMS", "SMS", "SMS"),
        option("Email", "E-posta", "Email"),
        option("Phone Call", "Telefon", "Phone Call"),
      ] },
      { name: "status", type: "select", label: i18nLabel("Durum", "Status"), options: [
        option("Draft", "Taslak", "Draft"),
        option("Planned", "Planlandi", "Planned"),
        option("Running", "Çalışıyor", "Running"),
        option("Completed", "Tamamlandı", "Completed"),
        option("Cancelled", "İptal", "Cancelled"),
      ] },
      { name: "scheduled_for", type: "datetime", label: i18nLabel("Planlanan Zaman", "Scheduled For") },
      { name: "notes", type: "textarea", label: i18nLabel("Not", "Notes"), rows: 3, fullWidth: true },
    ],
  },
  notification_draft: {
    key: "notification_draft",
    title: i18nLabel("Hızlı Bildirim Taslagi", "Quick Notification Draft"),
    subtitle: i18nLabel("Şablon tabanlı bildirim taslağı oluştur", "Create a template-based notification draft"),
    submitUrl: "acentem_takipte.acentem_takipte.api.communication.create_quick_notification_draft",
    resultKey: "draft",
    openRouteName: "notification-drafts-detail",
    successRefreshTargets: ["notification_draft_list", "aux_list", "communication_snapshot"],
    defaults: {
      template: "",
      channel: "",
      language: "tr",
      customer: "",
      recipient: "",
      reference_doctype: "",
      reference_name: "",
      subject: "",
      body: "",
      status: "Draft",
    },
    fields: [
      { name: "template", type: "select", label: i18nLabel("Şablon", "Template"), optionsSource: "notificationTemplates", required: true },
      {
        name: "channel",
        type: "select",
        label: i18nLabel("Kanal", "Channel"),
        options: [option("", "Template Kanal", "Template Channel"), option("SMS", "SMS", "SMS"), option("Email", "E-posta", "Email"), option("WHATSAPP", "WhatsApp", "WhatsApp")],
      },
      { name: "language", type: "select", label: i18nLabel("Dil", "Language"), options: [option("tr", "Türkçe", "Turkish"), option("en", "İngilizce", "English")] },
      { name: "customer", type: "select", label: i18nLabel("Müşteri", "Customer"), optionsSource: "customers" },
      { name: "recipient", type: "text", label: i18nLabel("Alıcı", "Recipient"), required: true },
      {
        name: "reference_doctype",
        type: "select",
        label: i18nLabel("Referans Tipi", "Reference Type"),
        options: [
          option("", "Yok", "None"),
          option("AT Lead", "Lead", "Lead"),
          option("AT Offer", "Teklif", "Offer"),
          option("AT Policy", "Poliçe", "Policy"),
          option("AT Customer", "Müşteri", "Customer"),
          option("AT Claim", "Hasar", "Claim"),
          option("AT Payment", "Ödeme", "Payment"),
          option("AT Renewal Task", "Yenileme Görevi", "Renewal Task"),
        ],
      },
      { name: "reference_name", type: "text", label: i18nLabel("Referans Kayıt", "Reference Record") },
      { name: "status", type: "select", label: i18nLabel("Durum", "Status"), options: [
        option("Draft", "Taslak", "Draft"),
        option("Queued", "Kuyrukta", "Queued"),
      ] },
      { name: "subject", type: "text", label: i18nLabel("Konu", "Subject"), fullWidth: true },
      { name: "body", type: "textarea", label: i18nLabel("Mesaj", "Message"), rows: 4, fullWidth: true },
    ],
  },
  communication_message: {
    key: "communication_message",
    title: i18nLabel("Hızlı İletişim", "Quick Communication"),
    subtitle: i18nLabel("Taslak kaydet veya hemen gönder", "Save as draft or send immediately"),
    submitUrl: "acentem_takipte.acentem_takipte.api.communication.create_quick_notification_draft",
    resultKey: "draft",
    successRefreshTargets: ["communication_snapshot", "notification_draft_list"],
    defaults: {
      template: "",
      channel: "",
      language: "tr",
      customer: "",
      recipient: "",
      reference_doctype: "",
      reference_name: "",
      subject: "",
      body: "",
    },
    fields: [
      { name: "template", type: "select", label: i18nLabel("Şablon", "Template"), optionsSource: "notificationTemplates", required: true },
      {
        name: "channel",
        type: "select",
        label: i18nLabel("Kanal", "Channel"),
        options: [option("", "Template Kanal", "Template Channel"), option("SMS", "SMS", "SMS"), option("Email", "E-posta", "Email"), option("WHATSAPP", "WhatsApp", "WhatsApp")],
      },
      { name: "language", type: "select", label: i18nLabel("Dil", "Language"), options: [option("tr", "Türkçe", "Turkish"), option("en", "İngilizce", "English")] },
      { name: "customer", type: "select", label: i18nLabel("Müşteri", "Customer"), optionsSource: "customers" },
      { name: "recipient", type: "text", label: i18nLabel("Alıcı", "Recipient"), required: true },
      {
        name: "reference_doctype",
        type: "select",
        label: i18nLabel("Referans Tipi", "Reference Type"),
        options: [
          option("", "Yok", "None"),
          option("AT Lead", "Lead", "Lead"),
          option("AT Offer", "Teklif", "Offer"),
          option("AT Policy", "Poliçe", "Policy"),
          option("AT Customer", "Müşteri", "Customer"),
          option("AT Claim", "Hasar", "Claim"),
          option("AT Payment", "Ödeme", "Payment"),
          option("AT Renewal Task", "Yenileme Görevi", "Renewal Task"),
        ],
      },
      { name: "reference_name", type: "text", label: i18nLabel("Referans Kayıt", "Reference Record") },
      { name: "subject", type: "text", label: i18nLabel("Konu (E-posta)", "Subject (Email)"), fullWidth: true },
      { name: "body", type: "textarea", label: i18nLabel("Mesaj", "Message"), rows: 4, fullWidth: true },
    ],
  },
  insurance_company: {
    key: "insurance_company",
    title: i18nLabel("Hızlı Sigorta Şirketi", "Quick Insurance Company"),
    subtitle: i18nLabel("Ana veri şirket kaydı oluştur", "Create an insurance company master record"),
    submitUrl: "acentem_takipte.acentem_takipte.api.quick_create.create_quick_insurance_company",
    resultKey: "company",
    openRouteName: "companies-detail",
    successRefreshTargets: ["aux_list"],
    defaults: { company_name: "", company_code: "", is_active: true },
    fields: [
      { name: "company_name", type: "text", label: i18nLabel("Şirket Adı", "Company Name"), required: true, fullWidth: true },
      { name: "company_code", type: "text", label: i18nLabel("Şirket Kodu", "Company Code") },
      { name: "is_active", type: "checkbox", label: i18nLabel("Aktif", "Active"), checkboxLabel: i18nLabel("Aktif şirket", "Active company") },
    ],
  },
  branch_master: {
    key: "branch_master",
    title: i18nLabel("Hızlı Branş", "Quick Branch"),
    subtitle: i18nLabel("Branş ve şirket eşleşmesi oluştur", "Create a branch and company mapping"),
    submitUrl: "acentem_takipte.acentem_takipte.api.quick_create.create_quick_branch",
    resultKey: "branch",
    openRouteName: "branches-detail",
    successRefreshTargets: ["aux_list"],
    defaults: { branch_name: "", branch_code: "", insurance_company: "", is_active: true },
    fields: [
      { name: "branch_name", type: "text", label: i18nLabel("Branş Adı", "Branch Name"), required: true, fullWidth: true },
      { name: "branch_code", type: "text", label: i18nLabel("Branş Kodu", "Branch Code") },
      { name: "insurance_company", type: "select", label: i18nLabel("Sigorta Şirketi", "Insurance Company"), optionsSource: "insuranceCompanies" },
      { name: "is_active", type: "checkbox", label: i18nLabel("Aktif", "Active"), checkboxLabel: i18nLabel("Aktif brans", "Active branch") },
    ],
  },
  sales_entity_master: {
    key: "sales_entity_master",
    title: i18nLabel("Hızlı Satış Birimi", "Quick Sales Entity"),
    subtitle: i18nLabel("Satış örgütü kaydı oluştur", "Create a sales organization record"),
    submitUrl: "acentem_takipte.acentem_takipte.api.quick_create.create_quick_sales_entity",
    resultKey: "sales_entity",
    openRouteName: "sales-entities-detail",
    successRefreshTargets: ["aux_list"],
    defaults: { entity_type: "Agency", full_name: "", parent_entity: "" },
    fields: [
      { name: "entity_type", type: "select", label: i18nLabel("Tip", "Entity Type"), required: true, options: [
        option("Agency", "Acente", "Agency"),
        option("Sub-Account", "Alt Hesap", "Sub-Account"),
        option("Representative", "Temsilci", "Representative"),
      ] },
      { name: "full_name", type: "text", label: i18nLabel("Tam Ad", "Full Name"), required: true, fullWidth: true },
      { name: "parent_entity", type: "select", label: i18nLabel("Bağlı Birim", "Parent Entity"), optionsSource: "salesEntities" },
    ],
  },
  notification_template_master: {
    key: "notification_template_master",
    title: i18nLabel("Hızlı Bildirim Şablonu", "Quick Notification Template"),
    subtitle: i18nLabel("Kanal ve dil bazlı şablon oluştur", "Create a channel and language template"),
    submitUrl: "acentem_takipte.acentem_takipte.api.quick_create.create_quick_notification_template",
    resultKey: "template",
    openRouteName: "templates-detail",
    successRefreshTargets: ["aux_list"],
    defaults: {
      template_key: "",
      event_key: "",
      channel: "WHATSAPP",
      language: "tr",
      content_mode: "template",
      provider_template_name: "",
      provider_template_category: "",
      variables_schema_json: "",
      subject: "",
      body_template: "",
      sms_body_template: "",
      email_body_template: "",
      whatsapp_body_template: "",
      is_active: true,
    },
    fields: [
      { name: "template_key", type: "text", label: i18nLabel("Şablon Anahtarı", "Template Key"), required: true },
      { name: "event_key", type: "text", label: i18nLabel("Olay Anahtarı", "Event Key"), required: true },
      { name: "channel", type: "select", label: i18nLabel("Kanal", "Channel"), required: true, options: [option("SMS","SMS","SMS"), option("Email","E-posta","Email"), option("WHATSAPP","WhatsApp","WhatsApp"), option("Both","Her İkisi","Both")] },
      { name: "language", type: "select", label: i18nLabel("Dil", "Language"), required: true, options: [option("tr","Türkçe","Turkish"), option("en","İngilizce","English")] },
      { name: "content_mode", type: "select", label: i18nLabel("İçerik Modu", "Content Mode"), required: true, options: [option("freeform","Serbest Metin","Freeform"), option("template","Sağlayıcı Şablonu","Provider Template")] },
      { name: "provider_template_name", type: "text", label: i18nLabel("Sağlayıcı Şablon Adı", "Provider Template Name"), fullWidth: true },
      { name: "provider_template_category", type: "text", label: i18nLabel("Sağlayıcı Kategori", "Provider Category") },
      { name: "variables_schema_json", type: "textarea", label: i18nLabel("Değişken Şeması JSON", "Variables Schema JSON"), rows: 3, fullWidth: true },
      { name: "subject", type: "text", label: i18nLabel("Konu", "Subject"), fullWidth: true },
      { name: "body_template", type: "textarea", label: i18nLabel("Şablon Gövdesi", "Body Template"), required: true, rows: 5, fullWidth: true },
      { name: "sms_body_template", type: "textarea", label: i18nLabel("SMS Gövdesi", "SMS Body"), rows: 3, fullWidth: true },
      { name: "email_body_template", type: "textarea", label: i18nLabel("E-posta Gövdesi", "Email Body"), rows: 3, fullWidth: true },
      { name: "whatsapp_body_template", type: "textarea", label: i18nLabel("WhatsApp Gövdesi", "WhatsApp Body"), rows: 3, fullWidth: true },
      { name: "is_active", type: "checkbox", label: i18nLabel("Aktif", "Active"), checkboxLabel: i18nLabel("Aktif şablon", "Active template") },
    ],
  },
  accounting_entry: {
    key: "accounting_entry",
    title: i18nLabel("Hızlı Muhasebe Kaydı", "Quick Accounting Entry"),
    subtitle: i18nLabel("Mutabakat odaklı muhasebe kaydı oluştur", "Create an accounting entry for reconciliation workflows"),
    submitUrl: "acentem_takipte.acentem_takipte.api.quick_create.create_quick_accounting_entry",
    resultKey: "accounting_entry",
    openRouteName: "accounting-entries-detail",
    successRefreshTargets: ["aux_list"],
    defaults: {
      entry_type: "Policy",
      status: "Draft",
      policy: "",
      customer: "",
      insurance_company: "",
      currency: "TRY",
      local_amount: "",
      local_amount_try: "",
      external_amount: "",
      external_amount_try: "",
      external_ref: "",
    },
    fields: [
      { name: "entry_type", type: "select", label: i18nLabel("Kayıt Türü", "Entry Type"), required: true, options: [
        option("Policy","Poliçe","Policy"),
        option("Payment","Ödeme","Payment"),
        option("Claim","Hasar","Claim"),
      ]},
      { name: "status", type: "select", label: i18nLabel("Durum", "Status"), required: true, options: [
        option("Draft","Taslak","Draft"),
        option("Synced","Senkron","Synced"),
        option("Failed","Başarısız","Failed"),
      ]},
      { name: "policy", type: "select", label: i18nLabel("Poliçe", "Policy"), optionsSource: "policies" },
      { name: "customer", type: "select", label: i18nLabel("Müşteri", "Customer"), optionsSource: "customers" },
      { name: "insurance_company", type: "select", label: i18nLabel("Sigorta Şirketi", "Insurance Company"), optionsSource: "insuranceCompanies" },
      { name: "currency", type: "select", label: i18nLabel("Döviz", "Currency"), options: [option("TRY","TRY","TRY"), option("USD","USD","USD"), option("EUR","EUR","EUR")] },
      { name: "local_amount", type: "number", label: i18nLabel("Yerel Tutar", "Local Amount"), step: "0.01" },
      { name: "local_amount_try", type: "number", label: i18nLabel("Yerel Tutar TRY", "Local Amount TRY"), step: "0.01" },
      { name: "external_amount", type: "number", label: i18nLabel("Dış Tutar", "External Amount"), step: "0.01" },
      { name: "external_amount_try", type: "number", label: i18nLabel("Dış Tutar TRY", "External Amount TRY"), step: "0.01" },
      { name: "external_ref", type: "text", label: i18nLabel("Dış Referans", "External Ref"), fullWidth: true },
    ],
  },
  reconciliation_item: {
    key: "reconciliation_item",
    title: i18nLabel("Hızlı Mutabakat Kalemi", "Quick Reconciliation Item"),
    subtitle: i18nLabel("Mutabakat fark kaydı oluştur", "Create a reconciliation mismatch record"),
    submitUrl: "acentem_takipte.acentem_takipte.api.quick_create.create_quick_reconciliation_item",
    resultKey: "reconciliation_item",
    openRouteName: "reconciliation-items-detail",
    successRefreshTargets: ["aux_list"],
    defaults: {
      accounting_entry: "",
      status: "Open",
      mismatch_type: "Amount",
      local_amount_try: "",
      external_amount_try: "",
      resolution_action: "",
      notes: "",
    },
    fields: [
      { name: "accounting_entry", type: "select", label: i18nLabel("Muhasebe Kaydı", "Accounting Entry"), optionsSource: "accountingEntries", required: true, fullWidth: true },
      { name: "status", type: "select", label: i18nLabel("Durum", "Status"), required: true, options: [
        option("Open","Açık","Open"),
        option("Resolved","Çözüldü","Resolved"),
        option("Ignored","Yoksayıldı","Ignored"),
      ]},
      { name: "mismatch_type", type: "select", label: i18nLabel("Uyumsuzluk Tipi", "Mismatch Type"), required: true, options: [
        option("Amount","Tutar","Amount"),
        option("Currency","Döviz","Currency"),
        option("Missing External","Dış Kayıt Eksik","Missing External"),
        option("Missing Local","Yerel Kayıt Eksik","Missing Local"),
        option("Status","Durum","Status"),
        option("Other","Diğer","Other"),
      ]},
      { name: "local_amount_try", type: "number", label: i18nLabel("Yerel TRY", "Local TRY"), step: "0.01" },
      { name: "external_amount_try", type: "number", label: i18nLabel("Dış TRY", "External TRY"), step: "0.01" },
      { name: "resolution_action", type: "select", label: i18nLabel("Çözüm Aksiyonu", "Resolution Action"), options: [
        option("","Seçiniz","Select"),
        option("Matched","Eşleşti","Matched"),
        option("Adjusted","Düzeltildi","Adjusted"),
        option("Manual Override","Manuel Override","Manual Override"),
        option("Ignored","Yoksayıldı","Ignored"),
      ]},
      { name: "notes", type: "textarea", label: i18nLabel("Not", "Notes"), rows: 3, fullWidth: true },
    ],
  },
  ownership_assignment: {
    key: "ownership_assignment",
    title: i18nLabel("Hızlı Atama", "Quick Assignment"),
    subtitle: i18nLabel("Kayıt sahipliği ve operasyon ataması oluştur", "Create a record ownership and operational assignment"),
    submitUrl: "acentem_takipte.acentem_takipte.api.quick_create.create_quick_ownership_assignment",
    resultKey: "ownership_assignment",
    openRouteName: "ownership-assignments-detail",
    successRefreshTargets: ["ownership-assignments-list"],
    defaults: {
      source_doctype: "AT Customer",
      source_name: "",
      customer: "",
      policy: "",
      assigned_to: "",
      assignment_role: "Owner",
      status: "Open",
      priority: "Normal",
      due_date: "",
      notes: "",
    },
    fields: [
      { name: "source_doctype", type: "select", label: i18nLabel("Kaynak Tipi", "Source Type"), options: [
        option("AT Customer", "Müşteri", "Customer"),
        option("AT Policy", "Poliçe", "Policy"),
        option("AT Claim", "Hasar", "Claim"),
        option("AT Renewal Task", "Yenileme Görevi", "Renewal Task"),
        option("AT Campaign", "Kampanya", "Campaign"),
      ] },
      { name: "source_name", type: "text", label: i18nLabel("Kaynak Kayıt", "Source Record"), required: true },
      { name: "customer", type: "select", label: i18nLabel("Müşteri", "Customer"), optionsSource: "customers" },
      { name: "policy", type: "select", label: i18nLabel("Poliçe", "Policy"), optionsSource: "policies" },
      { name: "assigned_to", type: "text", label: i18nLabel("Atanan Kullanıcı", "Assigned User"), required: true },
      { name: "assignment_role", type: "select", label: i18nLabel("Atama Rolu", "Assignment Role"), options: [
        option("Owner", "Sahip", "Owner"),
        option("Assignee", "Sorumlu", "Assignee"),
        option("Reviewer", "Gozden Geciren", "Reviewer"),
        option("Follower", "Takipci", "Follower"),
      ] },
      { name: "status", type: "select", label: i18nLabel("Durum", "Status"), options: [
        option("Open", "Açık", "Open"),
        option("In Progress", "Devam Ediyor", "In Progress"),
        option("Blocked", "Bloke", "Blocked"),
        option("Done", "Tamamlandı", "Done"),
        option("Cancelled", "İptal", "Cancelled"),
      ] },
      { name: "priority", type: "select", label: i18nLabel("Öncelik", "Priority"), options: [
        option("Low", "Düşük", "Low"),
        option("Normal", "Normal", "Normal"),
        option("High", "Yüksek", "High"),
        option("Critical", "Kritik", "Critical"),
      ] },
      { name: "due_date", type: "date", label: i18nLabel("Termin", "Due Date") },
      { name: "notes", type: "textarea", label: i18nLabel("Not", "Notes"), rows: 3, fullWidth: true },
    ],
  },
  task: {
    key: "task",
    title: i18nLabel("Hızlı Görev", "Quick Task"),
    subtitle: i18nLabel("Görev ve takip kaydı oluştur", "Create a task and follow-up item"),
    submitUrl: "acentem_takipte.acentem_takipte.api.quick_create.create_quick_task",
    resultKey: "task",
    openRouteName: "tasks-detail",
    successRefreshTargets: ["tasks-list"],
    defaults: {
      task_title: "",
      task_type: "Follow-up",
      source_doctype: "AT Customer",
      source_name: "",
      customer: "",
      policy: "",
      claim: "",
      assigned_to: "",
      status: "Open",
      priority: "Normal",
      due_date: "",
      reminder_at: "",
      notes: "",
    },
    fields: [
      { name: "task_title", type: "text", label: i18nLabel("Görev Başlığı", "Task Title"), required: true },
      { name: "task_type", type: "select", label: i18nLabel("Görev Tipi", "Task Type"), options: [
        option("Follow-up", "Takip", "Follow-up"),
        option("Visit", "Ziyaret", "Visit"),
        option("Call", "Arama", "Call"),
        option("Collection", "Tahsilat", "Collection"),
        option("Claim", "Hasar", "Claim"),
        option("Renewal", "Yenileme", "Renewal"),
        option("Review", "Inceleme", "Review"),
        option("Other", "Diğer", "Other"),
      ] },
      { name: "source_doctype", type: "select", label: i18nLabel("Kaynak Tipi", "Source Type"), options: [
        option("AT Customer", "Müşteri", "Customer"),
        option("AT Policy", "Poliçe", "Policy"),
        option("AT Claim", "Hasar", "Claim"),
        option("AT Renewal Task", "Yenileme Görevi", "Renewal Task"),
        option("AT Campaign", "Kampanya", "Campaign"),
        option("AT Ownership Assignment", "Atama", "Assignment"),
        option("AT Call Note", "Arama Notu", "Call Note"),
      ] },
      { name: "source_name", type: "text", label: i18nLabel("Kaynak Kayıt", "Source Record") },
      { name: "customer", type: "select", label: i18nLabel("Müşteri", "Customer"), optionsSource: "customers" },
      { name: "policy", type: "select", label: i18nLabel("Poliçe", "Policy"), optionsSource: "policies" },
      { name: "claim", type: "text", label: i18nLabel("Hasar", "Claim") },
      { name: "assigned_to", type: "text", label: i18nLabel("Atanan Kullanıcı", "Assigned User"), required: true },
      { name: "status", type: "select", label: i18nLabel("Durum", "Status"), options: [
        option("Open", "Açık", "Open"),
        option("In Progress", "Devam Ediyor", "In Progress"),
        option("Blocked", "Bloke", "Blocked"),
        option("Done", "Tamamlandı", "Done"),
        option("Cancelled", "İptal", "Cancelled"),
      ] },
      { name: "priority", type: "select", label: i18nLabel("Öncelik", "Priority"), options: [
        option("Low", "Düşük", "Low"),
        option("Normal", "Normal", "Normal"),
        option("High", "Yüksek", "High"),
        option("Critical", "Kritik", "Critical"),
      ] },
      { name: "due_date", type: "date", label: i18nLabel("Termin", "Due Date") },
      { name: "reminder_at", type: "datetime-local", label: i18nLabel("Hatırlatma", "Reminder At") },
      { name: "notes", type: "textarea", label: i18nLabel("Not", "Notes"), rows: 3, fullWidth: true },
    ],
  },
  activity: {
    key: "activity",
    title: i18nLabel("Hızlı Aktivite", "Quick Activity"),
    subtitle: i18nLabel("Gerçekleşen operasyon adımını kaydet", "Log a completed operational step"),
    submitUrl: "acentem_takipte.acentem_takipte.api.quick_create.create_quick_activity",
    resultKey: "activity",
    openRouteName: "activities-detail",
    successRefreshTargets: ["activities-list"],
    defaults: {
      activity_title: "",
      activity_type: "Note",
      source_doctype: "AT Customer",
      source_name: "",
      customer: "",
      policy: "",
      claim: "",
      assigned_to: "",
      activity_at: "",
      status: "Logged",
      notes: "",
    },
    fields: [
      { name: "activity_title", type: "text", label: i18nLabel("Aktivite Basligi", "Activity Title"), required: true },
      { name: "activity_type", type: "select", label: i18nLabel("Aktivite Tipi", "Activity Type"), options: [
        option("Call", "Arama", "Call"),
        option("Visit", "Ziyaret", "Visit"),
        option("Note", "Not", "Note"),
        option("Claim Update", "Hasar Güncelleme", "Claim Update"),
        option("Renewal Update", "Yenileme Güncelleme", "Renewal Update"),
        option("Collection", "Tahsilat", "Collection"),
        option("Campaign", "Kampanya", "Campaign"),
        option("Review", "Inceleme", "Review"),
        option("Other", "Diğer", "Other"),
      ] },
      { name: "source_doctype", type: "select", label: i18nLabel("Kaynak Tipi", "Source Type"), options: [
        option("AT Customer", "Müşteri", "Customer"),
        option("AT Policy", "Poliçe", "Policy"),
        option("AT Claim", "Hasar", "Claim"),
        option("AT Task", "Görev", "Task"),
        option("AT Campaign", "Kampanya", "Campaign"),
      ] },
      { name: "source_name", type: "text", label: i18nLabel("Kaynak Kayıt", "Source Record") },
      { name: "customer", type: "select", label: i18nLabel("Müşteri", "Customer"), optionsSource: "customers" },
      { name: "policy", type: "select", label: i18nLabel("Poliçe", "Policy"), optionsSource: "policies" },
      { name: "claim", type: "text", label: i18nLabel("Hasar", "Claim") },
      { name: "assigned_to", type: "text", label: i18nLabel("Atanan Kullanıcı", "Assigned User") },
      { name: "activity_at", type: "datetime-local", label: i18nLabel("Aktivite Zamani", "Activity Time") },
      { name: "status", type: "select", label: i18nLabel("Durum", "Status"), options: [
        option("Logged", "Kaydedildi", "Logged"),
        option("Shared", "Paylaşıldı", "Shared"),
        option("Archived", "Arşivlendi", "Archived"),
      ] },
      { name: "notes", type: "textarea", label: i18nLabel("Not", "Notes"), rows: 3, fullWidth: true },
    ],
  },
  reminder: {
    key: "reminder",
    title: i18nLabel("Hızlı Hatırlatıcı", "Quick Reminder"),
    subtitle: i18nLabel("Zaman bazlı takip kaydı oluştur", "Create a time-based follow-up record"),
    submitUrl: "acentem_takipte.acentem_takipte.api.quick_create.create_quick_reminder",
    resultKey: "reminder",
    openRouteName: "reminders-detail",
    successRefreshTargets: ["reminders-list"],
    defaults: {
      reminder_title: "",
      source_doctype: "AT Customer",
      source_name: "",
      customer: "",
      policy: "",
      claim: "",
      assigned_to: "",
      status: "Open",
      priority: "Normal",
      remind_at: "",
      notes: "",
    },
    fields: [
      { name: "reminder_title", type: "text", label: i18nLabel("Hatırlatıcı Basligi", "Reminder Title"), required: true },
      { name: "source_doctype", type: "select", label: i18nLabel("Kaynak Tipi", "Source Type"), options: [
        option("AT Customer", "Müşteri", "Customer"),
        option("AT Policy", "Poliçe", "Policy"),
        option("AT Claim", "Hasar", "Claim"),
        option("AT Renewal Task", "Yenileme Görevi", "Renewal Task"),
        option("AT Campaign", "Kampanya", "Campaign"),
        option("AT Ownership Assignment", "Atama", "Assignment"),
        option("AT Call Note", "Arama Notu", "Call Note"),
        option("AT Task", "Görev", "Task"),
      ] },
      { name: "source_name", type: "text", label: i18nLabel("Kaynak Kayıt", "Source Record") },
      { name: "customer", type: "select", label: i18nLabel("Müşteri", "Customer"), optionsSource: "customers" },
      { name: "policy", type: "select", label: i18nLabel("Poliçe", "Policy"), optionsSource: "policies" },
      { name: "claim", type: "text", label: i18nLabel("Hasar", "Claim") },
      { name: "assigned_to", type: "text", label: i18nLabel("Atanan Kullanıcı", "Assigned User"), required: true },
      { name: "status", type: "select", label: i18nLabel("Durum", "Status"), options: [
        option("Open", "Açık", "Open"),
        option("Done", "Tamamlandı", "Done"),
        option("Cancelled", "İptal", "Cancelled"),
      ] },
      { name: "priority", type: "select", label: i18nLabel("Öncelik", "Priority"), options: [
        option("Low", "Düşük", "Low"),
        option("Normal", "Normal", "Normal"),
        option("High", "Yüksek", "High"),
        option("Critical", "Kritik", "Critical"),
      ] },
      { name: "remind_at", type: "datetime-local", label: i18nLabel("Hatırlatma Zamani", "Reminder Time"), required: true },
      { name: "notes", type: "textarea", label: i18nLabel("Not", "Notes"), rows: 3, fullWidth: true },
    ],
  },
};

function addQuickEditVariant(baseKey, editKey, trTitle, enTitle, trSubtitle, enSubtitle) {
  const base = quickCreateRegistry[baseKey];
  if (!base) return;
  quickCreateRegistry[editKey] = {
    ...base,
    key: editKey,
    title: i18nLabel(trTitle, enTitle),
    subtitle: i18nLabel(trSubtitle, enSubtitle),
    submitUrl: "acentem_takipte.acentem_takipte.api.quick_create.update_quick_aux_record",
    resultKey: "record",
    openRouteName: "",
    successRefreshTargets: ["aux_detail"],
  };
}

addQuickEditVariant(
  "customer_relation",
  "customer_relation_edit",
  "Müşteri İlişkisini Düzenle",
  "Edit Customer Relation",
  "İlişki alanlarini güncelle",
  "Update relation fields"
);
addQuickEditVariant(
  "insured_asset",
  "insured_asset_edit",
  "Sigortalanan Varlığı Düzenle",
  "Edit Insured Asset",
  "Varlık alanlarini güncelle",
  "Update insured asset fields"
);
addQuickEditVariant(
  "insurance_company",
  "insurance_company_edit",
  "Sigorta Şirketini Düzenle",
  "Edit Insurance Company",
  "Ana veri şirket kaydını güncelle",
  "Update the insurance company master record"
);
addQuickEditVariant(
  "branch_master",
  "branch_master_edit",
  "Branşı Düzenle",
  "Edit Branch",
  "Branş ve şirket eşleşmesini güncelle",
  "Update branch and company mapping"
);
addQuickEditVariant(
  "sales_entity_master",
  "sales_entity_master_edit",
  "Satış Birimini Düzenle",
  "Edit Sales Entity",
  "Satış örgütü kaydını güncelle",
  "Update sales organization record"
);
addQuickEditVariant(
  "call_note",
  "call_note_edit",
  "Arama Notunu Düzenle",
  "Edit Call Note",
  "Arama notu alanlarini güncelle",
  "Update call note fields"
);
addQuickEditVariant(
  "segment",
  "segment_edit",
  "Segmenti Düzenle",
  "Edit Segment",
  "Segment alanlarini güncelle",
  "Update segment fields"
);
addQuickEditVariant(
  "campaign",
  "campaign_edit",
  "Kampanyayı Düzenle",
  "Edit Campaign",
  "Kampanya alanlarini güncelle",
  "Update campaign fields"
);
addQuickEditVariant(
  "ownership_assignment",
  "ownership_assignment_edit",
  "Atamayı Düzenle",
  "Edit Assignment",
  "Atama alanlarini güncelle",
  "Update assignment fields"
);
addQuickEditVariant(
  "task",
  "task_edit",
  "Görevi Düzenle",
  "Edit Task",
  "Görev alanlarini güncelle",
  "Update task fields"
);
addQuickEditVariant(
  "activity",
  "activity_edit",
  "Aktiviteyi Düzenle",
  "Edit Activity",
  "Aktivite alanlarini güncelle",
  "Update activity fields"
);
addQuickEditVariant(
  "reminder",
  "reminder_edit",
  "Hatırlatıcıyı Düzenle",
  "Edit Reminder",
  "Hatırlatıcı alanlarini güncelle",
  "Update reminder fields"
);
addQuickEditVariant(
  "notification_template_master",
  "notification_template_master_edit",
  "Bildirim Şablonunu Düzenle",
  "Edit Notification Template",
  "Şablon alanlarini güncelle",
  "Update notification template fields"
);
addQuickEditVariant(
  "accounting_entry",
  "accounting_entry_edit",
  "Muhasebe Kaydını Düzenle",
  "Edit Accounting Entry",
  "Muhasebe ve mutabakat alanlarini güncelle",
  "Update accounting and reconciliation fields"
);
addQuickEditVariant(
  "reconciliation_item",
  "reconciliation_item_edit",
  "Mutabakat Kalemini Düzenle",
  "Edit Reconciliation Item",
  "Mutabakat fark kaydını güncelle",
  "Update reconciliation mismatch record"
);

export function getQuickCreateConfig(key) {
  return quickCreateRegistry[key] || null;
}

export function buildQuickCreateDraft(config, overrides = {}) {
  if (!config) return {};
  return { ...(config.defaults || {}), ...overrides };
}

export function getLocalizedText(value, locale = "tr") {
  if (value == null) return "";
  if (typeof value === "string") return value;
  if (typeof value === "object") return value[locale] || value.tr || value.en || "";
  return String(value);
}
