import { translateText } from "@/utils/i18n";

function i18nLabel(en) {
  return (context) => {
    const locale =
      typeof context === "string"
        ? context
        : context?.locale;
    return translateText(en, locale || "en");
  };
}

function option(value, label) {
  return { value, label };
}

function hasValue(value) {
  return String(value ?? "").trim() !== "";
}

function isCorporateCustomer(model, fieldName = "customer_type") {
  return String(model?.[fieldName] || "Individual") === "Corporate";
}

export const quickCreateRegistry = {
  offer: {
    key: "offer",
    title: i18nLabel("detailed_quick_offer"),
    subtitle: i18nLabel("create_a_draft_offer_with_customer,_product_and_financial_fields"),
    submitUrl: "acentem_takipte.doctype.at_offer.at_offer.create_quick_offer",
    resultKey: "offer",
    openRouteName: "offer-detail",
    successRefreshTargets: ["offer_list", "offer_board"],
    defaults: {
      customer_type: "Individual",
      tax_id: "",
      phone: "",
      email: "",
      branch: "",
      insurance_company: "",
      sales_entity: "",
      offer_date: "",
      valid_until: "",
      currency: "TRY",
      status: "Draft",
      gross_premium: "",
      net_premium: "",
      tax_amount: "0",
      commission_amount: "0",
      notes: "",
    },
    fields: [
      { name: "sales_entity", type: "select", label: i18nLabel("sales_entity"), optionsSource: "salesEntities", fullWidth: false },
      { name: "insurance_company", type: "select", label: i18nLabel("insurance_company"), optionsSource: "insuranceCompanies", fullWidth: false },
      { name: "branch", type: "select", label: i18nLabel("branch"), optionsSource: "branches", fullWidth: false },
      {
        name: "customer_type",
        type: "select",
        label: i18nLabel("customer_type"),
        required: ({ model }) => !hasValue(model?.customerOption?.value) && hasValue(model?.queryText),
        disabled: ({ model }) => hasValue(model?.customerOption?.value),
        options: [
          option("Individual", "Individual"),
          option("Corporate", "Corporate"),
        ],
        fullWidth: false,
      },
      {
        name: "tax_id",
        type: "text",
        required: ({ model }) => !hasValue(model?.customerOption?.value) && hasValue(model?.queryText),
        disabled: ({ model }) => hasValue(model?.customerOption?.value),
        label: ({ model, locale }) =>
          isCorporateCustomer(model)
            ? translateText("Tax Number", locale)
            : translateText("National ID Number", locale),
        help: ({ model, locale }) =>
          isCorporateCustomer(model)
            ? translateText("Enter a 10-digit tax number.", locale)
            : translateText("Enter an 11-digit Turkish national ID number.", locale),
        fullWidth: false,
      },
      { name: "phone", type: "text", label: i18nLabel("phone"), disabled: ({ model }) => hasValue(model?.customerOption?.value), fullWidth: false },
      { name: "email", type: "email", label: i18nLabel("email"), disabled: ({ model }) => hasValue(model?.customerOption?.value), fullWidth: false },
      { name: "status", type: "select", label: i18nLabel("status"), options: [
        option("Draft", "Draft"),
        option("Sent", "Sent"),
        option("Accepted", "Accepted"),
        option("Rejected", "Rejected"),
      ], fullWidth: false },
      { name: "offer_date", type: "date", label: i18nLabel("offer_date"), fullWidth: false },
      { name: "valid_until", type: "date", label: i18nLabel("valid_until"), fullWidth: false },
      { name: "currency", type: "select", label: i18nLabel("currency"), options: [option("TRY", "TRY"), option("USD", "USD"), option("EUR", "EUR")], fullWidth: false },
      { name: "gross_premium", type: "number", label: i18nLabel("gross_premium"), min: 0, step: "0.01", fullWidth: false },
      { name: "net_premium", type: "number", label: i18nLabel("net_premium"), min: 0, step: "0.01", fullWidth: false },
      { name: "tax_amount", type: "number", label: i18nLabel("tax_amount"), min: 0, step: "0.01", fullWidth: false },
      { name: "commission_amount", type: "number", label: i18nLabel("commission_amount"), min: 0, step: "0.01", fullWidth: false },
      { name: "notes", type: "textarea", label: i18nLabel("notes"), rows: 3, fullWidth: true },
    ],
  },
  policy: {
    key: "policy",
    title: i18nLabel("quick_policy_entry"),
    subtitle: i18nLabel("create_a_policy_with_an_auto-generated_record_number_and_an_optional_carrier_policy_number"),
    submitUrl: "acentem_takipte.acentem_takipte.api.quick_create.create_quick_policy",
    resultKey: "policy",
    openRouteName: "policy-detail",
    successRefreshTargets: ["policy_list"],
    defaults: {
      customer: "",
      customer_full_name: "",
      customer_type: "Individual",
      customer_tax_id: "",
      customer_phone: "",
      customer_email: "",
      customer_birth_date: "",
      sales_entity: "",
      insurance_company: "",
      branch: "",
      policy_no: "",
      source_offer: "",
      status: "Active",
      issue_date: "",
      start_date: "",
      end_date: "",
      currency: "TRY",
      gross_premium: "",
      net_premium: "",
      tax_amount: "0",
      commission_amount: "0",
      notes: "",
    },
    fields: [
      {
        name: "customer",
        type: "select",
        label: i18nLabel("customer"),
        optionsSource: "customers",
        disabled: ({ model }) => hasValue(model?.source_offer),
      },
      {
        name: "customer_full_name",
        type: "text",
        label: i18nLabel("new_customer_name"),
        required: ({ model }) => !hasValue(model?.customer) && !hasValue(model?.source_offer),
        disabled: ({ model }) => hasValue(model?.customer) || hasValue(model?.source_offer),
      },
      {
        name: "customer_type",
        type: "select",
        label: i18nLabel("customer_type"),
        required: ({ model }) => !hasValue(model?.customer) && !hasValue(model?.source_offer),
        disabled: ({ model }) => hasValue(model?.customer) || hasValue(model?.source_offer),
        options: [
          option("Individual", "Individual"),
          option("Corporate", "Corporate"),
        ],
      },
      {
        name: "customer_tax_id",
        type: "text",
        required: ({ model }) => !hasValue(model?.customer) && !hasValue(model?.source_offer),
        disabled: ({ model }) => hasValue(model?.customer) || hasValue(model?.source_offer),
        label: ({ model, locale }) =>
          isCorporateCustomer(model)
            ? translateText("Tax Number", locale)
            : translateText("National ID Number", locale),
        help: ({ model, locale }) =>
          isCorporateCustomer(model)
            ? translateText("Enter a 10-digit tax number.", locale)
            : translateText("Enter an 11-digit Turkish national ID number.", locale),
      },
      {
        name: "customer_phone",
        type: "text",
        label: i18nLabel("phone"),
        disabled: ({ model }) => hasValue(model?.customer) || hasValue(model?.source_offer),
      },
      {
        name: "customer_email",
        type: "email",
        label: i18nLabel("email"),
        disabled: ({ model }) => hasValue(model?.customer) || hasValue(model?.source_offer),
      },
      {
        name: "sales_entity",
        type: "select",
        label: i18nLabel("sales_entity"),
        optionsSource: "salesEntities",
        required: ({ model }) => !hasValue(model?.source_offer),
        disabled: ({ model }) => hasValue(model?.source_offer),
      },
      {
        name: "insurance_company",
        type: "select",
        label: i18nLabel("insurance_company"),
        optionsSource: "insuranceCompanies",
        required: ({ model }) => !hasValue(model?.source_offer),
        disabled: ({ model }) => hasValue(model?.source_offer),
      },
      {
        name: "branch",
        type: "select",
        label: i18nLabel("branch"),
        optionsSource: "branches",
        required: ({ model }) => !hasValue(model?.source_offer),
        disabled: ({ model }) => hasValue(model?.source_offer),
      },
      { name: "policy_no", type: "text", label: i18nLabel("carrier_policy_no") },
      { name: "source_offer", type: "select", label: i18nLabel("source_offer"), optionsSource: "offers" },
      {
        name: "status",
        type: "select",
        label: i18nLabel("status"),
        required: ({ model }) => !hasValue(model?.source_offer),
        disabled: ({ model }) => hasValue(model?.source_offer),
        options: [
          option("Active", "Active"),
          option("KYT", "KYT"),
          option("IPT", "IPT"),
        ],
      },
      {
        name: "issue_date",
        type: "date",
        label: i18nLabel("issue_date"),
        required: ({ model }) => !hasValue(model?.source_offer),
        disabled: ({ model }) => hasValue(model?.source_offer),
      },
      {
        name: "start_date",
        type: "date",
        label: i18nLabel("start_date"),
        required: ({ model }) => !hasValue(model?.source_offer),
      },
      {
        name: "end_date",
        type: "date",
        label: i18nLabel("end_date"),
        required: ({ model }) => !hasValue(model?.source_offer),
      },
      {
        name: "currency",
        type: "select",
        label: i18nLabel("currency"),
        required: ({ model }) => !hasValue(model?.source_offer),
        disabled: ({ model }) => hasValue(model?.source_offer),
        options: [option("TRY", "TRY"), option("USD", "USD"), option("EUR", "EUR")],
      },
      { name: "gross_premium", type: "number", label: i18nLabel("gross_premium"), required: true, min: 0, step: "0.01" },
      { name: "net_premium", type: "number", label: i18nLabel("net_premium"), min: 0, step: "0.01" },
      { name: "tax_amount", type: "number", label: i18nLabel("tax_amount"), min: 0, step: "0.01" },
      { name: "commission_amount", type: "number", label: i18nLabel("commission_amount"), min: 0, step: "0.01" },
      { name: "commission_rate", type: "number", label: i18nLabel("commission_rate"), disabled: true },
      { name: "notes", type: "textarea", label: i18nLabel("notes"), rows: 2, fullWidth: true },
    ],
  },
  lead: {
    key: "lead",
    title: i18nLabel("quick_lead"),
    subtitle: i18nLabel("create_a_lead_with_sales_and_potential_details"),
    submitUrl: "acentem_takipte.acentem_takipte.api.quick_create.create_quick_lead",
    resultKey: "lead",
    openRouteName: "lead-detail",
    successRefreshTargets: ["lead_list"],
    defaults: {
      first_name: "",
      last_name: "",
      customer_type: "Individual",
      phone: "",
      tax_id: "",
      email: "",
      status: "Open",
      customer: "",
      sales_entity: "",
      insurance_company: "",
      branch: "",
      estimated_gross_premium: "",
      notes: "",
    },
    fields: [
      { name: "first_name", type: "text", label: i18nLabel("first_name"), required: true },
      { name: "last_name", type: "text", label: i18nLabel("last_name") },
      {
        name: "customer_type",
        type: "select",
        label: i18nLabel("customer_type"),
        options: [
          option("Individual", "Individual"),
          option("Corporate", "Corporate"),
        ],
      },
      { name: "phone", type: "text", label: i18nLabel("phone") },
      {
        name: "tax_id",
        type: "text",
        label: ({ model, locale }) =>
          isCorporateCustomer(model)
            ? translateText("Tax Number", locale)
            : translateText("National ID Number", locale),
        help: ({ model, locale }) =>
          isCorporateCustomer(model)
            ? translateText("Enter a 10-digit tax number.", locale)
            : translateText("Enter an 11-digit Turkish national ID number.", locale),
      },
      { name: "email", type: "email", label: i18nLabel("email") },
      { name: "status", type: "select", label: i18nLabel("lead_status"), options: [
        option("Draft", "Draft"),
        option("Open", "Open"),
      ] },
      { name: "customer", type: "select", label: i18nLabel("customer_(optional)"), optionsSource: "customers" },
      { name: "sales_entity", type: "select", label: i18nLabel("sales_entity"), optionsSource: "salesEntities" },
      { name: "insurance_company", type: "select", label: i18nLabel("insurance_company"), optionsSource: "insuranceCompanies" },
      { name: "branch", type: "select", label: i18nLabel("Branch"), optionsSource: "branches" },
      { name: "estimated_gross_premium", type: "number", label: i18nLabel("estimated_gross_premium"), min: 0, step: "0.01" },
      { name: "notes", type: "textarea", label: i18nLabel("notes"), rows: 3, fullWidth: true },
    ],
  },
  customer: {
    key: "customer",
    title: i18nLabel("quick_customer"),
    subtitle: i18nLabel("create_a_customer_with_insured_profile_fields"),
    submitUrl: "acentem_takipte.acentem_takipte.api.quick_create.create_quick_customer",
    resultKey: "customer",
    openRouteName: "customer-detail",
    successRefreshTargets: ["customer_list"],
    defaults: {
      full_name: "",
      tax_id: "",
      phone: "",
      email: "",
      address: "",
      birth_date: "",
      gender: "Unknown",
      marital_status: "Unknown",
      occupation: "",
      consent_status: "Unknown",
      assigned_agent: "",
    },
    fields: [
      { name: "full_name", type: "text", label: i18nLabel("full_name"), required: true, fullWidth: true },
      { name: "tax_id", type: "text", label: i18nLabel("tax_id"), required: true },
      { name: "birth_date", type: "date", label: i18nLabel("birth_date") },
      { name: "phone", type: "text", label: i18nLabel("phone") },
      { name: "email", type: "email", label: i18nLabel("email") },
      { name: "gender", type: "select", label: i18nLabel("Gender"), options: [
        option("Unknown", "Unknown"),
        option("Male", "Male"),
        option("Female", "Female"),
        option("Other", "Other"),
      ] },
      { name: "marital_status", type: "select", label: i18nLabel("marital_status"), options: [
        option("Unknown", "Unknown"),
        option("Single", "Single"),
        option("Married", "Married"),
        option("Divorced", "Divorced"),
        option("Widowed", "Widowed"),
      ] },
      { name: "consent_status", type: "select", label: i18nLabel("consent_status"), options: [
        option("Unknown", "Unknown"),
        option("Granted", "Granted"),
        option("Revoked", "Revoked"),
      ] },
      { name: "assigned_agent", type: "text", label: i18nLabel("assigned_agent_(user)") },
      { name: "occupation", type: "text", label: i18nLabel("Occupation"), fullWidth: true },
      { name: "address", type: "textarea", label: i18nLabel("Address"), rows: 3, fullWidth: true },
    ],
  },
  claim: {
    key: "claim",
    title: i18nLabel("quick_claim"),
    subtitle: i18nLabel("create_a_claim_linked_to_a_policy"),
    submitUrl: "acentem_takipte.acentem_takipte.api.quick_create.create_quick_claim",
    resultKey: "claim",
    successRefreshTargets: ["claim_list"],
    defaults: {
      policy: "",
      customer: "",
      claim_no: "",
      claim_type: "Damage",
      claim_status: "Open",
      incident_date: "",
      reported_date: "",
      currency: "TRY",
      estimated_amount: "",
      approved_amount: "",
      notes: "",
    },
    fields: [
      { name: "policy", type: "select", label: i18nLabel("Policy"), optionsSource: "policies", required: true },
      { name: "customer", type: "select", label: i18nLabel("customer"), optionsSource: "customers", required: true },
      { name: "claim_no", type: "text", label: i18nLabel("claim_number") },
      { name: "claim_type", type: "select", label: i18nLabel("claim_type"), options: [
        option("Damage", "Damage"),
        option("Health", "Health"),
        option("Theft", "Theft"),
        option("Liability", "Liability"),
        option("Other", "Other"),
      ] },
      { name: "claim_status", type: "select", label: i18nLabel("status"), options: [
        option("Draft", "Draft"),
        option("Open", "Open"),
        option("Under Review", "Under Review"),
        option("Approved", "Approved"),
        option("Rejected", "Rejected"),
      ] },
      { name: "incident_date", type: "date", label: i18nLabel("incident_date"), required: true },
      { name: "reported_date", type: "date", label: i18nLabel("reported_date"), required: true },
      { name: "currency", type: "select", label: i18nLabel("currency"), options: [option("TRY", "TRY"), option("USD", "USD"), option("EUR", "EUR")] },
      { name: "estimated_amount", type: "number", label: i18nLabel("estimated_amount"), min: 0, step: "0.01" },
      { name: "approved_amount", type: "number", label: i18nLabel("approved_amount"), min: 0, step: "0.01" },
      { name: "notes", type: "textarea", label: i18nLabel("notes"), rows: 3, fullWidth: true },
    ],
  },
  payment: {
    key: "payment",
    title: i18nLabel("quick_payment"),
    subtitle: i18nLabel("create_an_inbound_or_outbound_payment_record"),
    submitUrl: "acentem_takipte.acentem_takipte.api.quick_create.create_quick_payment",
    resultKey: "payment",
    successRefreshTargets: ["payment_list"],
    defaults: {
      customer: "",
      policy: "",
      claim: "",
      sales_entity: "",
      payment_direction: "Inbound",
      payment_purpose: "Premium Collection",
      status: "Draft",
      payment_date: "",
      due_date: "",
      installment_count: "1",
      installment_interval_days: "30",
      currency: "TRY",
      amount: "",
      reference_no: "",
      notes: "",
    },
    fields: [
      { name: "payment_direction", type: "select", label: i18nLabel("Direction"), options: [
        option("Inbound", "Inbound"),
        option("Outbound", "Outbound"),
      ] },
      { name: "payment_purpose", type: "select", label: i18nLabel("Purpose"), options: [
        option("Premium Collection", "Premium Collection"),
        option("Commission Payout", "Commission Payout"),
        option("Claim Payout", "Claim Payout"),
        option("Other", "Other"),
      ] },
      { name: "customer", type: "select", label: i18nLabel("customer"), optionsSource: "customers", required: true },
      { name: "policy", type: "select", label: i18nLabel("Policy"), optionsSource: "policies" },
      { name: "claim", type: "select", label: i18nLabel("Claim"), optionsSource: "claims" },
      { name: "sales_entity", type: "select", label: i18nLabel("sales_entity"), optionsSource: "salesEntities" },
      { name: "status", type: "select", label: i18nLabel("status"), options: [
        option("Draft", "Draft"),
        option("Paid", "Paid"),
        option("Cancelled", "Cancelled"),
      ] },
      { name: "payment_date", type: "date", label: i18nLabel("payment_date"), required: true },
      { name: "due_date", type: "date", label: i18nLabel("due_date") },
      { name: "installment_count", type: "number", label: i18nLabel("installment_count"), min: 1, step: "1" },
      { name: "installment_interval_days", type: "number", label: i18nLabel("installment_interval_(days)"), min: 1, step: "1" },
      { name: "currency", type: "select", label: i18nLabel("currency"), options: [option("TRY", "TRY"), option("USD", "USD"), option("EUR", "EUR")] },
      { name: "amount", type: "number", label: i18nLabel("Amount"), required: true, min: 0.01, step: "0.01" },
      { name: "reference_no", type: "text", label: i18nLabel("external_reference") },
      { name: "notes", type: "textarea", label: i18nLabel("notes"), rows: 3, fullWidth: true },
    ],
  },
  renewal_task: {
    key: "renewal_task",
    title: i18nLabel("quick_renewal_task"),
    subtitle: i18nLabel("create_a_policy_renewal_follow-up_task"),
    submitUrl: "acentem_takipte.acentem_takipte.api.quick_create.create_quick_renewal_task",
    resultKey: "renewal_task",
    openRouteName: "tasks-detail",
    successRefreshTargets: ["renewal_list"],
    defaults: {
      policy: "",
      customer: "",
      renewal_date: "",
      due_date: "",
      status: "Open",
      lost_reason_code: "",
      competitor_name: "",
      assigned_to: "",
      notes: "",
      auto_created: false,
    },
    fields: [
      { name: "policy", type: "select", label: i18nLabel("Policy"), optionsSource: "policies", required: true },
      { name: "customer", type: "select", label: i18nLabel("customer"), optionsSource: "customers", required: true },
      { name: "renewal_date", type: "date", label: i18nLabel("renewal_date"), required: true },
      { name: "due_date", type: "date", label: i18nLabel("due_date"), required: true },
      { name: "status", type: "select", label: i18nLabel("status"), options: [
        option("Open", "Open"),
        option("In Progress", "In Progress"),
        option("Done", "Done"),
        option("Cancelled", "Cancelled"),
      ] },
      { name: "lost_reason_code", type: "select", label: i18nLabel("lost_reason"), options: [
        option("", "Blank"),
        option("Price", "Price"),
        option("Competitor", "Competitor"),
        option("Service", "Service"),
        option("Customer Declined", "Customer Declined"),
        option("Coverage Mismatch", "Coverage Mismatch"),
        option("Other", "Other"),
      ] },
      { name: "competitor_name", type: "text", label: i18nLabel("competitor_name"), fullWidth: true },
      { name: "assigned_to", type: "text", label: i18nLabel("assigned_to_(user)") },
      { name: "auto_created", type: "checkbox", label: i18nLabel("auto_created") },
      { name: "notes", type: "textarea", label: i18nLabel("notes"), rows: 3, fullWidth: true },
    ],
  },
  customer_relation: {
    key: "customer_relation",
    title: i18nLabel("quick_customer_relation"),
    subtitle: i18nLabel("create_a_relationship_between_customers"),
    submitUrl: "acentem_takipte.acentem_takipte.api.quick_create.create_quick_customer_relation",
    resultKey: "customer_relation",
    openRouteName: "customer-relations-detail",
    successRefreshTargets: ["customer-relations-list"],
    defaults: {
      customer: "",
      related_customer: "",
      relation_type: "Other",
      is_household: false,
      notes: "",
    },
    fields: [
      { name: "customer", type: "select", label: i18nLabel("customer"), optionsSource: "customers", required: true },
      { name: "related_customer", type: "select", label: i18nLabel("related_customer"), optionsSource: "customers", required: true },
      { name: "relation_type", type: "select", label: i18nLabel("relation_type"), options: [
        option("Spouse", "Spouse"),
        option("Child", "Child"),
        option("Parent", "Parent"),
        option("Sibling", "Sibling"),
        option("Partner", "Partner"),
        option("Household", "Household"),
        option("Other", "Other"),
      ] },
      { name: "is_household", type: "checkbox", label: i18nLabel("same_household") },
      { name: "notes", type: "textarea", label: i18nLabel("notes"), rows: 3, fullWidth: true },
    ],
  },
  insured_asset: {
    key: "insured_asset",
    title: i18nLabel("quick_insured_asset"),
    subtitle: i18nLabel("create_an_insured_asset_linked_to_a_customer"),
    submitUrl: "acentem_takipte.acentem_takipte.api.quick_create.create_quick_insured_asset",
    resultKey: "insured_asset",
    openRouteName: "insured-assets-detail",
    successRefreshTargets: ["insured-assets-list"],
    defaults: {
      customer: "",
      policy: "",
      asset_type: "Other",
      asset_label: "",
      asset_identifier: "",
      notes: "",
    },
    fields: [
      { name: "customer", type: "select", label: i18nLabel("customer"), optionsSource: "customers", required: true },
      { name: "policy", type: "select", label: i18nLabel("Policy"), optionsSource: "policies" },
      { name: "asset_type", type: "select", label: i18nLabel("asset_type"), options: [
        option("Vehicle", "Vehicle"),
        option("Home", "Home"),
        option("Health Person", "Health Person"),
        option("Workplace", "Workplace"),
        option("Travel", "Travel"),
        option("Boat", "Boat"),
        option("Farm", "Farm"),
        option("Other", "Other"),
      ] },
      { name: "asset_label", type: "text", label: i18nLabel("asset_label"), required: true, fullWidth: true },
      { name: "asset_identifier", type: "text", label: i18nLabel("asset_identifier"), fullWidth: true },
      { name: "notes", type: "textarea", label: i18nLabel("notes"), rows: 3, fullWidth: true },
    ],
  },
  call_note: {
    key: "call_note",
    title: i18nLabel("quick_call_note"),
    subtitle: i18nLabel("create_a_phone_interaction_record"),
    submitUrl: "acentem_takipte.acentem_takipte.api.quick_create.create_quick_call_note",
    resultKey: "call_note",
    openRouteName: "call-notes-detail",
    successRefreshTargets: ["call-notes-list"],
    defaults: {
      customer: "",
      policy: "",
      claim: "",
      channel: "Phone Call",
      direction: "Outbound",
      call_status: "Completed",
      call_outcome: "",
      note_at: "",
      next_follow_up_on: "",
      notes: "",
    },
    fields: [
      { name: "customer", type: "select", label: i18nLabel("customer"), optionsSource: "customers", required: true },
      { name: "policy", type: "select", label: i18nLabel("Policy"), optionsSource: "policies" },
      { name: "claim", type: "select", label: i18nLabel("Claim"), optionsSource: "claims" },
      { name: "channel", type: "select", label: i18nLabel("Channel"), options: [
        option("Phone Call", "Phone Call"),
        option("WhatsApp Call", "WhatsApp Call"),
        option("Video Call", "Video Call"),
        option("Other", "Other"),
      ] },
      { name: "direction", type: "select", label: i18nLabel("Direction"), options: [
        option("Inbound", "Inbound"),
        option("Outbound", "Outbound"),
      ] },
      { name: "call_status", type: "select", label: i18nLabel("call_status"), options: [
        option("Planned", "Planned"),
        option("Completed", "Completed"),
        option("Missed", "Missed"),
        option("No Answer", "No Answer"),
        option("Cancelled", "Cancelled"),
      ] },
      { name: "call_outcome", type: "text", label: i18nLabel("call_outcome"), fullWidth: true },
      { name: "note_at", type: "datetime", label: i18nLabel("note_at"), required: true },
      { name: "next_follow_up_on", type: "date", label: i18nLabel("next_follow_up") },
      { name: "notes", type: "textarea", label: i18nLabel("notes"), rows: 3, fullWidth: true },
    ],
  },
  segment: {
    key: "segment",
    title: i18nLabel("quick_segment"),
    subtitle: i18nLabel("create_a_campaign_target_segment"),
    submitUrl: "acentem_takipte.acentem_takipte.api.quick_create.create_quick_segment",
    resultKey: "segment",
    openRouteName: "segments-detail",
    successRefreshTargets: ["segments-list"],
    defaults: {
      segment_name: "",
      segment_type: "Static",
      channel_focus: "WHATSAPP",
      status: "Draft",
      criteria_json: "",
      notes: "",
    },
    fields: [
      { name: "segment_name", type: "text", label: i18nLabel("segment_name"), required: true, fullWidth: true },
      { name: "segment_type", type: "select", label: i18nLabel("segment_type"), options: [
        option("Static", "Static"),
        option("Dynamic", "Dynamic"),
        option("Operational", "Operational"),
      ] },
      { name: "channel_focus", type: "select", label: i18nLabel("channel_focus"), options: [
        option("WHATSAPP", "WhatsApp"),
        option("SMS", "SMS"),
        option("Email", "Email"),
        option("Phone Call", "Phone Call"),
      ] },
      { name: "status", type: "select", label: i18nLabel("status"), options: [
        option("Draft", "Draft"),
        option("Active", "Active"),
        option("Archived", "Archived"),
      ] },
      { name: "criteria_json", type: "textarea", label: i18nLabel("criteria_json"), rows: 4, fullWidth: true },
      { name: "notes", type: "textarea", label: i18nLabel("notes"), rows: 3, fullWidth: true },
    ],
  },
  campaign: {
    key: "campaign",
    title: i18nLabel("quick_campaign"),
    subtitle: i18nLabel("create_a_segment-based_campaign"),
    submitUrl: "acentem_takipte.acentem_takipte.api.quick_create.create_quick_campaign",
    resultKey: "campaign",
    openRouteName: "campaigns-detail",
    successRefreshTargets: ["campaigns-list"],
    defaults: {
      campaign_name: "",
      segment: "",
      template: "",
      channel: "WHATSAPP",
      status: "Draft",
      scheduled_for: "",
      notes: "",
    },
    fields: [
      { name: "campaign_name", type: "text", label: i18nLabel("campaign_name"), required: true, fullWidth: true },
      { name: "segment", type: "select", label: i18nLabel("Segment"), optionsSource: "segments", required: true },
      { name: "template", type: "select", label: i18nLabel("Template"), optionsSource: "notificationTemplates" },
      { name: "channel", type: "select", label: i18nLabel("Channel"), options: [
        option("WHATSAPP", "WhatsApp"),
        option("SMS", "SMS"),
        option("Email", "Email"),
        option("Phone Call", "Phone Call"),
      ] },
      { name: "status", type: "select", label: i18nLabel("status"), options: [
        option("Draft", "Draft"),
        option("Planned", "Planned"),
        option("Running", "Running"),
        option("Completed", "Completed"),
        option("Cancelled", "Cancelled"),
      ] },
      { name: "scheduled_for", type: "datetime", label: i18nLabel("scheduled_for") },
      { name: "notes", type: "textarea", label: i18nLabel("notes"), rows: 3, fullWidth: true },
    ],
  },
  notification_draft: {
    key: "notification_draft",
    title: i18nLabel("quick_notification_draft"),
    subtitle: i18nLabel("create_a_template-based_notification_draft"),
    submitUrl: "acentem_takipte.acentem_takipte.api.communication.create_quick_notification_draft",
    resultKey: "draft",
    openRouteName: "notification-drafts-detail",
    successRefreshTargets: ["notification_draft_list", "aux_list", "communication_snapshot"],
    defaults: {
      template: "",
      channel: "",
      language: "en",
      customer: "",
      recipient: "",
      reference_doctype: "",
      reference_name: "",
      subject: "",
      body: "",
      status: "Draft",
    },
    fields: [
      { name: "template", type: "select", label: i18nLabel("Template"), optionsSource: "notificationTemplates", required: true },
      {
        name: "channel",
        type: "select",
        label: i18nLabel("Channel"),
        options: [option("", "Template Channel"), option("SMS", "SMS"), option("Email", "Email"), option("WHATSAPP", "WhatsApp")],
      },
      { name: "language", type: "select", label: i18nLabel("Language"), options: [option("tr", "Turkish"), option("en", "English")] },
      { name: "customer", type: "select", label: i18nLabel("customer"), optionsSource: "customers" },
      { name: "recipient", type: "text", label: i18nLabel("Recipient"), required: true },
      {
        name: "reference_doctype",
        type: "select",
        label: i18nLabel("reference_type"),
        options: [
          option("", "None"),
          option("AT Lead", "Lead"),
          option("AT Offer", "Offer"),
          option("AT Policy", "Policy"),
          option("AT Customer", "Customer"),
          option("AT Claim", "Claim"),
          option("AT Payment", "Payment"),
          option("AT Renewal Task", "Renewal Task"),
        ],
      },
      { name: "reference_name", type: "text", label: i18nLabel("reference_record") },
      { name: "status", type: "select", label: i18nLabel("status"), options: [
        option("Draft", "Draft"),
        option("Queued", "Queued"),
      ] },
      { name: "subject", type: "text", label: i18nLabel("Subject"), fullWidth: true },
      { name: "body", type: "textarea", label: i18nLabel("Message"), rows: 4, fullWidth: true },
    ],
  },
  communication_message: {
    key: "communication_message",
    title: i18nLabel("quick_communication"),
    subtitle: i18nLabel("save_as_draft_or_send_immediately"),
    submitUrl: "acentem_takipte.acentem_takipte.api.communication.create_quick_notification_draft",
    resultKey: "draft",
    successRefreshTargets: ["communication_snapshot", "notification_draft_list"],
    defaults: {
      template: "",
      channel: "",
      language: "en",
      customer: "",
      recipient: "",
      reference_doctype: "",
      reference_name: "",
      subject: "",
      body: "",
    },
    fields: [
      { name: "template", type: "select", label: i18nLabel("Template"), optionsSource: "notificationTemplates", required: true },
      {
        name: "channel",
        type: "select",
        label: i18nLabel("Channel"),
        options: [option("", "Template Channel"), option("SMS", "SMS"), option("Email", "Email"), option("WHATSAPP", "WhatsApp")],
      },
      { name: "language", type: "select", label: i18nLabel("Language"), options: [option("tr", "Turkish"), option("en", "English")] },
      { name: "customer", type: "select", label: i18nLabel("customer"), optionsSource: "customers" },
      { name: "recipient", type: "text", label: i18nLabel("Recipient"), required: true },
      {
        name: "reference_doctype",
        type: "select",
        label: i18nLabel("reference_type"),
        options: [
          option("", "None"),
          option("AT Lead", "Lead"),
          option("AT Offer", "Offer"),
          option("AT Policy", "Policy"),
          option("AT Customer", "Customer"),
          option("AT Claim", "Claim"),
          option("AT Payment", "Payment"),
          option("AT Renewal Task", "Renewal Task"),
        ],
      },
      { name: "reference_name", type: "text", label: i18nLabel("reference_record") },
      { name: "subject", type: "text", label: i18nLabel("subject_(email)"), fullWidth: true },
      { name: "body", type: "textarea", label: i18nLabel("Message"), rows: 4, fullWidth: true },
    ],
  },
  insurance_company: {
    key: "insurance_company",
    title: i18nLabel("quick_insurance_company"),
    subtitle: i18nLabel("create_an_insurance_company_master_record"),
    submitUrl: "acentem_takipte.acentem_takipte.api.quick_create.create_quick_insurance_company",
    resultKey: "company",
    openRouteName: "companies-detail",
    successRefreshTargets: ["aux_list"],
    defaults: { company_name: "", company_code: "", is_active: true },
    fields: [
      { name: "company_name", type: "text", label: i18nLabel("company_name"), required: true, fullWidth: true },
      { name: "company_code", type: "text", label: i18nLabel("company_code") },
      { name: "is_active", type: "checkbox", label: i18nLabel("Active"), checkboxLabel: i18nLabel("active_company") },
    ],
  },
  branch_master: {
    key: "branch_master",
    title: i18nLabel("quick_branch"),
    subtitle: i18nLabel("create_a_branch_and_company_mapping"),
    submitUrl: "acentem_takipte.acentem_takipte.api.quick_create.create_quick_branch",
    resultKey: "branch",
    openRouteName: "branches-detail",
    successRefreshTargets: ["aux_list"],
    defaults: { branch_name: "", branch_code: "", insurance_company: "", is_active: true },
    fields: [
      { name: "branch_name", type: "text", label: i18nLabel("branch_name"), required: true, fullWidth: true },
      { name: "branch_code", type: "text", label: i18nLabel("branch_code") },
      { name: "insurance_company", type: "select", label: i18nLabel("insurance_company"), optionsSource: "insuranceCompanies" },
      { name: "is_active", type: "checkbox", label: i18nLabel("Active"), checkboxLabel: i18nLabel("active_branch") },
    ],
  },
  sales_entity_master: {
    key: "sales_entity_master",
    title: i18nLabel("quick_sales_entity"),
    subtitle: i18nLabel("create_a_sales_organization_record"),
    submitUrl: "acentem_takipte.acentem_takipte.api.quick_create.create_quick_sales_entity",
    resultKey: "sales_entity",
    openRouteName: "sales-entities-detail",
    successRefreshTargets: ["aux_list"],
    defaults: { entity_type: "Agency", full_name: "", office_branch: "", parent_entity: "" },
    fields: [
      { name: "entity_type", type: "select", label: i18nLabel("entity_type"), required: true, options: [
        option("Agency", "Agency"),
        option("Sub-Account", "Sub-Account"),
        option("Representative", "Representative"),
      ] },
      { name: "full_name", type: "text", label: i18nLabel("full_name"), required: true, fullWidth: true },
      { name: "office_branch", type: "select", label: i18nLabel("office_branch"), required: true, optionsSource: "officeBranches" },
      { name: "parent_entity", type: "select", label: i18nLabel("parent_entity"), optionsSource: "salesEntities" },
    ],
  },
  notification_template_master: {
    key: "notification_template_master",
    title: i18nLabel("quick_notification_template"),
    subtitle: i18nLabel("create_a_channel_and_language_template"),
    submitUrl: "acentem_takipte.acentem_takipte.api.quick_create.create_quick_notification_template",
    resultKey: "template",
    openRouteName: "templates-detail",
    successRefreshTargets: ["aux_list"],
    defaults: {
      template_key: "",
      event_key: "",
      channel: "WHATSAPP",
      language: "en",
      content_mode: "template",
      provider_template_name: "",
      provider_template_category: "",
      variables_schema_json: "",
      subject: "",
      body_template: "",
      sms_body_template: "",
      email_body_template: "",
      whatsapp_body_template: "",
      is_active: true,
    },
    fields: [
      { name: "template_key", type: "text", label: i18nLabel("template_key"), required: true },
      { name: "event_key", type: "text", label: i18nLabel("event_key"), required: true },
      { name: "channel", type: "select", label: i18nLabel("Channel"), required: true, options: [option("SMS", "SMS"), option("Email", "Email"), option("WHATSAPP", "WhatsApp"), option("Both", "Both")] },
      { name: "language", type: "select", label: i18nLabel("Language"), required: true, options: [option("tr", "Turkish"), option("en", "English")] },
      { name: "content_mode", type: "select", label: i18nLabel("content_mode"), required: true, options: [option("freeform", "Freeform"), option("template", "Provider Template")] },
      { name: "provider_template_name", type: "text", label: i18nLabel("provider_template_name"), fullWidth: true },
      { name: "provider_template_category", type: "text", label: i18nLabel("provider_category") },
      { name: "variables_schema_json", type: "textarea", label: i18nLabel("variables_schema_json"), rows: 3, fullWidth: true },
      { name: "subject", type: "text", label: i18nLabel("Subject"), fullWidth: true },
      { name: "body_template", type: "textarea", label: i18nLabel("body_template"), required: true, rows: 5, fullWidth: true },
      { name: "sms_body_template", type: "textarea", label: i18nLabel("sms_body"), rows: 3, fullWidth: true },
      { name: "email_body_template", type: "textarea", label: i18nLabel("email_body"), rows: 3, fullWidth: true },
      { name: "whatsapp_body_template", type: "textarea", label: i18nLabel("whatsapp_body"), rows: 3, fullWidth: true },
      { name: "is_active", type: "checkbox", label: i18nLabel("Active"), checkboxLabel: i18nLabel("active_template") },
    ],
  },
  accounting_entry: {
    key: "accounting_entry",
    title: i18nLabel("quick_accounting_entry"),
    subtitle: i18nLabel("create_an_accounting_entry_for_reconciliation_workflows"),
    submitUrl: "acentem_takipte.acentem_takipte.api.quick_create.create_quick_accounting_entry",
    resultKey: "accounting_entry",
    openRouteName: "accounting-entries-detail",
    successRefreshTargets: ["aux_list"],
    defaults: {
      entry_type: "Policy",
      status: "Draft",
      policy: "",
      customer: "",
      insurance_company: "",
      currency: "TRY",
      local_amount: "",
      local_amount_try: "",
      external_amount: "",
      external_amount_try: "",
      external_ref: "",
    },
    fields: [
      { name: "entry_type", type: "select", label: i18nLabel("entry_type"), required: true, options: [
        option("Policy", "Policy"),
        option("Payment", "Payment"),
        option("Claim", "Claim"),
      ]},
      { name: "status", type: "select", label: i18nLabel("status"), required: true, options: [
        option("Draft", "Draft"),
        option("Synced", "Synced"),
        option("Failed", "Failed"),
      ]},
      { name: "policy", type: "select", label: i18nLabel("Policy"), optionsSource: "policies" },
      { name: "customer", type: "select", label: i18nLabel("customer"), optionsSource: "customers" },
      { name: "insurance_company", type: "select", label: i18nLabel("insurance_company"), optionsSource: "insuranceCompanies" },
      { name: "currency", type: "select", label: i18nLabel("currency"), options: [option("TRY", "TRY"), option("USD", "USD"), option("EUR", "EUR")] },
      { name: "local_amount", type: "number", label: i18nLabel("local_amount"), step: "0.01" },
      { name: "local_amount_try", type: "number", label: i18nLabel("local_amount_try"), step: "0.01" },
      { name: "external_amount", type: "number", label: i18nLabel("external_amount"), step: "0.01" },
      { name: "external_amount_try", type: "number", label: i18nLabel("external_amount_try"), step: "0.01" },
      { name: "external_ref", type: "text", label: i18nLabel("external_ref"), fullWidth: true },
    ],
  },
  reconciliation_item: {
    key: "reconciliation_item",
    title: i18nLabel("quick_reconciliation_item"),
    subtitle: i18nLabel("create_a_reconciliation_mismatch_record"),
    submitUrl: "acentem_takipte.acentem_takipte.api.quick_create.create_quick_reconciliation_item",
    resultKey: "reconciliation_item",
    openRouteName: "reconciliation-items-detail",
    successRefreshTargets: ["aux_list"],
    defaults: {
      accounting_entry: "",
      status: "Open",
      mismatch_type: "Amount",
      local_amount_try: "",
      external_amount_try: "",
      resolution_action: "",
      notes: "",
    },
    fields: [
      { name: "accounting_entry", type: "select", label: i18nLabel("accounting_entry"), optionsSource: "accountingEntries", required: true, fullWidth: true },
      { name: "status", type: "select", label: i18nLabel("status"), required: true, options: [
        option("Open", "Open"),
        option("Resolved", "Resolved"),
        option("Ignored", "Ignored"),
      ]},
      { name: "mismatch_type", type: "select", label: i18nLabel("mismatch_type"), required: true, options: [
        option("Amount", "Amount"),
        option("Currency", "Currency"),
        option("Missing External", "Missing External"),
        option("Missing Local", "Missing Local"),
        option("Status", "Status"),
        option("Other", "Other"),
      ]},
      { name: "local_amount_try", type: "number", label: i18nLabel("local_try"), step: "0.01" },
      { name: "external_amount_try", type: "number", label: i18nLabel("external_try"), step: "0.01" },
      { name: "resolution_action", type: "select", label: i18nLabel("resolution_action"), options: [
        option("", "Select"),
        option("Matched", "Matched"),
        option("Adjusted", "Adjusted"),
        option("Manual Override", "Manual Override"),
        option("Ignored", "Ignored"),
      ]},
      { name: "notes", type: "textarea", label: i18nLabel("notes"), rows: 3, fullWidth: true },
    ],
  },
  ownership_assignment: {
    key: "ownership_assignment",
    title: i18nLabel("quick_assignment"),
    subtitle: i18nLabel("create_a_record_ownership_and_operational_assignment"),
    submitUrl: "acentem_takipte.acentem_takipte.api.quick_create.create_quick_ownership_assignment",
    resultKey: "ownership_assignment",
    openRouteName: "ownership-assignments-detail",
    successRefreshTargets: ["ownership-assignments-list"],
    defaults: {
      source_doctype: "AT Customer",
      source_name: "",
      customer: "",
      policy: "",
      assigned_to: "",
      assignment_role: "Owner",
      status: "Open",
      priority: "Normal",
      due_date: "",
      notes: "",
    },
    fields: [
      { name: "source_doctype", type: "select", label: i18nLabel("source_type"), options: [
        option("AT Customer", "Customer"),
        option("AT Policy", "Policy"),
        option("AT Claim", "Claim"),
        option("AT Renewal Task", "Renewal Task"),
        option("AT Campaign", "Campaign"),
      ] },
      { name: "source_name", type: "text", label: i18nLabel("source_record"), required: true },
      { name: "customer", type: "select", label: i18nLabel("customer"), optionsSource: "customers" },
      { name: "policy", type: "select", label: i18nLabel("Policy"), optionsSource: "policies" },
      { name: "assigned_to", type: "text", label: i18nLabel("assigned_user"), required: true },
      { name: "assignment_role", type: "select", label: i18nLabel("assignment_role"), options: [
        option("Owner", "Owner"),
        option("Assignee", "Assignee"),
        option("Reviewer", "Reviewer"),
        option("Follower", "Follower"),
      ] },
      { name: "status", type: "select", label: i18nLabel("status"), options: [
        option("Open", "Open"),
        option("In Progress", "In Progress"),
        option("Blocked", "Blocked"),
        option("Done", "Done"),
        option("Cancelled", "Cancelled"),
      ] },
      { name: "priority", type: "select", label: i18nLabel("Priority"), options: [
        option("Low", "Low"),
        option("Normal", "Normal"),
        option("High", "High"),
        option("Critical", "Critical"),
      ] },
      { name: "due_date", type: "date", label: i18nLabel("due_date") },
      { name: "notes", type: "textarea", label: i18nLabel("notes"), rows: 3, fullWidth: true },
    ],
  },
  task: {
    key: "task",
    title: i18nLabel("quick_task"),
    subtitle: i18nLabel("create_a_task_and_follow-up_item"),
    submitUrl: "acentem_takipte.acentem_takipte.api.quick_create.create_quick_task",
    resultKey: "task",
    openRouteName: "tasks-detail",
    successRefreshTargets: ["tasks-list"],
    defaults: {
      task_title: "",
      task_type: "Follow-up",
      source_doctype: "AT Customer",
      source_name: "",
      customer: "",
      policy: "",
      claim: "",
      assigned_to: "",
      status: "Open",
      priority: "Normal",
      due_date: "",
      reminder_at: "",
      notes: "",
    },
    fields: [
      { name: "task_title", type: "text", label: i18nLabel("task_title"), required: true },
      { name: "task_type", type: "select", label: i18nLabel("task_type"), options: [
        option("Follow-up", "Follow-up"),
        option("Visit", "Visit"),
        option("Call", "Call"),
        option("Collection", "Collection"),
        option("Claim", "Claim"),
        option("Renewal", "Renewal"),
        option("Review", "Review"),
        option("Other", "Other"),
      ] },
      { name: "source_doctype", type: "select", label: i18nLabel("source_type"), options: [
        option("AT Customer", "Customer"),
        option("AT Policy", "Policy"),
        option("AT Claim", "Claim"),
        option("AT Renewal Task", "Renewal Task"),
        option("AT Campaign", "Campaign"),
        option("AT Ownership Assignment", "Assignment"),
        option("AT Call Note", "Call Note"),
      ] },
      { name: "source_name", type: "text", label: i18nLabel("source_record") },
      { name: "customer", type: "select", label: i18nLabel("customer"), optionsSource: "customers" },
      { name: "policy", type: "select", label: i18nLabel("Policy"), optionsSource: "policies" },
      { name: "claim", type: "text", label: i18nLabel("Claim") },
      { name: "assigned_to", type: "text", label: i18nLabel("assigned_user"), required: true },
      { name: "status", type: "select", label: i18nLabel("status"), options: [
        option("Open", "Open"),
        option("In Progress", "In Progress"),
        option("Blocked", "Blocked"),
        option("Done", "Done"),
        option("Cancelled", "Cancelled"),
      ] },
      { name: "priority", type: "select", label: i18nLabel("Priority"), options: [
        option("Low", "Low"),
        option("Normal", "Normal"),
        option("High", "High"),
        option("Critical", "Critical"),
      ] },
      { name: "due_date", type: "date", label: i18nLabel("due_date") },
      { name: "reminder_at", type: "datetime-local", label: i18nLabel("reminder_at") },
      { name: "notes", type: "textarea", label: i18nLabel("notes"), rows: 3, fullWidth: true },
    ],
  },
  activity: {
    key: "activity",
    title: i18nLabel("quick_activity"),
    subtitle: i18nLabel("log_a_completed_operational_step"),
    submitUrl: "acentem_takipte.acentem_takipte.api.quick_create.create_quick_activity",
    resultKey: "activity",
    openRouteName: "activities-detail",
    successRefreshTargets: ["activities-list"],
    defaults: {
      activity_title: "",
      activity_type: "Note",
      source_doctype: "AT Customer",
      source_name: "",
      customer: "",
      policy: "",
      claim: "",
      assigned_to: "",
      activity_at: "",
      status: "Logged",
      notes: "",
    },
    fields: [
      { name: "activity_title", type: "text", label: i18nLabel("activity_title"), required: true },
      { name: "activity_type", type: "select", label: i18nLabel("activity_type"), options: [
        option("Call", "Call"),
        option("Visit", "Visit"),
        option("Note", "Note"),
        option("Claim Update", "Claim Update"),
        option("Renewal Update", "Renewal Update"),
        option("Collection", "Collection"),
        option("Campaign", "Campaign"),
        option("Review", "Review"),
        option("Other", "Other"),
      ] },
      { name: "source_doctype", type: "select", label: i18nLabel("source_type"), options: [
        option("AT Customer", "Customer"),
        option("AT Policy", "Policy"),
        option("AT Claim", "Claim"),
        option("AT Task", "Task"),
        option("AT Campaign", "Campaign"),
      ] },
      { name: "source_name", type: "text", label: i18nLabel("source_record") },
      { name: "customer", type: "select", label: i18nLabel("customer"), optionsSource: "customers" },
      { name: "policy", type: "select", label: i18nLabel("Policy"), optionsSource: "policies" },
      { name: "claim", type: "text", label: i18nLabel("Claim") },
      { name: "assigned_to", type: "text", label: i18nLabel("assigned_user") },
      { name: "activity_at", type: "datetime-local", label: i18nLabel("activity_time") },
      { name: "status", type: "select", label: i18nLabel("status"), options: [
        option("Logged", "Logged"),
        option("Shared", "Shared"),
        option("Archived", "Archived"),
      ] },
      { name: "notes", type: "textarea", label: i18nLabel("notes"), rows: 3, fullWidth: true },
    ],
  },
  reminder: {
    key: "reminder",
    title: i18nLabel("quick_reminder"),
    subtitle: i18nLabel("create_a_time-based_follow-up_record"),
    submitUrl: "acentem_takipte.acentem_takipte.api.quick_create.create_quick_reminder",
    resultKey: "reminder",
    openRouteName: "reminders-detail",
    successRefreshTargets: ["reminders-list"],
    defaults: {
      reminder_title: "",
      source_doctype: "AT Customer",
      source_name: "",
      customer: "",
      policy: "",
      claim: "",
      assigned_to: "",
      status: "Open",
      priority: "Normal",
      remind_at: "",
      notes: "",
    },
    fields: [
      { name: "reminder_title", type: "text", label: i18nLabel("reminder_title"), required: true },
      { name: "source_doctype", type: "select", label: i18nLabel("source_type"), options: [
        option("AT Customer", "Customer"),
        option("AT Policy", "Policy"),
        option("AT Claim", "Claim"),
        option("AT Renewal Task", "Renewal Task"),
        option("AT Campaign", "Campaign"),
        option("AT Ownership Assignment", "Assignment"),
        option("AT Call Note", "Call Note"),
        option("AT Task", "Task"),
      ] },
      { name: "source_name", type: "text", label: i18nLabel("source_record") },
      { name: "customer", type: "select", label: i18nLabel("customer"), optionsSource: "customers" },
      { name: "policy", type: "select", label: i18nLabel("Policy"), optionsSource: "policies" },
      { name: "claim", type: "text", label: i18nLabel("Claim") },
      { name: "assigned_to", type: "text", label: i18nLabel("assigned_user"), required: true },
      { name: "status", type: "select", label: i18nLabel("status"), options: [
        option("Open", "Open"),
        option("Done", "Done"),
        option("Cancelled", "Cancelled"),
      ] },
      { name: "priority", type: "select", label: i18nLabel("Priority"), options: [
        option("Low", "Low"),
        option("Normal", "Normal"),
        option("High", "High"),
        option("Critical", "Critical"),
      ] },
      { name: "remind_at", type: "datetime-local", label: i18nLabel("reminder_time"), required: true },
      { name: "notes", type: "textarea", label: i18nLabel("notes"), rows: 3, fullWidth: true },
    ],
  },
};

function addQuickEditVariant(baseKey, editKey, enTitle, enSubtitle) {
  const base = quickCreateRegistry[baseKey];
  if (!base) return;
  quickCreateRegistry[editKey] = {
    ...base,
    key: editKey,
    title: i18nLabel(enTitle),
    subtitle: i18nLabel(enSubtitle),
    submitUrl: "acentem_takipte.acentem_takipte.api.quick_create.update_quick_aux_record",
    resultKey: "record",
    openRouteName: "",
    successRefreshTargets: ["aux_detail"],
  };
}

addQuickEditVariant("customer_relation", "customer_relation_edit", "Edit Customer Relation", "Update relation fields");
addQuickEditVariant("insured_asset", "insured_asset_edit", "Edit Insured Asset", "Update insured asset fields");
addQuickEditVariant("insurance_company", "insurance_company_edit", "Edit Insurance Company", "Update the insurance company master record");
addQuickEditVariant("branch_master", "branch_master_edit", "Edit Branch", "Update branch and company mapping");
addQuickEditVariant("sales_entity_master", "sales_entity_master_edit", "Edit Sales Entity", "Update sales organization record");
addQuickEditVariant("call_note", "call_note_edit", "Edit Call Note", "Update call note fields");
addQuickEditVariant("segment", "segment_edit", "Edit Segment", "Update segment fields");
addQuickEditVariant("campaign", "campaign_edit", "Edit Campaign", "Update campaign fields");
addQuickEditVariant("ownership_assignment", "ownership_assignment_edit", "Edit Assignment", "Update assignment fields");
addQuickEditVariant("task", "task_edit", "Edit Task", "Update task fields");
addQuickEditVariant("activity", "activity_edit", "Edit Activity", "Update activity fields");
addQuickEditVariant("reminder", "reminder_edit", "Edit Reminder", "Update reminder fields");
addQuickEditVariant("notification_template_master", "notification_template_master_edit", "Edit Notification Template", "Update notification template fields");
addQuickEditVariant("accounting_entry", "accounting_entry_edit", "Edit Accounting Entry", "Update accounting and reconciliation fields");
addQuickEditVariant("reconciliation_item", "reconciliation_item_edit", "Edit Reconciliation Item", "Update reconciliation mismatch record");

quickCreateRegistry.document_registry_edit = {
  key: "document_registry_edit",
  title: i18nLabel("edit_document"),
  subtitle: i18nLabel("update_secondary_file_name_and_notes"),
  submitUrl: "acentem_takipte.acentem_takipte.api.quick_create.update_quick_aux_record",
  resultKey: "record",
  openRouteName: "",
  successRefreshTargets: ["aux_detail"],
  defaults: {
    secondary_file_name: "",
    notes: "",
  },
  fields: [
    { name: "secondary_file_name", type: "text", label: i18nLabel("secondary_file_name"), required: true, fullWidth: true },
    { name: "notes", type: "textarea", label: i18nLabel("notes"), rows: 3, fullWidth: true },
  ],
};

const customerQuickCreateConfig = quickCreateRegistry.customer;
if (customerQuickCreateConfig) {
  customerQuickCreateConfig.defaults = {
    ...(customerQuickCreateConfig.defaults || {}),
    customer_type: "Individual",
    tax_id: "",
    birth_date: "",
    gender: "Unknown",
    marital_status: "Unknown",
    occupation: "",
  };
  customerQuickCreateConfig.fields = [
    { name: "full_name", type: "text", label: i18nLabel("full_name"), required: true, fullWidth: true },
    {
      name: "customer_type",
      type: "select",
      label: i18nLabel("customer_type"),
      required: true,
      options: [
        option("Individual", "Individual"),
        option("Corporate", "Corporate"),
      ],
    },
    {
      name: "tax_id",
      type: "text",
      required: true,
      label: ({ model, locale }) =>
        String(model?.customer_type || "Individual") === "Corporate"
          ? translateText("Tax Number", locale)
          : translateText("National ID Number", locale),
      help: ({ model, locale }) =>
        String(model?.customer_type || "Individual") === "Corporate"
          ? translateText("Enter a 10-digit tax number.", locale)
          : translateText("Enter an 11-digit Turkish national ID number.", locale),
    },
    {
      name: "birth_date",
      type: "date",
      label: i18nLabel("birth_date"),
      disabled: ({ model }) => String(model?.customer_type || "Individual") === "Corporate",
      help: ({ model, locale }) =>
        String(model?.customer_type || "Individual") === "Corporate"
          ? translateText("Disabled for corporate customers.", locale)
          : "",
    },
    { name: "phone", type: "text", label: i18nLabel("phone") },
    { name: "email", type: "email", label: i18nLabel("email") },
    {
      name: "gender",
      type: "select",
      label: i18nLabel("Gender"),
      disabled: ({ model }) => String(model?.customer_type || "Individual") === "Corporate",
      options: [
        option("Unknown", "Unknown"),
        option("Male", "Male"),
        option("Female", "Female"),
        option("Other", "Other"),
      ],
    },
    {
      name: "marital_status",
      type: "select",
      label: i18nLabel("marital_status"),
      disabled: ({ model }) => String(model?.customer_type || "Individual") === "Corporate",
      options: [
        option("Unknown", "Unknown"),
        option("Single", "Single"),
        option("Married", "Married"),
        option("Divorced", "Divorced"),
        option("Widowed", "Widowed"),
      ],
    },
    {
      name: "consent_status",
      type: "select",
      label: i18nLabel("consent_status"),
      options: [
        option("Unknown", "Unknown"),
        option("Granted", "Granted"),
        option("Revoked", "Revoked"),
      ],
    },
    { name: "assigned_agent", type: "text", label: i18nLabel("assigned_agent_(user)") },
    {
      name: "occupation",
      type: "text",
      label: i18nLabel("Occupation"),
      fullWidth: true,
      disabled: ({ model }) => String(model?.customer_type || "Individual") === "Corporate",
    },
    { name: "address", type: "textarea", label: i18nLabel("Address"), rows: 3, fullWidth: true },
  ];
}

export function getQuickCreateConfig(key) {
  return quickCreateRegistry[key] || null;
}

export function buildQuickCreateDraft(config, overrides = {}) {
  if (!config) return {};
  return { ...(config.defaults || {}), ...overrides };
}

export function getLocalizedText(value, locale = "en") {
  if (value == null) return "";
  if (typeof value === "string") return translateText(value, locale);
  if (typeof value === "function") {
    return value(locale);
  }
  if (typeof value === "object") return value[locale] || value.en || value.tr || "";
  return String(value);
}

